### DISCUSSION TITLE
JSON Patch denormalizer

### DISCUSSION THREAD

**Discussion by DurandA** [api-platform/core#4882] [General]
I'd like to implement a subset of the [`application/json-patch+json` format](https://github.com/api-platform/core/issues/759) to partially update the lists/collections of some of my resources without modifying _API Platform_.

1. Is it possible to call a custom controller based on the _Content-Type_ but keep the default wiring/actions for other content types with the same URIs? E.g. something like:
```php
#[ApiResource(itemOperations: [
    'get',
    'patch',
    'json_patch' => [
        'method' => 'PATCH',
        'formats' => ['application/json-patch+json'],
        'controller' => PatchBook::class,
    ],
])]
```
I still want the non-custom `application/merge-patch+json` to work (not the same as `application/json-patch+json`).

2. Is there a better way of implementing a custom format without forking _API Platform_? I took a look at the [serialization process](https://api-platform.com/docs/core/serialization/) but I am not sure how to implement this.

**Comment by DurandA** [comment]
After further investigation, here is how it can be implemented using a custom denormalizer.

## Register the `jsonpatch` format

Add `jsonpatch` to `apiplatform.yaml`:
```yaml
api_platform:
    patch_formats:
        json: ['application/merge-patch+json']
        jsonpatch: ['application/json-patch+json']
```
Register a JSON decoder for the jsonpatch format in `services.yaml`:
```yaml
services:
    ApiPlatform\Core\Serializer\JsonEncoder:
        public: false
        arguments:
            - 'jsonpatch'
        tags:
            - { name: serializer.encoder }
```

## Implement a JSON Patch denormalizer

Create a JSONPatchDenormalizer class:
```php
namespace App\Serializer;

use Symfony\Component\Serializer\Normalizer\ContextAwareDenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;

class JsonPatchDenormalizer implements ContextAwareDenormalizerInterface, DenormalizerAwareInterface
{
    use DenormalizerAwareTrait;

    private const ALREADY_CALLED = 'JSON_PATCH_DENORMALIZER_ALREADY_CALLED';

    public function denormalize($data, $type, $format = null, array $context = [])
    {
        // TODO
    }

    public function supportsDenormalization($data, $type, $format = null, array $context = []): bool
    {
        if (isset($context[self::ALREADY_CALLED])) {
            return false;
        }
        return $format === "jsonpatch";
    }
}
```
