### DISCUSSION TITLE
[Question] Is it possible to pass arguments to filter in yaml ?

### DISCUSSION THREAD

**Discussion by spincon** [api-platform/core#5135] [Q&A]
Hello,
i did try to pass arguments to my filters i did declare in resources.yml file:
```yml
App\Entity\OcExtendedPerson:
    shortName: 'Users'
    description: 'A company user'
    collectionOperations:
        get:
            method: 'GET'
            path: '/users'
            filters: 
            - 'App\Bridge\ApiPlatform\Filter\LdapFilterFilter'
            - 'App\Bridge\ApiPlatform\Filter\AttributeFilter'
    itemOperations:
        get:
            method: 'GET'
            path: '/users/{id}'
    properties:
        dn:
            identifier: true
```

But i did not succeed in finding the right syntax, is it possible ?

Thanks in advance,
Regards
