### DISCUSSION TITLE
Index is not related to the mapping configuration

### DISCUSSION THREAD

**Discussion by rapaelector** [api-platform/core#5271] [Ideas]
@soyuka 
When I custom the index on the configuration like this : 

```
api_platform:
    ......
    mapping:
        paths:
            - '%kernel.project_dir%/src/Model'
    elasticsearch:
        hosts: [ '%env(ELASTICSEARCH_HOST)%' ]
        mapping:
            App\Model\Document:
                index: '%env(APP_ENV)%_hubble_document'
                type: document
```

Why the index is not handle here

https://github.com/api-platform/core/blob/main/src/Elasticsearch/Metadata/Resource/Factory/ElasticsearchProviderResourceMetadataCollectionFactory.php#L90

 It still search the shortname on the operation that is not the index but the name of the entity 
for example here it will be "document"
