### DISCUSSION TITLE
Invalid input syntax for type uuid in subresources

### DISCUSSION THREAD

**Discussion by klobastov** [api-platform/core#5351] [Q&A] [answered]
Admin GUI cannot represent uuid in string and try to send [object Object] as id.

"An exception occurred while executing a query: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type uuid: \"[object Object]\"\nCONTEXT:  unnamed portal parameter $1 = '...'"

![image](https://user-images.githubusercontent.com/3277751/213630588-87d2038e-2009-4796-9a4d-d8b974ca7bb3.png)
![image](https://user-images.githubusercontent.com/3277751/213630665-94fa1c1f-be24-4ab7-8bf2-37a921d472c1.png)
![image](https://user-images.githubusercontent.com/3277751/213630842-5b4cc68d-844d-4fcc-b1b8-3db107e3db82.png)

Response contains valid order id, but next request contains id as [object object].

```
#[ApiResource]
class OrderNotification
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id = null;

    #[ORM\ManyToOne(targetEntity: Order::class, cascade: ['persist'])]
    #[ORM\JoinColumn(name: 'order_id', referencedColumnName: 'id', nullable: false)]
    #[Link(fromProperty: 'order')]
    private ?Order $order = null;
}
```

```
Gate\Entity\OrderNotification:
  attributes:
    id:
      groups: [ 'order-notification:output']
    type:
      groups: [ 'order-notification:output', 'order-notification:input' ]
    status:
      groups: [ 'order-notification:output', 'order-notification:input' ]
    state:
      groups: [ 'order-notification:output', 'order-notification:input' ]
    order:
      groups: [ 'order-notification:output', 'order-notification:input' ]

```

```
resources:
  Gate\Entity\OrderNotification:
    order:
      serialId: ASC

    normalizationContext:
      groups: [ 'order-notification:output' ]
    denormalizationContext:
      groups: [ 'order-notification:input' ]

    operations:
      order_all_notification_list:
        class: 'ApiPlatform\Metadata\GetCollection'
        filters: [ 'default.id' ]
        security: is_granted('ORDER_LIST', object)

      order_notification_list:
        class: 'ApiPlatform\Metadata\GetCollection'
        filters: [ 'default.id' ]
        security: is_granted('ORDER_LIST', object)
        uriTemplate: '/orders/{orderId}/notifications.{_format}'
        uriVariables:
          orderId:
            fromClass: Gate\Entity\Order
            toProperty: 'order'

      order_notification_view:
        class: 'ApiPlatform\Metadata\Get'
        security: is_granted('ORDER_LIST', object)
        uriTemplate: '/orders/{orderId}/notifications/{id}.{_format}'
        uriVariables:
          orderId:
            fromClass: Gate\Entity\Order
            toProperty: 'order'
          id:
            fromClass: Gate\Entity\OrderNotification

      order_notification_create:
        class: 'ApiPlatform\Metadata\Post'
        security: is_granted('ORDER_CREATE', object)

      order_notification_update:
        class: 'ApiPlatform\Metadata\Put'
        security: is_granted('ORDER_UPDATE', object)
        uriTemplate: '/orders/{orderId}/notifications/{id}.{_format}'
        uriVariables:
          orderId:
            fromClass: Gate\Entity\Order
            toProperty: 'order'
          id:
            fromClass: Gate\Entity\OrderNotification

      order_notification_update_partial:
        class: 'ApiPlatform\Metadata\Patch'
        security: is_granted('ORDER_UPDATE', object)
        uriTemplate: '/orders/{orderId}/notifications/{id}.{_format}'
        uriVariables:
          orderId:
            fromClass: Gate\Entity\Order
            toProperty: 'order'
          id:
            fromClass: Gate\Entity\OrderNotification

      order_notification_delete:
        class: 'ApiPlatform\Metadata\Delete'
        security: is_granted('ORDER_CREATE', object)
        uriTemplate: '/orders/{orderId}/notifications/{id}.{_format}'
        uriVariables:
          orderId:
            fromClass: Gate\Entity\Order
            toProperty: 'order'
          id:
            fromClass: Gate\Entity\OrderNotification
```

**Comment by klobastov** [comment, marked as answer]
solution:
```
properties:
  Gate\Entity\OrderNotification:
    order:
      readableLink: false
      writableLink: false
```
