### DISCUSSION TITLE
API Configuration | enable_docs

### DISCUSSION THREAD

**Discussion by renja-g** [api-platform/core#5439] [Q&A]
Hi, I was trying to the docs by setting `enable_docs = flase`
```yml
# api/config/routes/api_platform.yaml
api_platform:
    resource: .
    type: api_platform
    prefix: /api

    # Enable the docs.
    enable_docs: true
```

But I get an error that the key `enable_docs` is unsupported.

Then I also noticed that in the docs it says that the `api_platform.yaml` file is in `packages` not in `routes`
But the Demo app has the config in `routes` https://github.com/api-platform/demo/blob/main/api/config/routes/api_platform.yaml

To be honest I'm a bit confused.
