### DISCUSSION TITLE
Can we have different route prefix per path mapping?

### DISCUSSION THREAD

**Discussion by jelovac** [api-platform/core#5592] [Q&A]
Hi,

Is it possible to define different path prefixes globally per Resource path mapping?

What I want to achieve is to have something like following:

```
src/Api/Alpha/Resource/User => /api/alpha/users

src/Api/Beta/Resource/User => /api/beta/users
```

Currently I can do this by defining `routePrefix ` on individual API Platform resource. However, I would like to know if there is a more flexible approach?

I also tried different approach by overriding `config/routes/api_platform.yml`:

```
SwaggerUI:
    path: /
    controller: api_platform.swagger_ui.action

AlphaAPI:
    resource: ../../src/Api/Alpha/
    prefix: /api/alpha
    type: api_platform

BetaAPI:
    resource: ../../src/Api/Beta/
    prefix: /api/beta
    type: api_platform
```

However this did not work correctly. Basically all routes in swagger had beta prefix.
