### DISCUSSION TITLE
What is the best way to disable the documentation in production ?

### DISCUSSION THREAD

**Discussion by bbarhoum1** [api-platform/core#6282] [Q&A]
I'm trying to hide/disable documentation for the production. The configuration option 'enable_docs' is not working for me.
It works with this cong:
```yaml
when@prod:
    api_platform:
        enable_docs: false
        enable_swagger_ui: false
        enable_re_doc: false
        enable_swagger: false
        enable_entrypoint: false
```

Is this the best way or there is an issue with the "enable_docs" configuration ?
Thank you for your help :)

**Comment by pauljura** [comment]
Hi, I'm not sure if this is the best way but this is how I do it, in my routes.yaml file:

```
swagger_ui:
    path: /docs
    controller: api_platform.swagger_ui.action
    condition: "'%kernel.environment%' != 'prod'"
```
