### ISSUE TITLE
Collection of Doctrine Single table inheritance entities

### ISSUE THREAD

**Issue by desmax** [api-platform/core#1071]
I have an object, that has collection containing different entities, that use Single inheritance.
Problem is that only base fields are fetched, entity specific are null. As I understand its happening because Doctrine partial query is used, but how can I force load all fields for given collection?

**Comment by soyuka** [comment]
#1025 can you try the `2.0` branch?

**Comment by desmax** [comment]
@soyuka I am sorry for duplicate. And I am on master already.

**Comment by soyuka** [comment]
Hmm this patch hasn't been merged back to master yet :|.

**Comment by soyuka** [comment]
@desmax done through #1072 can you update?

**Comment by desmax** [comment]
@soyuka I don't seem to see any difference...

**Comment by soyuka** [comment]
ping @bwegrzyn 

Quoting some related issues:

- #1069
- https://github.com/api-platform/api-platform/issues/277
- https://github.com/api-platform/api-platform/issues/266
- https://github.com/api-platform/api-platform/issues/263
- https://github.com/api-platform/api-platform/issues/272

I'll investigate this and hopefully find a clean fix.

**Comment by bwegrzyn** [comment]
@desmax Can you try to disabled eager loading and try again?

```yml
api_platform:
    eager_loading:
        enabled: false
```

Also, can you provide a sample of your entities?

**Comment by soyuka** [comment]
Even better disable it on the resource:

```
/*
 * @ApiResource(attributes={"force_eager"=false})
 */
```

**Comment by bwegrzyn** [comment]
@soyuka Interestingly... that doesn't disabled eager loading on a resource for me. I have to force it through config.yml. That might be a separate issue.

**Comment by soyuka** [comment]
This is the condition:
```
            if (false === $forceEager && ClassMetadataInfo::FETCH_EAGER !== $mapping['fetch']) {
```

Anyway, I need to refactor this fetchEager thing #1035

**Comment by desmax** [comment]
@bwegrzyn disabling eager loading via config does help.
On resource object I have one to many relation to base single inherited master class, marked as abstract.
All non abstract entities extend base class, some of them have additional fields, that are not present in base class. Base class is marked with `@ApiResource()` annotation.
```    
oneToMany:
  history:
     targetEntity: AppBundle\Entity\HistoryAction\HistoryAction
     mappedBy: vacancy
```

````
AppBundle\Entity\HistoryAction\HistoryAction:
    type: entity

    inheritanceType: SINGLE_TABLE

    discriminatorColumn:
        name: type
        type: string

    discriminatorMap:
        created:              Created
        ...

    cache:
        usage: NONSTRICT_READ_WRITE

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    gedmo:
        translation:
            locale: language

    fields:
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create

    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: history
            joinColumn:
                nullable: false

        vacancy:
            targetEntity: AppBundle\Entity\Vacancy
            inversedBy: history
            joinColumn:
                nullable: false

````
````
AppBundle\Entity\HistoryAction\Created:
    type: entity

    fields:
        initialFields:
            type: array
````
Another thing that bugging me is that array typed `initialFields` is not serialized unless I mark sub entity as ApiResource (field value is fetched and not null). That makes no sense to mark it as ApiResource, for now I force that value to serialize via custom Normalizer.
