### ISSUE TITLE
[Question] Filter collections based on related entity id

### ISSUE THREAD

**Issue by abarani** [api-platform/core#1095]
I must be missing something simple here but i cannot figure out the right way to go to filter collections based on a related entity id.

Here is a basic use case:

 - I have a `Customer` and an `Subscription` entity;
 - The `Subscription` entity has a manyToOne relationship with the `Customer` one;
 - Both entities are exposed through the API;
 - I want to add a filter on the `/subscriptions` endpoint to filter out entities related to a given customer such that a call to `/subscriptions?customer=/customers/1` will list all subscriptions related to the given customer.

The only solution that I think is working is adding a `NumericFilter` to the nested `customer.id` property but it feels a bit hacky. On the client side there are only full string ids. I have to extract the numeric part from the full id using a regular expression or something.

Am I missing something? What is the right way to proceed?

**Comment by soyuka** [comment]
I'm filtering using the `id` (indeed here the numeric part `/subscriptions?customer=1`). Not sure if filtering by `IRI` is supported, but it might be a good feature.

**Comment by abarani** [comment]
Ok, I completely missed the paragraph in the documentation that talks about filtering by relations. :neutral_face:

With a `SearchFilter` both IRI (`/subscriptions?customer=/customers/1`) and numeric id (`/subscriptions?customer=1`) are supported.

Here is the correct solution for reference:

```yaml
# app/config/services.yml

services:
    subscription.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { customer: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'subscription.search' } ]
```
