### ISSUE TITLE
Nelmio api doc integration throws an error

### ISSUE THREAD

**Issue by alfabetagama** [api-platform/core#1131]
```
api_platform:
    enable_nelmio_api_doc: true
```

Throws an error:

`The service "api_platform.nelmio_api_doc.annotations_provider" has a dependency on a non-existent service "api_platform.hydra.normalizer.documentation".`

**Comment by meyerbaptiste** [comment]
You have to enable the `jsonld` format:

```yaml
api_platform:
    # ...
    formats:
        # ...
        jsonld: ['application/ld+json']
    error_formats:
        # ...
        jsonld: ['application/ld+json']

**Comment by alfabetagama** [comment]
@meyerbaptiste thanks.

**Comment by Nek-** [comment]
Hello,

I use the following:

```yaml
api_platform:
    enable_nelmio_api_doc: true
    formats:
        json:
            mime_types: ['application/json']
```

It looks like the fact of enabling nelmio API imply that this is wrong because there is no jsonld format specified. Why do I need to enable jsonld format? o_O
