### ISSUE TITLE
[QUESTION] How to create nested custom search

### ISSUE THREAD

**Issue by ad3n** [api-platform/core#1158]
Background:
```
I use Doctrine Soft Deletable behavior and that is work perfectly. 

But i have problem when the record is deleted and having relation to other table(s) because the record still counted
```

What i want:
```
I have an idea to create custom filter to handling it. Just because the field is nested field, i have no idea how to create it.

I read the documentation (https://api-platform.com/docs/core/filters#creating-custom-filters) and try to create read the code directly but i have no information how to it work.

Can you help me how to create custom filter with nested field? 
```

Thank you very much

**Comment by soyuka** [comment]
Is this what you want? Filter on the `property` of your `relation`:

```yaml
services:
    offer.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { relation.property: 'partial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'offer.search' } 
```

```php
<?php

// src/AppBundle/Entity/Offer.php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ApiResource(attributes={"filters"={"offer.search"}})
 */
class Offer
{
    // ...
}
```

Ref: https://api-platform.com/docs/core/filters#search-filter
