### ISSUE TITLE
CircularReferenceException in custom ItemDataProvider

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/core#1165]
Hello,

I'm implementing 2 custom data providers, connecting on WordPress API: 1 for collection, 1 for item. For the first one, I can easily inject the `serializer` service. But for the item, I get a CircularReferenceException.

A solution would be to create an event subscriber which listens to `kernel.request` event and serialize the controller result, but it's not generic at all (and I don't find it very clean…).

A better solution would be to listen to `SerializerAwareInterface` on my ItemDataProvider from API Platform, and if so call `setSerializer` method.

What do you think of it @api-platform/core-team?

**Comment by teohhanhui** [comment]
A data provider isn't supposed to do serialization?

**Comment by vincentchalamon** [comment]
@teohhanhui So how can I convert my WordPress API JSON result to my entity?

**Comment by soyuka** [comment]
Just to understand the context you're parsing the resulting JSON (from WP API) and then populating some entities?

**Comment by vincentchalamon** [comment]
@soyuka Yep. I have a `PostCollectionDataProvider` which calls WordPress API (through guzzle) to get the list of posts in JSON, I need to serialize this list to an array of `AppBundle\WordPress\Post` objects. Same for `PostItemDataProvider`

**Comment by vincentchalamon** [comment]
Then, I'll have the same context with `Tag` & `Category` objects

**Comment by teohhanhui** [comment]
> I need to serialize this list to an array of AppBundle\WordPress\Post objects. 

Do you mean deserializing the JSON data into the `Post` objects? I guess it makes sense then...

> A better solution would be to listen to SerializerAwareInterface on my ItemDataProvider from API Platform, and if so call setSerializer method.

Or some other tricks like lazy services which should help...

**Comment by soyuka** [comment]
to deserialize then not serialize :p. 

I don't get the issue here, you should be able to use your own serializer/normalizer.

**Comment by vincentchalamon** [comment]
To deserialize of course, my bad 😉

**Comment by vincentchalamon** [comment]
> Or some other tricks like lazy services which should help...

@teohhanhui Like a service locator?

```yml
# services.yml
services:
    app.serializer.locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                serializer: '@serializer'
        tags:
            - { name: container.service_locator }

    App\DataProvider\PostItemDataProvider:
        class: App\DataProvider\PostItemDataProvider
        arguments: ['@csa_guzzle.client.word_press', '@app.serializer.locator']
        tags:
            - { name: api_platform.item_data_provider }
```
```php
// PostItemDataProvider.php
class PostItemDataProvider implements ItemDataProviderInterface
{
    private $client;
    private $container;

    /**
     * @param Client $client
     */
    public function __construct(Client $client, ContainerInterface $container)
    {
        $this->client = $client;
        $this->container = $container;
    }

    /**
     * {@inheritdoc}
     */
    public function getItem(string $resourceClass, $id, string $operationName = null, array $context = [])
    {
        if (Post::class !== $resourceClass) {
            throw new ResourceClassNotSupportedException();
        }

        try {
            return $this->container->get('serializer')->deserialize($this->client->get('wp-json/wp/v2/posts/'.$id)->getBody(), Post::class, 'json');
        } catch (RequestException $exception) {
            return null;
        }
    }
}
```
