### ISSUE TITLE
after upgrading to v2.1.0-beta.1 each request takes up to half a minute

### ISSUE THREAD

**Issue by karser** [api-platform/core#1169]
![image](https://user-images.githubusercontent.com/1675033/26974374-b23ed396-4d23-11e7-8b3f-ecf44a63e3de.png)

![image](https://user-images.githubusercontent.com/1675033/26974381-b877ce66-4d23-11e7-90bd-bc2260c0cd16.png)

![image](https://user-images.githubusercontent.com/1675033/26974429-04314a6c-4d24-11e7-9e24-e2d391bf398c.png)

my config:
```
api_platform:
    title: Survos
    description: Rest API
    enable_fos_user: true
    enable_swagger: true
    enable_nelmio_api_doc: true
    collection:
        pagination:
            client_items_per_page: true
            items_per_page_parameter_name: itemsPerPage
    exception_to_status:
        'Symfony\Component\Security\Core\Exception\AuthenticationException': 401
        'Symfony\Component\Security\Core\Exception\AccessDeniedException': 403
        'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
```

I have lot of resources, custom filters and listeners, can't post them all here. So the issue isn't isolated, but it was working just fine with v2.0.9. Do you guys have any thoughts so far?

**Comment by tacman** [comment]
Removing all the Waves in diamond.yml allows the fixtures to load.

**Comment by dunglas** [comment]
It's in dev mode? Do you use Doctrine?

**Comment by karser** [comment]
yes, it's dev mode, doctrine 2.6.x-dev

**Comment by dunglas** [comment]
Even after the first request? This operation should happen only during the cache clearing.

**Comment by soyuka** [comment]
Do you have subresources? Or this means that [this condition](https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Routing/ApiLoader.php#L141) isn't doing what it should.

**Comment by karser** [comment]
@dunglas Yes, after each request. I tried a few times using different clients.
@soyuka I don't have subresources. I'll check if this condition is being met

**Comment by soyuka** [comment]
It's the only thing that changed in route loading (blackfire points to ApiLoader).

**Comment by karser** [comment]
`$propertyMetadata->hasSubresource()` is always null.
if blackfire and xdebug are disabled it takes 5-7 seconds, doesn't matter whether I load item or collection:
![image](https://user-images.githubusercontent.com/1675033/26984908-ef93cd5c-4d49-11e7-8ca7-4f6cc852f375.png)
I'll try to isolate the issue.

**Comment by karser** [comment]
When `$kernel = new AppKernel('prod', $debug=false);` it's 100ms
![image](https://user-images.githubusercontent.com/1675033/26985091-aea62c8a-4d4a-11e7-80df-3a707bb5bcac.png)
When `$kernel = new AppKernel('prod', $debug=true);` it's 5s
![image](https://user-images.githubusercontent.com/1675033/26985201-2ba9c58e-4d4b-11e7-8580-09992e9ee905.png)

**Comment by dunglas** [comment]
Do you have upgraded to Symfony 3.3 at the same time? If it's the case, can you test with API Platform 2.0.9 but Symfony 3.3 instead of 3.2 to test if it's not a problem related to SF?

**Comment by karser** [comment]
All benchmarks are on Symfony 3.3.2.
Here is api-platform **2.0.9** results.
When $kernel = new AppKernel('prod', $debug=false); it's ~150ms
![image](https://user-images.githubusercontent.com/1675033/26990820-b102feac-4d60-11e7-9d21-bf19bd04c3ac.png)
When $kernel = new AppKernel('prod', $debug=true); it's ~600ms
![image](https://user-images.githubusercontent.com/1675033/26990869-f59a4b7e-4d60-11e7-9fed-7d8e324af607.png)

**Comment by soyuka** [comment]
@karser are you able to give more details on this matter? Screen of the profiler, number of relations / items, number of queries executed, a blackfire profile you could share? I'm trying to rewind our commit history with performance tests to see if something comes out.

**Comment by soyuka** [comment]
So, I did try a collection with 2 relations per items:

on master
back to 6457f244a06d62c9102e0d6bf56243b646b2fe6d (it's before we merged embedded)
back to 2.0 

and I see literally no difference (master was slightly faster according to blackfire). 

Note that apcu cache is enabled with something like this:

```
    api_platform.cache.metadata.property:
        class: Symfony\Component\Cache\Adapter\ApcuAdapter
    api_platform.cache.metadata.resource:
        class: Symfony\Component\Cache\Adapter\ApcuAdapter
    api_platform.cache.route_name_resolver:
        class: Symfony\Component\Cache\Adapter\ApcuAdapter
    api_platform.cache_identifiers_extractor:
        class: Symfony\Component\Cache\Adapter\ApcuAdapter
```

Tests done on dev mode.
