### ISSUE TITLE
Get a resource in a service

### ISSUE THREAD

**Issue by shiftSh** [api-platform/core#1232]
Hi. I'm using LexikJWTAuthenticationBundle to provide jwt authentication to my app. After the authentication I want to add the authenticated user Resource on the jwt response. I followed the LexikJWTAuthenticationBundle documentation and now I need to get the user Resource in the service . I want to use the forward method ([forward to another controller internally](https://symfony.com/doc/current/controller/forwarding.html)) and I need the controller which I must use as argument to the forward() method ;

Here is my code
`app/config/services.yml`

```yaml

    ...
        acme_api.event.authentication_success_listener:
        class: AppBundle\EventListener\AuthenticationSuccessListener
        arguments:
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    ...
```
`src/AppBundle/EventListener/AuthenticationSuccessListener.php`

```php
// src/AppBundle/EventListener/AuthenticationSuccessListener.php
<?php
namespace AppBundle\EventListener;

use AppBundle\Entity\User;
use Lexik\Bundle\JWTAuthenticationBundle\Event\AuthenticationSuccessEvent;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\HttpKernel\HttpKernelInterface;

class AuthenticationSuccessListener {

    private $container;

    public function __construct(Container $container)
    {
        $this->container = $container;
    }

    /**
     * @param AuthenticationSuccessEvent $event
     */
    public function onAuthenticationSuccessResponse(AuthenticationSuccessEvent $event)
    {
        $data = $event->getData();
        $user = $event->getUser();

        if (!$user instanceof User) {
            return;
        }

        $toForwardRequest = $this->container->get('request_stack')->getCurrentRequest();
        $toForwardRequest->attributes->add(array('_resource'=>'User'));

        /* WHICH CONTROLLER DO I NEED TO PASS TO $this->forward()*/
        
       $userInfoResponse = $this->forward('CONTROLLER NAME',array(
            'request'=>$toForwardRequest,
            'id'=> $user->getId()
        ));

        $data['user'] = array($userInfoResponse);

        $event->setData($data);
    }

    private function forward($controller, array $path = array(), array $query = array())
    {
        $path['_controller'] = $controller;
        $subRequest = $this->container->get('request_stack')->getCurrentRequest()->duplicate($query, null, $path);
        return $this->container->get('http_kernel')->handle($subRequest, HttpKernelInterface::SUB_REQUEST);
    }

}

```
So  WHICH CONTROLLER DO I NEED TO PASS TO $this->forward().

I look forward to your response! Thanks
