### ISSUE TITLE
Identifier date doctrine type converts to value with time that broke item query result

### ISSUE THREAD

**Issue by cve** [api-platform/core#1233]
Hi,

when I have a Post with date field as doctrine date type, and I want to use that field as ApiProperty identifier then in ItemProvider there is a trait that converts a parameter value into doctrine type which for example transforms "2017-01-01" into "2017-01-01 00:00:00" that fails on query result.

**Comment by soyuka** [comment]
We had the same issue and I think that #1478 is a slightly better fix, indeed it allows you to add a normalizer for any identifer (uuid or datetime), for example:

```php
<?php
// DateIdentifierNormalizer

namespace Core\ApiBundle\Identifier\Normalizer;
use AppBundle\Orm\Types\IdxDate; // using a custom Doctrine Type here

use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;

class DateNormalizer implements DenormalizerInterface
{
    public function denormalize($data, $class, $format = null, array $context = [])
    {
        return (string) (new IdxDate($data));
    }

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === \DateTime::class; //I'm working on this there's an issue on PropertyInfo regarding \DateTime extended classes
    }
}
```

```yaml
services:
    bender_api.date_identifier_normalizer:
        public: false
        class: Core\ApiBundle\Identifier\Normalizer\DateNormalizer
        tags: [ { name: 'api_platform.identifier_normalizer' } ]
```

```php
<?php
namespace AppBundle\Orm\Types;

class IdxDate extends \DateTime
{
    public function __toString()
    {
        return $this->format('d-m-Y');
    }

    public static function createFromFormat($format, $time, $object = null)
    {
        $d = \DateTime::createFromFormat($format, $time);

        $t = new self();
        $t->setTimestamp($d->getTimeStamp());

        return $t;
    }
}
```

Keeping this here for docs
