### ISSUE TITLE
How to provide id (primary key) in schema.yml file?

### ISSUE THREAD

**Issue by banandam** [api-platform/core#1267]
### Actual Result

While creating entity from schema.yml, primary key data type set as `int` as default.

### Expected Result

We have set `generateId: false` in schema.yml file. We have to mention `id` in schema.yml file. Let us know the syntax to do that?

**Comment by rrjanbiah** [comment]
@banandam By looking at the code https://github.com/api-platform/schema-generator/blob/master/src/TypesGenerator.php#L316 I think, you have to use ``isId=true``

**Comment by banandam** [comment]
#### Schema
```
types:
    Users:                       
        parent: false
        properties:
            id:
                range: "Integer"
                generator:
                    strategy: AUTO                
            createdAt:
                range: "DateTime"
            updatedAt:
                range: "DateTime"
            username:
                range: "Text"
                ormColumn: 'type="string", length=255'
            email:
                range: "Text"
                ormColumn: 'type="string", length=255'
            password:
                range: "Text"
                ormColumn: 'type="string", length=255'
            firstName:
                range: "Text"
                ormColumn: 'type="string", length=255, nullable=true'
                nullable: true
            lastName:
                range: "Text"
                ormColumn: 'type="string", length=255, nullable=false'
                nullable: false
```
#### Error

  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "generator" under "config.types.Users.properties.id"

**Comment by meyerbaptiste** [comment]
Test this:

```yaml
id:
    range: "Integer"
    isId: true
```

But the strategy cannot be modified.

**Comment by banandam** [comment]
```
types: 
    Users:                       
        parent: false
        properties:
            id:
                range: "Integer"
                isId: true
            createdAt:
                range: "DateTime"
            updatedAt:
                range: "DateTime"
            username:
                range: "Text"
                ormColumn: 'type="string", length=255'
            email:
                range: "Text"
                ormColumn: 'type="string", length=255'
            password:
                range: "Text"
                ormColumn: 'type="string", length=255'
            firstName:
                range: "Text"
                ormColumn: 'type="string", length=255, nullable=true'
                nullable: true
            lastName:
                range: "Text"
                ormColumn: 'type="string", length=255, nullable=false'
                nullable: false

generateId: false
```

#### CMD

```
php vendor/bin/schema generate-types src/ app/config/schema.yml
```

#### Error
```
                                                                                 
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "isId" under "config.types.Users.properties.id"            
                                                                                 

generate-types <output> [<config>]

```

**Comment by meyerbaptiste** [comment]
Oh, I see, this is not supported by the `ApiPlatform\SchemaGenerator\TypesGeneratorConfiguration` class... So, there is currently no solution to do this.

My advice would be to not use the schema generator currently and generate your entities by hand.
Too much confusion, painful and the project is no longer maintained enough. But PRs are welcome.

**Comment by Saphyel** [comment]
@banandam I guess I'm replying a bit late.. but should be something like:
```
namespaces:
  entity: App\Entity
id:
  generationStrategy: "uuid"
types:
```
And I think this issue belong to https://github.com/api-platform/schema-generator not here...
