### ISSUE TITLE
@Assert\NotNull annotation automatically added in all fields

### ISSUE THREAD

**Issue by banandam** [api-platform/core#1268]
### Actual Result
When generate entity file using schema.yml file, `@Assert\NotNull` annotation automatically added.

### Expected Result
`@Assert\NotNull` should not add in entity file

#### /api-platform/app/config/schema.yml

```
    Users:                       
        parent: false
        properties:
            createdAt: { range: "DateTime" }
            updatedAt: { range: "DateTime" } 
            username: { range: "Text", ormColumn: 'type="string", length=255' }
            email: { range: "Text", ormColumn: 'type="string", length=255' }
            password: { range: "Text", ormColumn: 'type="string", length=255' }
```

#### Entity generate using command:

```
php vendor/bin/schema generate-types src/ app/config/schema.yml
```

#### /api-platform/src/AppBundle/Entity/Users.php

```
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * The most generic type of item.
 *
 * @see http://schema.org/Thing Documentation on Schema.org
 *
 * @ORM\Entity
 * @ApiResource(iri="http://schema.org/Thing")
 */
class Users
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     * @Assert\NotNull
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     * @Assert\NotNull
     */
    private $updatedAt;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     * @Assert\Type(type="string")
     * @Assert\NotNull
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     * @Assert\Type(type="string")
     * @Assert\NotNull
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     * @Assert\Type(type="string")
     * @Assert\NotNull
     */
    private $password;
    ....
    ....
    ....
}
```

**Comment by rrjanbiah** [comment]
@banandam Have you tried ``nullable=true`` ? 

Example is at https://github.com/api-platform/schema-generator/blob/master/tests/config/address-book.yml#L22

**Comment by banandam** [comment]
@rrjanbiah  In table set as "NULL". But entity `@Assert\NotNull` added default. In example given below

```
    Users:                       
        parent: false
        properties:
            createdAt: { range: "DateTime" }
            updatedAt: { range: "DateTime" } 
            role: { range: "Roles", ormColumn: 'type="bigint"' }
            username: { range: "Text", ormColumn: 'type="string", length=255' }
            email: { range: "Text", ormColumn: 'type="string", length=255' }
            password: { range: "Text", ormColumn: 'type="string", length=255' }
            firstName: { range: "Text", ormColumn: 'type="string", length=255, nullable=true' }
            lastName: { range: "Text", ormColumn: 'type="string", length=255, nullable=true' }
```

#### Entity/Users.php

```
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     * @Assert\Type(type="string")
     * @Assert\NotNull
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type(type="string")
     * @Assert\NotNull
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type(type="string")
     * @Assert\NotNull
     */
    private $lastName;
```

![table_users](https://user-images.githubusercontent.com/3142065/28454785-299d1a8a-6e1a-11e7-97ef-5e225876158b.jpg)
