### ISSUE TITLE
Global DateTime format

### ISSUE THREAD

**Issue by mcanepa** [api-platform/core#1285]
Right now, if I want entity's attributes of type date/datetime to be displayed without timezone I do something like this:

`@ApiResource(attributes={"normalization_context"={"groups"={"my_group"},"datetime_format"="Y-m-d H:i:s"}})`

That works for `GET /entity/{id}`, but not for `GET /entity/`

How can I set this datetime format globally and not for a especific entity? So every date/datetime attribute of any entity is displayed by the format I specify.

**Comment by dunglas** [comment]
You can do this by setting the `$format` argument of the `DateTimeNormalizer` class: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/DateTimeNormalizer.php#L44

In YAML:

```yaml
# app/config/config.yaml

serializer.normalizer.datetime:
    arguments: ['Y-m-d H:i:s']
```

If you want to contribute back to Symfony, it would be nice to open a PR to make this explicit in the Symfony documentation.

**Comment by fulopattila122** [comment]
@dunglas Are you sure that this is the key?
I've added the yaml above and I get this error:

*FileLoaderLoadException*
_There is no extension able to load the configuration for "serializer.normalizer.datetime"_

**Comment by pasinter** [comment]
for anyone facing this issue: I was able to change the format of the DateTimeNormalizer by adding this:
`
# config.services.yml
Symfony\Component\Serializer\Normalizer\DateTimeNormalizer:
        arguments:
            $format: 'Y-m-d H:i:s'
`

**Comment by tsadiq** [comment]
In case anyone comes here in search for answers, i got it to work on 4.2 with 
```
services:
    Symfony\Component\Serializer\Normalizer\DateTimeNormalizer:
        arguments:
            $defaultContext:
                datetime_format: 'Y-m-d'
```

It also works simply with 
```
            $defaultContext: 'Y-m-d'
```
but that is deprecated so you should avoid this ^^
