### ISSUE TITLE
POST (create new item) with nested data

### ISSUE THREAD

**Issue by GonZOO82** [api-platform/core#1363]
I would like POST with nested data, but don't succeed.

Sample:
```
{
    "title": "test",
    "cover": {  //ManyToOne connection to MediaItem Entity
        "id": 1 // This MediaItem is exist
    }
}
```
Response: `Update is not allowed for this operation.`

but when I update item (PUT) then process is good.

I don't want to use this code:
```
{
    "title": "test",
    "cover": "/media_item/1"
}
```

**Comment by soyuka** [comment]
What format are you using (ie `Accept` header)?

**Comment by GonZOO82** [comment]
I try `application/json` and `application/ld+json`

json -->  {"id":1} .  --> Update is not allowed for this operation.
ld+json --> {"@id":1} --> Update is not allowed for this operation.

json -->  {"@id":1} .  -->  try run SQL nested data INSERT command
ld+json --> {"id":1} --> try run SQL nested data INSERT command

**Comment by soyuka** [comment]
What works with `json-ld`:

POST /books

```
{
  "cover": "/covers/1",
  "title": "foo"
}
```

About `json` I'm investigating.

**Comment by soyuka** [comment]
https://github.com/api-platform/api-platform/issues/249 not supported yet with plain IDs.

**Comment by GonZOO82** [comment]
@soyuka not supported when I POST data, but supported in PUT method?!
```
if (!$normalization && !isset($context['api_allow_update'])) {
    $context['api_allow_update'] = Request::METHOD_PUT === $request->getMethod();
}
``` 
If I PUT data with nested content then it's successful.

Video: https://youtu.be/kEuzdS4z3wk

**Comment by mab05k** [comment]
I was able to get something like this to work by adding "api_allow_update=true" in my deserialization context.

Example
```yaml
AppBundle\Entity\Resource:
    attributes:
        normalization_context:
            groups: [ 'resource.read' ]
        denormalization_context:
            api_allow_update: true
            groups: [ 'resource.write' ]
```

This allowed me to POST in data with full object references when I had embedded objects. It worked for me using JSON, LD+JSON, and HAL+JSON.
