### ISSUE TITLE
[Question] How can I change a route requirement

### ISSUE THREAD

**Issue by greg0ire** [api-platform/core#1401]
I have ids that may contain dots, and right now the path regex for my route is `#^/people/(?P<id>[^/\.]++)(?:\.(?P<_format>[^/]++))?$#s`. How can I change the requirements so that dots are allowed.

I tried adding a `requirements` key, to no avail.

```yaml
        itemOperations:
            get:
                method: 'GET'
                requirements:
                    id: '[^/]++' # allow dots
```
