### ISSUE TITLE
Reuse services configuration

### ISSUE THREAD

**Issue by felicitus** [api-platform/core#141]
I have quite a bunch of entities which share the same configuration. Right now, I would need to copy'n'paste configurations for filters and other calls from one service to another:

```yaml
    resource.partunit:
        parent:    "api.resource"
        arguments: [ "PartKeepr\PartBundle\Entity\PartUnit" ]
        tags:      [ { name: "api.resource" } ]
        calls:
            -       method:    "initFilters"
                    arguments: [ [ "@resource.order_filter" ] ]
            -       method:    "initNormalizationContext"
                    arguments: [ { groups: [ "default" ] } ]
            -       method:    "initDenormalizationContext"
                    arguments:
                        - { groups: [ "default" ] }

    resource.unit:
        parent:    "api.resource"
        arguments: [ "PartKeepr\UnitBundle\Entity\Unit" ]
        tags:      [ { name: "api.resource" } ]
        calls:
            -       method:    "initFilters"
                    arguments: [ [ "@resource.order_filter" ] ]
            -       method:    "initNormalizationContext"
                    arguments: [ { groups: [ "default" ] } ]
            -       method:    "initDenormalizationContext"
                    arguments:
                        - { groups: [ "default" ] }

    resource.siprefix:
        parent:    "api.resource"
        arguments: [ "PartKeepr\SiPrefixBundle\Entity\SiPrefix" ]
        tags:      [ { name: "api.resource" } ]
        calls:
            -       method:    "initFilters"
                    arguments: [ [ "@resource.order_filter" ] ]
            -       method:    "initNormalizationContext"
                    arguments: [ { groups: [ "default" ] } ]
            -       method:    "initDenormalizationContext"
                    arguments:
                        - { groups: [ "default" ] }
```

These are only three entities, the project will have 42 entities in total. Is there any way to re-use the "calls" parameters for each service?

As I'm still a newbie to Symfony2, this question might be trivial.

**Comment by dunglas** [comment]
I think what you are looking for is custom resources: https://github.com/dunglas/DunglasApiBundle/blob/master/Resources/doc/resources.md#using-a-custom-resource-class

**Comment by felicitus** [comment]
As I don't know what I should implement in that resource class, I have no idea if that's what I'm looking for. What's a "Resource"? It seems like a very generic term and I'm having trouble grasping what it's used for :(

**Comment by dunglas** [comment]
When your services mapping your entities with configuration like the following:

```yaml
    resource.product:
        parent:    "api.resource"
        arguments: [ "AppBundle\Entity\Product" ]
        tags:      [ { name: "api.resource" } ]
```

A default `Resource` class is registered as service. Custom `Resource` classes allow to avoid duplicated / too long definitions by populating the resource in raw PHP.
