### ISSUE TITLE
`default_operation_path_resolver` configuration has no effect

### ISSUE THREAD

**Issue by vViktorPL** [api-platform/core#1471]
It seems that at v2.1 overriding the default value of `default_operation_path_resolver` bundle configuration parameter does not make any difference, for instance `api_platform.operation_path_resolver.dash` value still results with route paths like `/my_resource`.

It seems that the service which is passed to the ApiLoader class is hardcoded and hence the bundle configuration parameter is ignored:
https://github.com/api-platform/core/blob/2.1/src/Bridge/Symfony/Bundle/Resources/config/api.xml#L35

The quick a little hacky workaround for this (to force ApiPlatform to use dash strategy in path generation) is to override one of the services:
```yaml
services:
  api_platform.path_segment_name_generator:
    alias: api_platform.path_segment_name_generator.dash
```
