### ISSUE TITLE
How to change Subresource path

### ISSUE THREAD

**Issue by iCodr8** [api-platform/core#1479]
Is it possible to change the path of a subresource?

**Comment by soyuka** [comment]
It should work just as you would overwrite the one of a collection operation. 

For example:

```yaml
# src/AppBundle/Resources/config/api_resources/resources.yml
AppBundle\Entity\Answer:
    collectionOperations:
        api_questions_answer_get_subresource:
            method: 'GET' # nothing more to add if we want to keep the default controller
            path: '/foo/{id}/bar'
```

Before you do this check `debug:router` to get the operation name and the identifier names (they'll have to stay the same).

[docs](https://github.com/api-platform/docs/blob/2.1/core/operations.md#subresources)

**Comment by iCodr8** [comment]
When I am naming my collectionOperation to `api_teams_users_get_subresource` then it will be called `api_teams_api_teams_users_get_subresource_collection` in the router.

**Comment by soyuka** [comment]
Mhh I need to change the docs on this itś s actually only the suffix. Just like you're doing to replace a collection operation (ie `get`, `put`) here it's `property_get_subresource`:

For example to replace the  `api_users_person_get_subresource_collection` path I did:

```yaml
        collectionOperations:
            person_get_subresource:
                method: 'GET'
                path: '/foo/{id}/bar'
```

**Comment by iCodr8** [comment]
The problem is that i don't want to change the `api_users_person_get_subresource_collection`.
I want change the `api_users_person_get_subresource` and that's unfortunaley not possible at all :(

**Comment by soyuka** [comment]
Okaaayy. My bad thought this was fine!

**Comment by iCodr8** [comment]
So, the correct way was your first opinion?

```yaml
# src/AppBundle/Resources/config/api_resources/resources.yml
AppBundle\Entity\Answer:
    collectionOperations:
        api_questions_answer_get_subresource:
            method: 'GET' # nothing more to add if we want to keep the default controller
            path: '/foo/{id}/bar'
```
