### ISSUE TITLE
Errors when fetching resources related to the current user

### ISSUE THREAD

**Issue by takeit** [api-platform/core#1481]
Hi, 

I want to fetch books related to the current user according to this documentation: https://api-platform.com/docs/core/security

Unfortunately, I  have an issue. 

I have a Book entity where I have `$user` property and a getter. The resource file looks like that ( I use yaml):

```yaml
App\Entity\Book:
    attributes:
        normalization_context:
            groups: ['read']
        denormalization_context:
            groups: ['write']
    collectionOperations:
        get:
            method: 'GET'
            access_control: "is_granted('ROLE_USER') and object.getUser() == user"
```

When I want to fetch books I get an error:
```
Unable to call method "getUser" of object "ApiPlatform\Core\Bridge\Doctrine\Orm\Paginator"
```

When I use `access_control: "is_granted('ROLE_USER')"` it works fine tho, so the file is being read properly.

Any idea what I did wrong and why this Paginator class is being called?

Thanks!

**Comment by soyuka** [comment]
yes because `object` is a collection of items (ie an array/Paginator). You may want to do this on an item or you'd have to loop on the collection.

**Comment by takeit** [comment]
thanks @soyuka for your reply. 

I tried: 

```
    itemOperations:
        get:
            method: 'GET'
            access_control: "is_granted('ROLE_USER') and object.getUser() == user"
```
it doesn't throw an exception now, but all books are returned, even those related to other user.
It looks like `itemOperations` is not called at all. My user has role `ROLE_USER` when I change `is_granted('ROLE_USER')` to `is_granted('ROLE_ADMIN')` it still shows all books.

Any idea?
