### ISSUE TITLE
Content-Type */* generates error when format restriction configured

### ISSUE THREAD

**Issue by Nek-** [api-platform/core#1532]
When you use the following configuration:
```
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
            # The fact I need to have HTML just to get the documentation is another story...
```

And you query api platform with the following header:

```
Content-Type: */*; charset=utf-8
```

_This is the default one in some tools like PhpStorm for example._

## Observation:
Then apiplatform fails with error on "wrong format requested" instead of taking the first format specified in configuration.

## Expected behavior
As documented, it should take the first format (here jsonld) as format for the current query.
