### ISSUE TITLE
Why is validation process executed on `kernel.view` instead of `kernel.request` ?

### ISSUE THREAD

**Issue by jdeniau** [api-platform/core#1538]
I am upgrading a pretty "custom" API from v1 to v2, and thus I have a lot of "symfony-style" controllers.

I ask myself why do validation process appear after the "controller" (or action) ?

As I see it, I think I will need to "duplicate" the validation logic to appear before the controller code appends (at least the configuration), because the controller contain the core logic (saving stuff to persistance layer, etc.)

Am I missing a reason for that ?

Thank you

**Comment by jdeniau** [comment]
Well a good night sleep helps so it's logic that validation appends just before persist too, in case you did alter the object properties in the controller. But it can be interesseting to validate input data, isn't it ?

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/554 ? I think we discussed this in another issue can't find where though :|

**Comment by jdeniau** [comment]
Regarding this question, and if I understand api-platform right, I think it's maybe weird, but the controller / action place is really "custom-logic", and thus overriding the controller / action may be a bad practice. In fact it is said in the documentation to prefer event system against action / controller.

In fact in my case, I "simply" need to put my logic "somewhere between the validation and the persistance", but as a lazy developper, I just want to use the easy way, wich is the controller (and the controller allow to add anotations for routing, etc., wich is quite usefull).

**Comment by soyuka** [comment]
> Regarding this question, and if I understand api-platform right, I think it's maybe weird, but the controller / action place is really "custom-logic", and thus overriding the controller / action may be a bad practice. In fact it is said in the documentation to prefer event system against action / controller.

This is correct. 

> In fact in my case, I "simply" need to put my logic "somewhere between the validation and the persistance", but as a lazy developper, I just want to use the easy way, wich is the controller (and the controller allow to add anotations for routing, etc., wich is quite usefull).

In this case I usually just uses the DataProvider:

```yaml
#- routing.yml

api_foos_by_domain:
    path: /api/foos/by_domain
    defaults: {
        _api_resource_class: AppBundle\Entity\Foo,
        _api_collection_operation_name: api_foos_by_domain,
        _controller: ApiPlatform\Core\Action\PlaceholderAction }
```

```yaml
#- api_resources.yml

resources:
    AppBundle\Entity\Foo:
        collectionOperations:
            get:
                method: 'GET'
            post:
                method: 'POST'
            domain:
                method: 'GET'
```

```php
<?php
class FooCollectionDataProvider implements CollectionDataProviderInterface, RestrictedDataProviderInterface {
    public function supports(string $resourceClass, string $operationName = null): bool
    {
        return $resourceClass === Foo::class && $operationName === 'api_foos_by_domain';
    }

   //...
}
```

```yaml
services:
    _defaults:
        autowire: true
        public: false

    AppBundle\DataProvider\FooCollectionDataProvider:
        tags:
            - { name: 'api_platform.collection_data_provider', priority: 90}
```

Example with the EventListener (a lazy way to add data to a given operation):

```yaml
services:
    FooListener:
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 20}
```

```php
<?php
use Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent;

final class FooListener
{
    public function __construct(InjectStuffHere $foo)
    {}

    public function onKernelView(GetResponseForControllerResultEvent $event)
    {
        $controllerResult = $event->getControllerResult();

        if (!is_array($controllerResult) || !isset($controllerResult[0])) {
            return;
        }

        if (false === $controllerResult[0] instanceof Component) {
            return;
        }

       // return $controllerResult altered
    }
}
```
