### ISSUE TITLE
Filter class name is gettin modified when it contains the word "List"

### ISSUE THREAD

**Issue by blaues0cke** [api-platform/core#157]
I worte a custom filter and I use it like this:

    resource.id_filter:
        class:    "My\AppBundle\Api\Filter\TestFilter"
        arguments:
            - @doctrine
            - @api.iri_converter
            - @property_accessor

To test, I deleted the class. Then symfony reports correctly:

    hydra:description: "Attempted to load class "TestFilter" from namespace "My\AppBundle\Api\Filter". Did you forget a "use" statement for "Doctrine\Bundle\DoctrineBundle\Tests\DependencyInjection\TestFilter"?"

So everything is fine, `TestFilter` is recognized correctly.

When I add the Word `List` in the filter name, like this:

    resource.id_filter:
        class:    "My\AppBundle\Api\Filter\ListTestFilter"
        arguments:
            - @doctrine
            - @api.iri_converter
            - @property_accessor

The error is getting weird (and contains some special characters?):

    hydra:description: "Attempted to load class "Filter istTestFilter" from namespace "My\AppBundle\Api". Did you forget a "use" statement for another namespace?",

Here is the short link to the documentation: https://github.com/dunglas/DunglasApiBundle/blob/master/Resources/doc/filters.md

**Comment by dunglas** [comment]
Weird! Can you try with the following definition?

```yaml
resource.id_filter:
    class:    "My\\AppBundle\\Api\\Filter\\ListTestFilter"
    arguments:
        - @doctrine
        - @api.iri_converter
        - @property_accessor
```

**Comment by blaues0cke** [comment]
Yeah, this fixed it. Should we update the documentation for this?

    resource.id_filter:
        class:    "My\\AppBundle\\Api\\Filter\\ListTestFilter"
        arguments:
            - @doctrine
            - @api.iri_converter
            - @property_accessor


causes a correct

    hydra:description: "Attempted to load class "ListTestFilter" from namespace "My\AppBundle\Api\Filter". Did you forget a "use" statement for another namespace?"

**Comment by dunglas** [comment]
Yes, it would be could to have a note about that.

**Comment by teohhanhui** [comment]
I don't think this should be a problem at all if you just avoid quoting the FQCN, i.e.

```yaml
resource.id_filter:
    class:    My\AppBundle\Api\Filter\ListTestFilter
    arguments:
        - @doctrine
        - @api.iri_converter
        - @property_accessor
```
