### ISSUE TITLE
How to use validation groups based on fields given in PUT request

### ISSUE THREAD

**Issue by Zayon** [api-platform/core#1573]
Hi,

Imagine I have an Entity like this : 
```php
/**
 * @ApiResource(attributes={"validation_groups"=GroupsGenerator::class})
 */
class Book
{
    /**
     * @Assert\NotBlank(groups={"a"})
     */
    private $name;

    /**
     * @Assert\NotNull(groups={"b"})
     */
    private $author;

    // ...
}
```

Now I have a `Book` that has null `author` and `name`, I want to update the `name` field only:

```json 
// HTTP PUT on "book/1" :
{
    "name": "bookName"
}
```

In order to make it work I need to make the `__invoke` method of `GroupsGenerator` return `['a']`. How
to know in this method (with only my entity `Book` passed as first argument) that I'm only updating the `name` field and thus I don't want to validate the `author` field ?

Thanks.

**Comment by Zayon** [comment]
It seems this is impossible, we have to use a dedicated operation like this

```php
/**
 * @ApiResource(itemOperations={
 *     "put"={"method"="PUT"},
 *     "a"={"method"="PUT", "path"="book/{id}/update/a", "validation_groups"={"a"}}
 *     "b"={"method"="PUT", "path"="book/{id}/update/b", "validation_groups"={"b"}}
 * })
 */
class Book
{
    /**
     * @Assert\NotBlank(groups={"a"})
     */
    private $name;

    /**
     * @Assert\NotNull(groups={"b"})
     */
    private $author;

    // ...
}
```
Or in yml:
```yml
resources:
    AppBundle\Entity\Book:
        attributes:
            validation_groups: ['a', 'b]
        itemOperations:
            put:
                method: 'PUT'
            a:
                method: 'PUT'
                path: '/book/{id}/update/a'
                validation_groups: ['a']
            b:
                method: 'PUT'
                path: '/book/{id}/update/b'
                validation_groups: ['b']
```
