### ISSUE TITLE
Connect to a database via SSH

### ISSUE THREAD

**Issue by GreyBlade** [api-platform/core#1623]
Hey I am trying to connect my API to a database, but the only way to connect to it is via SSH, how do i have to config my parameters.yml to do the connection?
This is my file.

```
parameters:
    database_host: 127.0.0.1
    database_port: 3306
    database_name: aldroges8
    database_user: jacu
    database_password: ******
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
    cors_allow_origin: 'http://localhost'
    varnish_urls:
        - 'http://varnish'

```
In database_host i have tried with the SSH IP and MySql IP and using my passwords, SSH pass and MySql pass (the same way i connected to the database using MySql workbench)
