### ISSUE TITLE
Problems with bundles that have Entity folder

### ISSUE THREAD

**Issue by giovannialbero1992** [api-platform/core#1655]
I've noticed that api-platform scans all bundles into vendor directory, this behaviour creates problem when i use api-platform and vich-uploader without ORM installed in my project  (for example).
Is there a config to avoid this behaviour? I'd like to evaluate only folders declared into `api_platform.yml`
```
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Document'] 
```

**Comment by jewome62** [comment]
You should override `api_platform.resource_class_directories`
I dont know if you can just add into Yaml config or if you must override by compiler

**Comment by giovannialbero1992** [comment]
i must override entire `api_platform.resource_class_directories` in compiler pass . It would be nice have a config that disable this behaviour. is it welcome a PR on this?

**Comment by jewome62** [comment]
Everything is welcome in PR if the request makes sense

**Comment by soyuka** [comment]
So I came across the same problem. 

An alternative solution is to patch `configureContainer` of your Kernel to add the missing paths. Indeed, we currently search for `$bundle['path']/Entity`.

I'll add a patch to help configure `resource_class_directories` it'll give more power to the developer IMO. For example:

```
api_platform:
    mapping:
        paths:
          - '%kernel.project_dir%/src/Foo/api_resources.yaml'
    resource_class_directories:
        - '%kernel.project_dir%/src/Foo/Entity'
```
