### ISSUE TITLE
Symfony 4 & ressources defined in Yaml

### ISSUE THREAD

**Issue by alex-ception** [api-platform/core#1668]
Hi,

I'm trying tu use api-platform with SF4.
The fact is I have to use yml file to define my resources, I tried to put that file in multiple directory, but it doesn't seems to be loaded.

Any suggestion ?
Thanks :)

**Comment by sroze** [comment]
Where did you put your files? Can you give us an example of what isn't working exactly? Also, check your `src/Kernel.php` file to see which configuration files are loaded 😉

**Comment by dwolosowicz** [comment]
I had the same issue moments ago, actually.

Seems like I've had the api-platform configured to into Entities only to find the mappings.
Try something like this and put any yaml files with resources configurations into that path. In my case it picked it up:
```yaml
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/config/resources/']
```
