### ISSUE TITLE
api_resource/resource.yaml - Symfony 4 Location

### ISSUE THREAD

**Issue by kswzr** [api-platform/core#1671]
Hello,
what is the correct location for the resource yaml configuration in the symfony 4 flex version?

**Comment by soyuka** [comment]
The one you want :).

IMO, standard version would be like:

```
src/Kernel.php
src/api_resources.yaml
src/Entity/Product.php
```

With `config/packages/api_platform.yaml`:

```yaml
api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/src/api_resources.yaml`
  resource_class_directories:
    paths:
      - '%kernel.project_dir%/src/Entity`
```

I have the following:

```
src/Kernel.php
src/Product/api_resources.yaml
src/Product/Entity/Product.php
```

With `config/packages/api_platform.yaml`:

```yaml
api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/src/Product/api_resources.yaml` 
  resource_class_directories:
    paths:
      - '%kernel.project_dir%/src/Product/Entity` # reads annotations from those files 
```

I'll maybe add glob support to the paths
