### ISSUE TITLE
Can't Implement maxDepth in API-Platform using YAML

### ISSUE THREAD

**Issue by fawazIbrahim** [api-platform/core#1717]
I have an entity with the following

```
/**
 * @ORM\Table(name="category")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CategoryRepository")
 */
class Category
{
     ...
     /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Category", mappedBy="parent")
     */
    private $children;
    ...
}
```
and i've defined the "children" as an API-Subresource using YAML:

```
AppBundle\Entity\Category:
  properties:
    children:
      subresource:
        resourceClass: 'App\Entity\Category'
```

How to set a maxDepth for the `$children` without using annotation like

```
/**
* @ApiSubresource(maxDepth=1)
*/
```
