### ISSUE TITLE
symfony 3.4 + API platform - Service in action not autowired

### ISSUE THREAD

**Issue by cataragak90** [api-platform/core#1730]
I got an issue when I try to create my custom operation like it's described [here][1].
I created a new controller with some actions, but when I try to inject a service in the controller's actions/constructor I have an error:

    Too few arguments to function App\Controller\Api\UserController::__construct()

I use:

    api-platform/core : 2.2.1    
    Symfony 3.4.4

  [1]: https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers

Thank you

**Comment by k911** [comment]
If you're using default symfony configuration and different folder for actions than `src/Controller` (which is obvious BTW), you have to add tag `controller.service_arguments` for them.

Something like this in `services.yaml` should be enough:
```yaml
    # actions are imported separately to make sure they
    # have the tag that allows to type-hint services
    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']
```
