### ISSUE TITLE
filters with yaml

### ISSUE THREAD

**Issue by ahmed-hachena** [api-platform/core#1755]
I think filters with yaml are not supported, only with annotation like this from doc
`@ApiFilter(BooleanFilter::class, properties={"isAvailableGenericallyInMyCountry"})`

it would be cool to have yaml support for filters, like someone can configure everything in yaml not a part in yaml and another in annotation.

**Comment by antograssiot** [comment]
@ahmed-hachena did you tried 
```yaml
resources:
  App\Entity\Foo:
        itemOperations ...
        attributes:
            filters: ['app.my_filter']
```
 and
 ```yaml
services: 
    app.my_filter: 
        parent: 'api_platform.doctrine.orm.search_filter' 
        arguments: [ { bar: ~  } ] 
        tags:      [ 'api_platform.filter' ] 
```
it should already work I think
