### ISSUE TITLE
Expose a configuration in order to generate resources

### ISSUE THREAD

**Issue by ogizanagi** [api-platform/core#185]
## Overview

Echoing https://github.com/dunglas/DunglasApiBundle/pull/174#issuecomment-122347068, we indeed started something similar within one of our project, by exposing a configuration used by a compiler pass in order to generate resources services for us.
I expected doing of this a bundle or ask for integration within the bundle if we achieve to make something good enough.

Here is what the configuration reference currently looks like:
```yaml
app:
    dunglas_api:
        resources_templates:

            # Prototype
            name:

                # Basic generated operations to expose among these values: "GET", "POST", "PUT", "DELETE".
                methods:              []
                filters:              []
                validation_groups:    []
                normalization_context:
                    groups:               ~
                denormalization_context:
                    groups:               ~

        resources:

            # Prototype
            resource:
                template:             default # false to start from a fresh empty template

                # Basic generated operations to expose among these values: "GET", "POST", "PUT", "DELETE".
                methods:              []
                filters:              []
                validation_groups:    []
                item_operations:

                    # Prototype
                    operation:

                        # An existent operation service id prefixed by "@" if you don't want to generate it.
                        # Should not be set directly, but as the operation key instead.
                        service_id:           ~

                        # The route path to use for the operation to generate.
                        # Should not be set directly, but as the operation key instead.
                        path:                 ~ # Required
                        controller:           ~ # Required
                        methods:              []
                        context:              ~
                collection_operations:

                    # Prototype
                    operation:

                        # An existent operation service id prefixed by "@" if you don't want to generate it.
                        # Should not be set directly, but as the operation key instead.
                        service_id:           ~

                        # The route path to use for the operation to generate.
                        # Should not be set directly, but as the operation key instead.
                        path:                 ~ # Required
                        controller:           ~ # Required
                        methods:              []
                        context:              ~
                normalization_context:
                    groups:               []
                denormalization_context:
                    groups:               []
```

## Working example:

```yaml
    dunglas_api:
       resources_templates:
            # All resources extending this template will have this base configuration:
            custom_template:
                filters: []
                validation_groups: [Default]
                methods: [GET, POST]
                normalization_context:
                    groups: [group1, group 3]
                denormalization_context:
                    groups: [group2]
        resources:
            - AppBundle\Entity\Dummy:
                template: custom_template
                filters: [@my_date_filter, @my_serahc_filter] # filters services ids
                validation_groups: [Dummy]
                methods: [DELETE]
                item_operations:
                    # The following service reference will be used as an operation:
                    - @api.operation.dummy.custom_operation_reference
                    # The following configuration will generate an operation:
                    - /dummy/{id}/custom: 
                        controller: AppBundle:Dummy:custom # The controller and action to use.
                        methods: [GET, HEAD] # The http methods for which this action is available.
                        context:
                             "@type":       "hydra:Operation"
                             "hydra:title": "A custom operation on a Dummy entity"
                             "returns":     "xmls:string"
```

## Problematic

My issue here is about the `filters` option.
Currently, it only take an array of filters services ids as values.
But, I'd like to go further, in order to avoid mass manual filter services declaration:

```yaml
resources:
   AppBundle\DummyEntity:
        filters: 
            - api.custom.search_filter
            - api.doctrine.orm.date_filter: { dateProperty: ~ }
```

An `api.resource.dummy_entity` resource will be generated with two filters:
- My `api.custom.search_filter` service, which is not abstract but a concrete service, child of `api.doctrine.orm.search_filter`. Without specifying any configuration (it has already be done within the service declaration)
- A new generated `api.doctrine.orm.date_filter.dummy_entity` filter, which is automatically created from `api.doctrine.orm.date_filter` abstract service, and is initialized with `{ dateProperty: ~ }` as the `DateFilter::properties` instance property.

**But:**

1. We cannot presume what is the position of the `$properties` argument in the Filter constructor. Using DefinitionDecorator to create the child service from the parent, I don't know how to set the proper argument. **We would eventually need a method setProperties to be called**.  

2. Might some filters need more than properties for their concrete service declaration ?

3. Some concrete filters services might be shared by multiple resources (a search filter for any fields for instance). So creating a new service for each resource is useless and will pollute the container.
Instead, this filter will be declared as we already do, and the user will reference the id in the `filter` option of each needed resources/templates.
**Is it a workable workflow to only generate services when the given service id in the `filters` option are abstract services ?** 

What do you think ?

**Comment by dunglas** [comment]
We will definitely merge such features in the bundle! What do you think about my config proposal (#174)?
About filters, and for all reasons you mentioned,  I think it's better to keep them as services. Using filters is common but advanced and in many projects I'd to inject all sorts of custom services in filters. I think it's easier and better design to keep filter configuration as referencing existing services.

Another question: what's the purpose of the `resources_templates` key?

**Comment by ogizanagi** [comment]
About #174 , yes, of course, I'm almost basing myself on it, but we'll don't restrict to this for our needs, and the `filters` configuration for instance might be useful.
According to the avancement, I might extract this into a proper PR for this bundle, respecting your config proposal.

About filters, the main issue with services is the verbosity of the declaration and mixing the config style with DIC stuff. IMO it's better to have everything that concerns a resource under the same configuration key.
Also, the config style will generate services, and thus their ids. Which in case of a custom operation for instance is needed. We can automate the operation creation too, in order to keep the user from dealing with the generated id himself:

```yaml
app:
    dunglas_api:
        resources:
            AppBundle\Entity\Product:
                methods:              [GET, POST]
                item_operations:
                    - api.operation.my_custom_operaton_service_id # A custom operation service reference
                    - "/products/{id}/custom": # A generated operation service
                         route_name: ~ # Optional, generated
                         controller: AppBundle:Custom:custom # Mandatory
                         methods: [Get, HEAD] # Mandatory
                         context:  # Optional
```

---

> Another question: what's the purpose of the resources_templates key ?

Any resource defining the template option will automatically have the template configured options + their own configuration.

For instance, the default template is (but can be overridden):
```yaml
default:
    methods: [GET, POST, PUT, DELETE]
    filters: []
    normalization_context:
        groups: [serialization]
    denormalization_context:
        groups: [deserialization]
```

I also create this template:
```yaml
custom_template:
    methods: [GET, POST]
    filters: []
    normalization_context:
        groups: [group1, group 3]
    denormalization_context:
        groups: [group2]
```

Considering the following resources declaration:
```yaml
resources:
    - AppBundle\Entity\Product: 
        template: custom_template
        methods: [DELETE] # will be appended to the template methods
        normalization_context: { groups: [product] } # will be appended to the template groups
    - AppBundle\Entity\User: 
        template: ~ # use default template
        normalization_context: { groups: [user] } # will be appended to the template groups
```

The resulting configuration array will look like:
```php
["AppBundle\Entity\Product" => [
    "methods" => ["GET", "POST", "DELETE"],
    "normalizationContext" => [
        "groups" => ["group1", "group3", "product"],
    ],
    "denormalizationContext" => [
        "groups" => ["group2"]
    ],
], "AppBundle\Entity\User" => [
    "methods" => ["GET", "POST", "PUT", "DELETE"],
    "normalizationContext" => [
        "groups" => ["serialization", "user"],
    ],
    "denormalizationContext" => [
        "groups" => ["deserialization"]
    ],
]]
```
