### ISSUE TITLE
Add a `documentation_formats` that differs from `formats`

### ISSUE THREAD

**Issue by jdeniau** [api-platform/core#1854]
If you de-activate the `json` format from the configuration, you can not use like [ReDoc](https://rebilly.github.io/ReDoc/). You can not use the integrated swagger if you disable `html` format.

Personally, I disable everything except `json-ld` (less options means less bugs ;) ).

Furthermore, I don't think that enabling html format is really pertinent for an API, but it does for the documentation.

Do you think it's a good idea to split `formats` from the `documentation_formats`, this way, we could do something like:

```yaml
api_platform:
    formats: 
        jsonld: ['application/ld+json']
    documentation_formats: 
        html: ['text/html']
        json: ['application/json']
```

As usual, I will open a PR if you agree with this.
