### ISSUE TITLE
Varnish required?

### ISSUE THREAD

**Issue by jayesbe** [api-platform/core#1881]
Currently using the master branch

```
"api-platform/core": "dev-master"
```

I am getting the following exception

```
GuzzleHttp\Exception\ServerException:
Server error: `BAN http://localhost` resulted in a `501 Not Implemented` response:




Not (truncated...)


  at vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
  at GuzzleHttp\Exception\RequestException::create(object(Request), object(Response))
     (vendor/guzzlehttp/guzzle/src/Middleware.php:66)
  at GuzzleHttp\Middleware::GuzzleHttp\{closure}(object(Response))
     (vendor/guzzlehttp/promises/src/Promise.php:203)
  at GuzzleHttp\Promise\Promise::callHandler(1, object(Response), array(object(Promise), object(Closure), null))
     (vendor/guzzlehttp/promises/src/Promise.php:156)
  at GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
     (vendor/guzzlehttp/promises/src/TaskQueue.php:47)
  at GuzzleHttp\Promise\TaskQueue->run(true)
     (vendor/guzzlehttp/promises/src/Promise.php:246)
  at GuzzleHttp\Promise\Promise->invokeWaitFn()
```

I do not have Varnish configured. Is it required?

current http_cache config

```
    http_cache:
        # Automatically generate etags for API responses.
        etag: false

        # Default value for the response max age.
        # max_age: 60
        max_age: 0
        
        # Default value for the response shared (proxy) max age.
        shared_max_age: 3600

        # Default values of the "Vary" HTTP header.
        # vary: ['Accept']
        vary: ['Content-Type', 'Authorization']
        
        # To make all responses public by default.
        # public: ~
        public: true

        invalidation:
            # To enable the tags-based cache invalidation system.
            enabled: false

            # URLs of the Varnish servers to purge using cache tags when a resource is updated.
            varnish_urls: []

            request_options: 
                verify_ssl: '%kernel.debug%'
                
```

The exception occurs after

DEBUG19:03:39 | doctrine | "START TRANSACTION"
-- | -- | --
DEBUG19:03:39 | doctrine | UPDATE user SET last_login = ?, updated_at = ? WHERE id = ?
DEBUG19:03:39 | doctrine | "COMMIT"
CRITICAL19:03:39 | request | Uncaught PHP Exception GuzzleHttp\Exception\ServerException: "Server error: `BAN http://localhost` resulted in a `501 Not Implemented` response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>501 Not Implemented</title> </head><body> <h1>Not (truncated...) " at /api/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php line 113
