### ISSUE TITLE
A custom GET item operation will change the IRI

### ISSUE THREAD

**Issue by ogizanagi** [api-platform/core#189]
A custom GET item operation registered before the basic one will modify the IRI.

I encountered this issue while dealing with the exposition of a configuration to generate operations:

```yaml
    dunglas_api:
        resources:
            - AppBundle\Entity\Dummy:
                methods: [GET, POST, PUT, DELETE]
                item_operations:
                    # The following configuration will generate an operation:
                    - /dummy/{id}/custom: 
                        controller: AppBundle:Dummy:custom # The controller and action to use.
                        methods: [GET, HEAD] # The http methods for which this action is available.
                        context:
                             "@type":       "hydra:Operation"
                             "hydra:title": "A custom operation on a Dummy entity"
                             "returns":     "xmls:string"
```

In my compiler pass, item operations from the `item_operations` config property are generated and added first to the Resource. Then, from the `methods` config property, I generate the basic CRUD operations.

In this case, the IRI will be: `/api/dummy/1/custom` instead of `/api/dummy/1`.  
It could be tricky when trying to define custom operations for things like [nested resources](https://github.com/dunglas/DunglasApiBundle/issues/186) for instance.

So [here](https://github.com/dunglas/DunglasApiBundle/blame/master/Resources/doc/operations.md#L109), the operations order is important.

It is certainly an edge case, and I'm not sure anything straightforward can be done about it, but might be mentioned somewhere in the doc ?
