### ISSUE TITLE
How to get objects collection instead of IRI links by default?

### ISSUE THREAD

**Issue by nofirg** [api-platform/core#1896]
I have 2 related(one2many) entities witch I get its by api. All work well, besides nested collection in response.
I got 
```
[
    {
        "id": 1,
        "login": "login",
        "accounts": [
            "/rest/accounts/16002090",
            "/rest/accounts/16044758"
        ]
    }
]
```
instead of
```
[
    {
        "id": 1,
        "login": "login",
        "accounts": [
           {"id": 16002090, ...},
           {"id": 16044758, ...}
        ]
    }
]
```

Please give advice, how to get expected result with full nested collection of accounts.

**User**
```
/**
 * @ORM\Entity()
 * @ORM\Table(name="public.user")
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Presentation\Entity\Account", mappedBy="user")
     */
    private $accounts;

    public function __construct()
    {
        $this->accounts = new ArrayCollection();
    }
    
    public function addAccount(Account $account)
    {
        $this->accounts[] = $account;
    }

    public function getAccounts(): Collection
    {
        return $this->accounts;
    }
}
```
**Account**
```
/**
 * @ORM\Entity()
 * @ORM\Table(name="public.account")
 */
class Account
{
    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="integer")
     */
    private $id;

      /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="accounts", fetch="EAGER")
     */
    public $user;

    public function getUser() : User
    {
        return $this->user;
    }

    public function setUser(User $user): void
    {
        $this->user = $user;
    }
}
```

**api_resources.yaml**
```
resources:
    App\Entity\User:
        graphql:
            query:
                filters:
                    - 'user.search_filter'
                    - 'user.registered_filter'
                    - 'user.order_filter'
        collectionOperations:
            get:
                filters:
                    - 'user.search_filter'
                    - 'user.registered_filter'
                    - 'user.order_filter'
        itemOperations:
            get: ~

    App\Entity\Account:
        graphql:
            query:
                filters: ~
        collectionOperations:
            get:
                filters: ~
        itemOperations:
            get: ~
```

**Comment by soyuka** [comment]
serialization groups?

**Comment by nofirg** [comment]
Now it's works, tnx!

new **api_resources.yaml**
```
resources:
    App\Presentation\Entity\User:
        graphql:
            query:
                filters:
                    - 'user.search_filter'
                    - 'user.registered_filter'
                    - 'user.order_filter'
        collectionOperations:
            get:
                filters:
                    - 'user.search_filter'
                    - 'user.registered_filter'
                    - 'user.order_filter'
        itemOperations:
            get: ~
        attributes:
          normalization_context:
              groups: ['read']
        properties:
           accounts':
               subresource: {collection: true, resourceClass: 'App\Presentation\Entity\Account', maxDepth: 1}

    App\Presentation\Entity\Account:
        graphql:
            query:
                filters: ~
        collectionOperations:
            get:
                filters: ~
        itemOperations:
            get: ~
        attributes:
          normalization_context:
              groups: ['read']
        properties:
           user':
               subresource: {collection: false, resourceClass: 'App\Entity\User', maxDepth: 1}
```

new **User**
```
/**
 * @ORM\Entity()
 * @ORM\Table(name="public.user")
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Account", mappedBy="user")
     * @Groups({"read"})
     */
    private $accounts;

    public function __construct()
    {
        $this->accounts = new ArrayCollection();
    }
    
    public function addAccount(Account $account)
    {
        $this->accounts[] = $account;
    }

    public function getAccounts(): Collection
    {
        return $this->accounts;
    }
}
```
new **Account**
```
/**
 * @ORM\Entity()
 * @ORM\Table(name="public.account")
 */
class Account
{
    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="integer")
     */
    private $id;

      /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="accounts")
     * @Groups({"read"})
     */
    public $user;

    public function getUser() : User
    {
        return $this->user;
    }

    public function setUser(User $user): void
    {
        $this->user = $user;
    }
}
```
