### ISSUE TITLE
CustomCollectionDataProvider

### ISSUE THREAD

**Issue by mysiar** [api-platform/core#1965]
I need to add pagination and filters to my custom data provider using core 2.1.6.
This is my provider service definition.
```
services:
    AppBundle\DataProvider\Model\DrugUnifiedCollection:
        class: 'AppBundle\DataProvider\Model\DrugUnifiedCollection'
        calls:
            - method: 'addExtensions'
              arguments:
                - !tagged @api_platform.doctrine.orm.query_extension.pagination
                - !tagged @api_platform.doctrine.orm.query_extension.filter
        tags:
            - { name: 'api_platform.collection_data_provider' }

```
```
public function addExtensions(array $extensions): void
{
        $this->extensions = $extensions;
}
```

Could anybody tell me why I do not have extensions injected ?

**Comment by soyuka** [comment]
tagged should be the tag not the service name `api_platform.doctrine.orm.query_extension.collection` you can also inject services but omit the `!tagged` flag.

**Comment by mysiar** [comment]
@soyuka I have core 2.1.6 and have only these extensions
```
ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\EagerLoadingExtension
ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\FilterEagerLoadingExtension
ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\FilterExtension
ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\OrderExtension
ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\PaginationExtension 
```

my service
```
services:
    AppBundle\DataProvider\Model\DrugUnifiedCollection:
        class: 'AppBundle\DataProvider\Model\DrugUnifiedCollection'
        calls:
            - method: 'addExtension'
              arguments:
                - '@api_platform.doctrine.orm.query_extension.pagination'
        tags:
            - { name: 'api_platform.collection_data_provider' }
```

```
 /** @var array */
    private $extensions;

public function addExtension($extension): void
    {
        $this->extensions[] = $extension;
    }
```

still do not have anything in $extensions
