### ISSUE TITLE
Can not use GroupSequence

### ISSUE THREAD

**Issue by emilien-puget** [api-platform/core#2009]
Hello,

I use php7.2, symfony 4.1 and api-platform/core v2.2.7
I encountered an issue when using a GroupSequenceGenerator

```YAML
App\Entity\Checkout\Cart:
    collectionOperations:
        post:
            method: 'POST'
            validation_groups: App\Service\Checkout\Validator\CartGroupsGenerator
```
```PHP
namespace App\Service\Checkout\Validator;

use App\Entity\Checkout\Cart;
use Symfony\Component\Validator\Constraints\GroupSequence;

class CartGroupsGenerator
{
    /**
     * @param Cart $product
     *
     * @return GroupSequence
     */
    public function __invoke(Cart $product): GroupSequence
    {
        return new GroupSequence(['first', 'first_write', 'Cart']);
    }
}
```

When submitting a request, I get this error:

```
request.CRITICAL: Uncaught PHP Exception PHPUnit\Framework\Error\Warning: "Illegal offset type" at /var/www/symfony/vendor/symfony/validator/Context/ExecutionContext.php line 309 {"exception":"[object] (PHPUnit\\Framework\\Error\\Warning(code: 2): Illegal offset type at /var/www/symfony/vendor/symfony/validator/Context/ExecutionContext.php:309)"} []
```

It seems the problem is triggered by this line 
https://github.com/api-platform/core/blob/v2.2.7/src/Bridge/Symfony/Validator/Validator.php#L55

With this line removed, the error vanished.

The groupSequence is casted as an array and the symfony validator seems to not recognize a groupSequence as an array
