### ISSUE TITLE
Add Config Filters in yaml

### ISSUE THREAD

**Issue by stood** [api-platform/core#2037]
Hi,
I would like to add the filters in the Pomm Bridge. https://github.com/pomm-project/pomm-api-platform/pull/2
But for you when you use the project with Doctrine you use the annotations.
It's possible to add the config of the filters in yaml ?

For me the best place for this is: https://github.com/stood/pomm-api-platform/blob/44916cc2cd20c3e9a4f7f72f3ae76cc2149d9bd4/test/src/Resources/config/api_resources/resources.yml#L6

What do you think of this ?

**Comment by antograssiot** [comment]
It is already/still possible to use yaml even with Doctrine: https://api-platform.com/docs/core/filters/#basic-knowledge

Declare for example a ` offer.date_filter` service and use it in the filters attribute:

```
    collectionOperations:
        get:
            filters: ['offer.date_filter']
```

**Comment by stood** [comment]
I'm sorry, I doesn't want just to add a filter, I want specify search filter (partial...)

```
resources:
    AppBundle\Entity\Config:
        collectionOperations:
            get:
                filters:
                    value: partial
```
