### ISSUE TITLE
Custom order query parameter name in api_platform.yaml being ignored

### ISSUE THREAD

**Issue by rogamoore** [api-platform/core#2080]
## Expected behaviour:
After changing the configuration to
```
# api/config/packages/api_platform.yaml
api_platform:
    collection:
        order_parameter_name: '_order' # the URL query parameter to use is now "_order"
```
and adding an OrderFilter to my ApiResource
```
...
use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\OrderFilter;

/**
 * @ApiResource()
 * @ApiFilter(OrderFilter::class, properties={"id", "postCode"})
 * ...
 */
class Town
```
according to the documentation https://api-platform.com/docs/core/filters#using-a-custom-order-query-parameter-name I expected the query parameter for ordering to be named '_order'.

## Actual behaviour:
The setting is ignored and the query parameter continues to be named 'order' (without underscore).

## Hints
- Swagger UI shows 'order' for sorting
- Cache cleared :)
- Container parameter is set correctly:
```
www-data@fe34c1e3a189:~/symfony$ bin/console debug:container --parameter=api_platform.collection.order_parameter_name
 ---------------------------------------------- --------
  Parameter                                      Value
 ---------------------------------------------- --------
  api_platform.collection.order_parameter_name   _order
 ---------------------------------------------- --------
```
- When I dump `$orderParameterName` in [ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\OrderFilter](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Filter/OrderFilter.php) it is always 'order', even if I remove the default value from the constructor
- When changing the annotation to
```
 * @ApiFilter(OrderFilter::class, properties={"id", "postCode"}, arguments={"orderParameterName"="_order"})
``` 
it works - but this has to be repeated for every resource. My expectation was that I can set this globally using the configuration file.

Any ideas?

**Comment by soyuka** [comment]
My guess is that the `AnnotationFilterPass` doesn't configure the symfony Definition to take the updated parameters into consideration... 

https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPass.php#L62 

Not sure how to fix this though.

**Comment by rogamoore** [comment]
That's also my guess. :)
Unfortunately I don't understand the internals enough to propose a fix - but a temporary fix would be removing this from the docs so it saves someone some headaches while trying to debug this :)

**Comment by antograssiot** [comment]
@soyuka wouldn't it be possible to use ChildDefinition instead of Defition. We could try to guess the APIP parent service name based on the filter classname...
Another solution (for SF4.1+ I think) is to add a ParameterBag in the filter constructor args, so config and parameter could be autowired but I'm not sure on how to handle this properly in a BC way

**Comment by soyuka** [comment]
Is it possible that the compiler pass needs to be at a lower priority?

**Comment by rogamoore** [comment]
I tried this:

```
services:
    ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\OrderFilter:
        arguments:
            $orderParameterName: '_order'
```
but the Parameter is still "order"

**Comment by Maels1991** [comment]
✅ The following works for me.

services.yaml
```
user.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments:
            $properties:
                firstName: ~
                lastName: ~
            $orderParameterName: 'orderby'
        tags:  [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false
```

And where I set my entity as resource:
```
App\Entity\User:
    collectionOperations:
        get:
            filters: ['user.search_filter', 'user.order_filter']
```



Using $varName under the key arguments in your service declaration forces the parameter in the constructor of your service to have the given value without taking care of the order in which arguments are given.
