### ISSUE TITLE
Docs - Custom Normaliser Circular Dependency

### ISSUE THREAD

**Issue by silverbackdan** [api-platform/core#2135]
If I create a normaliser as described here:
https://api-platform.com/docs/core/content-negotiation/#writing-a-custom-normalizer

There is a circular dependency when autowire is configured.

```
  Circular reference detected for service "App\Serializer\CustomNormalizer", path: "App\Serializer\CustomNormalizer -> serializer -> App\Serializer\CustomNormalizer". 
```

Solution is to use the AbstractNormalizer typehint and define the service as decorating the item normalizer. Full example:

```php
<?php

namespace App\Serializer;

use ApiPlatform\Core\Api\IriConverterInterface;
use ApiPlatform\Core\Serializer\AbstractItemNormalizer;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

final class CustomNormalizer implements NormalizerInterface, DenormalizerInterface
{
    private $normalizer;

    public function __construct(
        AbstractNormalizer $normalizer,
        IriConverterInterface $iriConverter
    )
    {
        if (!$normalizer instanceof DenormalizerInterface) {
            throw new \InvalidArgumentException('The normalizer must implement the DenormalizerInterface');
        }
        if(!$normalizer instanceof AbstractItemNormalizer) {
            throw new \InvalidArgumentException('The normalizer must be an instance of AbstractItemNormalizer');
        }
        $handler = function ($entity) use ($iriConverter) {
            return $iriConverter->getIriFromItem($entity);
        };
        $normalizer->setMaxDepthHandler($handler);
        $normalizer->setCircularReferenceHandler($handler);
        $this->normalizer = $normalizer;
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        return $this->normalizer->denormalize($data, $class, $format, $context);
    }

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $this->normalizer->supportsDenormalization($data, $type, $format);
    }

    public function normalize($object, $format = null, array $context = [])
    {
        return $this->normalizer->normalize($object, $format, $context);
    }

    public function supportsNormalization($data, $format = null)
    {
        return $this->normalizer->supportsNormalization($data, $format);
    }
}
```

yaml services config:
```yaml
App\Serializer\CustomNormalizer:
        autowire: false
        autoconfigure: false
        tags: ['serializer.normalizer']
        decorates: 'api_platform.jsonld.normalizer.item'
        arguments:
            $normalizer: '@App\Serializer\CustomNormalizer.inner'
            $iriConverter: '@ApiPlatform\Core\Api\IriConverterInterface'
```

UPDATE:
The above results in another error
`The injected serializer must be an instance of "Symfony\Component\Serializer\Normalizer\NormalizerInterface".`

Having a little debug now trying to resolve this as the injected serializer is null

**Comment by silverbackdan** [comment]
Final working setup:
```php
<?php

namespace App\Serializer;

use ApiPlatform\Core\Api\IriConverterInterface;
use ApiPlatform\Core\Serializer\AbstractItemNormalizer;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

final class CustomNormalizer implements NormalizerInterface, DenormalizerInterface
{
    private $normalizer;

    public function __construct(
        NormalizerInterface $normalizer,
        IriConverterInterface $iriConverter
    )
    {
        if (!$normalizer instanceof DenormalizerInterface) {
            throw new \InvalidArgumentException('The normalizer must implement the DenormalizerInterface');
        }
        if(!$normalizer instanceof AbstractItemNormalizer) {
            throw new \InvalidArgumentException('The normalizer must be an instance of AbstractItemNormalizer');
        }
        $handler = function ($entity) use ($iriConverter) {
            return $iriConverter->getIriFromItem($entity);
        };
        $normalizer->setMaxDepthHandler($handler);
        $normalizer->setCircularReferenceHandler($handler);
        $this->normalizer = $normalizer;
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        return $this->normalizer->denormalize($data, $class, $format, $context);
    }

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $this->normalizer->supportsDenormalization($data, $type, $format);
    }

    public function normalize($object, $format = null, array $context = [])
    {
        return $this->normalizer->normalize($object, $format, $context);
    }

    public function supportsNormalization($data, $format = null)
    {
        return $this->normalizer->supportsNormalization($data, $format);
    }
}
```

```yaml
App\Serializer\CustomNormalizer:
        autowire: false
        autoconfigure: true
        arguments:
            $normalizer: '@api_platform.jsonld.normalizer.item'
            $iriConverter: '@ApiPlatform\Core\Api\IriConverterInterface'
```

The only difference in the docs and what works seems to be in the config. I'm having to inject the API Platform normalizer rather than what is automatically injected using the NormalizerInterface typehint
