### ISSUE TITLE
[BUG] Doctrine bridge QueryChecker does not detect entity with composite key

### ISSUE THREAD

**Issue by mcn-fredw** [api-platform/core#2136]
Doctrine yaml:

```yaml
App\Entity\SideA:
    type: entity
    table: sideA
    repositoryClass: App\Repository\SideARepository
        id:
            type: guid
            column: id
            generator:
                strategy: UUID
    fields:
        name:
            type: string
            column: name
            length: 1023
            options:
                default: ''
        description:
            type: text
            column: description
            nullable: true
            options:
                default: ''

App\Entity\SideB:
    type: entity
    table: sideB
    repositoryClass: App\Repository\SideARepository
        id:
            type: guid
            column: id
            generator:
                strategy: UUID
    fields:
        name:
            type: string
            column: name
            length: 1023
            options:
                default: ''
        description:
            type: text
            column: description
            nullable: true
            options:
                default: ''

App\Entity\Intersect:
    type: entity
    table: intersect
    repositoryClass: App\Repository\IntersectRepository
    id:
        sideA:
            type: string
            column: alert
        sideB:
            type: string
            column: log
    fields:
        active:
            type: boolean
            column: active
            nullable: false
            options:
                default: false

API yaml:
App\Entity\SideA:
    shortName: SideA
    itemOperations:
        get:
            method: GET
            requirements:
                id: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
        put:
            method: PUT
            requirements:
                id: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
    collectionOperations:
        get:
            method: GET
            filters:
                - name.search_filter
        post:
            method: POST
    properties:
        id:
            identifier: true
            readable: true
            writable: false
        name:
            readable: true
            writable: true
        description:
            readable: true
            writable: true

App\Entity\SideB:
    shortName: SideB
    itemOperations:
        get:
            method: GET
            requirements:
                id: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
        put:
            method: PUT
            requirements:
                id: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
    collectionOperations:
        get:
            method: GET
            filters:
                - name.search_filter
        post:
            method: POST
    properties:
        id:
            identifier: true
            readable: true
            writable: false
        name:
            readable: true
            writable: true
        description:
            readable: true
            writable: true

App\Entity\Intersect:
    shortName: Intersect
    itemOperations:
        get:
            method: GET
            requirements:
                sideA: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
                sideB '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
        put:
            method: PUT
            requirements:
                sideA: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
                sideB: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
    collectionOperations:
        get:
            method: GET
            filters:
                - sideA.search_filter
                - sideB.search_filter
                - active.bool_filter
        post:
            method: POST
    properties:
        sideA:
            readable: true
            writable: true
            identifier: true
        sideB:
            readable: true
            writable: true
            identifier: true
        active:
            readable: true
            writable: true
```

When you go to the collection endpoint /api/intersects, it will trigger the doctrine issue mentioned in https://api-platform.com/docs/core/pagination/#avoiding-double-sql-requests-on-doctrine

Tracing the code, `ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryChecker::hasRootEntityWithCompositeIdentifier()` is called and always passes `$isForeign=false`  to `hasRootEntityWithIdentifier()`. The if block in `hasRootEntityWithIdentifier()` does not look at `$rootMetadata->isIdentifierComposite` in that case, so it does not detect the composite key.
changing the if clause in `hasRootEntityWithIdentifier()` to:
 `if ($rootMetadata instanceof ClassMetadata && ($rootMetadata->isIdentifierComposite || $rootMetadata->containsForeignIdentifier))`
makes the code works as expected for all 3 collection endpoints.

Not sure why the upper logic is not calling `ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryChecker::hasRootEntityWithForeignKeyIdentifier()`, as that would examine `$rootMetadata->isIdentifierComposite`.

Are the values of `$isForeign` the inverse of what they should be in `hasRootEntityWithForeignKeyIdentifier()` and `hasRootEntityWithCompositeIdentifier()` ?
