### ISSUE TITLE
[BUG] Paginations 'itemsPerPage' querystring parameter is ignored

### ISSUE THREAD

**Issue by diimpp** [api-platform/core#2151]
Hi,

I'm following documentation to enable pagination globally on all my resources https://api-platform.com/docs/core/pagination

My `platform/api_platform.yaml`,
```yaml
 api_platform:
     mapping:
         paths: ['%kernel.project_dir%/config/api_platform']
     version: 1.0.0
     # Enable the Varnish integration
     http_cache:
         invalidation:
             enabled: true
             varnish_urls: ['%env(VARNISH_URL)%']
         max_age: 0
         shared_max_age: 3600
         vary: ['Content-Type', 'Authorization']
         public: true
     enable_fos_user: true
     swagger:
         api_keys:
             apiKey:
                 name: Authorization
                 type: header
     collection:
         pagination:
             enabled: true
             client_enabled: true
             page_parameter_name: page
             items_per_page_parameter_name: itemsPerPage
#             items_per_page: 20
```

I've tried it on various resources, with empty configuration and not.

Query string like
> resources?itemsPerPage=1

is ignored.

If `items_per_page` is specified via yaml configuration, then number of elements will be limited correctly.
`page` property works alright with or without `page_parameter_name`

I'm using api-platform/core-2.3.0
