### ISSUE TITLE
$this->tokenStorage->getToken()->getUser() return null

### ISSUE THREAD

**Issue by agatagolebiowska** [api-platform/core#2163]
Hi. I wanted to use logic from this example: [https://api-platform.com/docs/core/extensions#custom-extension](https://api-platform.com/docs/core/extensions#custom-extension) in my app. I have exact same file as CurrentUserExtension.php, but my service works only when I hardcode user id, because it never return a user object from `$this->tokenStorage->getToken()->getUser()`. I read that this can be related to firewall config, but I didn't found any answer how to do it properly. Maybe someone can tell me what am I doing wrong.
My security.yaml:
```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_docs:
              pattern: ^/api/docs
              anonymous: true
        api:
              pattern: ^/api
              fos_oauth: true
              stateless: true
              anonymous: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: app_dashboard
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            anonymous:    true

        oauth_authorize:
            pattern: ^/oauth/v2/auth|^/login*
            form_login: ~
            anonymous: true

        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

    access_control:
        - { path: ^/api/docs$, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/[a-z]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]+/logout$, role: ROLE_USER }
        - { path: ^/[a-z]+/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]+/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_ADMIN }
```
