### ISSUE TITLE
Error generating the doc when registering a non-entity class 

### ISSUE THREAD

**Issue by blt909** [api-platform/core#218]
Hi,

We would like to registeras a ressource, a class that is not an ORM entity class.
This is our use case : 
- We have a class of properties loaded with static arrays
- We try to expose it as a ressource with custom operations

```yaml
    resource.l10nutils.item_operation.timezone_custom_get:
        class:   "Dunglas\ApiBundle\Api\Operation\Operation"
        public:  false
        factory: [ "@api.operation_factory", "createItemOperation" ]
        arguments:
            -    "@resource.l10nutils"                  # Resource
            -    [ "GET" ]                              # Methods
            -    "/timezone"                            # Path
            -    "AppBundle:CustomL10nUtils:getTimeZone" # Controller
            -    "TimeZone"                             # Route name
            -    # Context (will be present in Hydra documentation)
                 "@type":       "hydra:Operation"
                 "hydra:title": "All TimeZone"
                 "returns":     "xmls:string"

    resource.l10nutils:
        parent:         "api.resource"
        arguments:      [ "AppBundle\\Entity\\Utils\\L10nUtils" ]
        calls:
            -   method:    "initItemOperations"
                arguments: [ [ "@resource.l10nutils.item_operation.timezone_custom_get" ] ]
        tags:      [ { name: "api.resource" } ]
```
We can call our custom operations but we have an error when accessing the doc : 
```
CRITICAL - Uncaught PHP Exception Doctrine\ORM\Mapping\MappingException: "Class "AppBundle\Entity\Utils\L10nUtils" is not a valid entity or mapped super class." at /media/fxlan/git/api-pm/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php line 336 
```
Is there any way to accept non-entity classes ?
