### ISSUE TITLE
Custom exception in custom action is marked as uncaught in logs

### ISSUE THREAD

**Issue by Cethy** [api-platform/core#2216]
The exception is correctly caught by the `ExceptionListener` (as I receive a 400 with the exception message in hydra format), but it also reach the logs as a critical error : 
`[critical] Uncaught PHP Exception App\Exception\FileExtensionNotAllowedException: "file type "txt" is not allowed."`

Any idea what am I missing ?

---

Exception class
```php
namespace App\Exception;
class FileExtensionNotAllowedException extends \Exception {}
```

Action controller
```php
namespace App\Controller;

// ...
use App\Exception\FileExtensionNotAllowedException;

class MediaObjectUpload
{
    // ...
    /**
     * @param Request $request
     * @return MediaObject
     *
     * @throws FileExtensionNotAllowedException
     */
    public function __invoke(Request $request): MediaObject
    {
        // ...
        throw new FileExtensionNotAllowedException(sprintf('file type "%s" is not allowed.', $extension));
    }
}
```

api_platform.yml
```yml
api_platform:
    # ...
    exception_to_status:
        # The 2 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        ApiPlatform\Core\Exception\InvalidArgumentException: 'HTTP_BAD_REQUEST'

        App\Exception\FileExtensionNotAllowedException: 400
```
