### ISSUE TITLE
Write new entity with ManyToMany relation with writing into mapping table

### ISSUE THREAD

**Issue by martinharder** [api-platform/core#2234]
I have two entities User and Location. Both have realtions to each other: User has Locations and Location has Users:

```php
class User
{
    /**
     * @var int
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"user:read", "location:read", "location:write"})
     */
    private $id;

    /**
     * @var Location[]|ArrayCollection|null
     * @ORM\ManyToMany(targetEntity="App\Entity\Location", inversedBy="users")
     * @ORM\JoinTable(name="user_locations")
     * @Groups({"location:read"})
     */
    private $locations;

    ...
}

class Location
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     *  @Groups({"location:read", "location:write"})
     */
    private $id;

    /**
     * @var User[]|ArrayCollection
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="locations")
     * @ORM\JoinTable(name="user_locations")
     * @Groups({"location:read", "location:write"})
     */
    private $users;

    ...
}
```

My resources.yaml looks like this (just the relevant part):
```yaml
App\Entity\Location:
    itemOperations:
        get:
            method: 'GET'
            path: '/locations/{id}'
            normalization_context:
                groups: ['location:read']
    collectionOperations:
        get:
            method: 'GET'
            path: '/locations'
            normalization_context:
                groups: ['location:read']
        create:
            method: 'POST'
            path: '/locations'
            denormalization_context:
                groups: ['location:write']
            normalization_context:
                groups: ['location:write']
App\Entity\User:
    itemOperations:
        get:
            method: 'GET'
            path: '/users/{id}'
            normalization_context:
                groups: ['user:read']
            denormalization_context:
                groups: ['location:write']
    collectionOperations:
        get:
            method: 'GET'
            path: '/users'
            normalization_context:
                groups: ['user:read']
        create:
            method: 'POST'
            path: '/users'
            denormalization_context:
                groups: ['user:write', 'location:write']
            normalization_context:
                groups: ['user:write', 'location:write']
```

I call a POST /locations with 
```
[
    'name' => 'location name'
    ...
    'users' => [
        '/users/1',
        '/users/2',
    ]
]
```
or
```
[
    'name' => 'location name'
    ...
    'users' => [
        ['id' => 1],
        ['id' => 2],
    ]
]
```

The new location is created but there is no entry in the mapping table 'user_locations'.
I just want to store the relation of users and locations and not to create or update users! There should be an error when the given user id doesn't exist. How can I achieve it?
