### ISSUE TITLE
Default value option on Swagger api keys

### ISSUE THREAD

**Issue by soullivaneuh** [api-platform/core#2280]
My current project API need this header to authenticate:

```
Authorization: Bearer your_api_token
```

So I add this configuration for Swagger:

```yaml
api_platform:
    swagger:
        api_keys:
            -
                name: Authorization
                type: header
```

It works. But the customer always have to add `Bearer` on the form content.

It would be great to have a `default_value` option on each `api_keys` element.
