### ISSUE TITLE
Configuration of format leads generate wrong swagger documentation

### ISSUE THREAD

**Issue by Nek-** [api-platform/core#2304]
Hello guys.

I noticed that if I specify the following configuration:

```yaml
api_platform:
    formats:
        jsonld:
            mime_types: ['application/ld+json']
```

It fills the `FormatsProvider` with : 
```
"jsonld" => array:1 [
    "mime_types" => array:2 [
      0 => "application/ld+json"
      1 => "application/ld+json"
    ]
  ]
```

This generate a duplication in the swagger json, which is wrong

![image](https://user-images.githubusercontent.com/972456/47928963-0300a700-dec8-11e8-8dc3-3bb5f1a42129.png)

**Comment by antograssiot** [comment]
are you using 2.3 or master as I can't reproduce it on a fresh install @Nek-  ?

**Comment by Nek-** [comment]
You're absolutely right. I just took the test too and the fact is that I had the following configuration on my project:

```yaml
# config/api_platform.yaml
api_platform:
    formats:
        jsonld:
            mime_types: ['application/ld+json']

# config/dev/api_platform.yaml
api_platform:
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
```

Once configuration merged, the problem occurs. I just have to remove the part related to jsonld in the dev config file.
