### ISSUE TITLE
[Bug] Set properties at yaml

### ISSUE THREAD

**Issue by RIPm** [api-platform/core#2330]
When i use `yaml` to configure resources. 
```yaml
resources:
    App\Entity\Goods:
        attributes:
            normalization_context:
                groups: ['goods:read']
        collectionOperations:
            get: ~
        itemOperations:
            get: ~

        properties:
            id:
                attributes:
                    swagger_context:
                        description: '编号'
            name:
                attributes:
                    swagger_context:
                        description: '商品名称'
            stock:
                attributes:
                    swagger_context:
                        description: '商品库存'
```
My serializater.yaml: 
```yaml
App\Entity\Goods:
    attributes:
        id:
            groups: ['banner:read', 'goods:read']

        name:
            groups: ['goods:read']

        stock:
            groups: ['goods:read']
```
When i look the docs server (copy content to here):
```
// Goods-banner:read
id | integerreadOnly: true编号
-- | --
name | string商品名称
stock | integer商品库存
```
My expectation is:
```
// Goods-banner:read
id | integerreadOnly: true编号
```
And that i try use `ApiProtery` at entity, not had this issue.
