### ISSUE TITLE
Per page option not present on swagger documentation

### ISSUE THREAD

**Issue by Soullivaneuh** [api-platform/core#2368]
With this configuration:

```yaml
api_platform:
    collection:
        pagination:
            items_per_page: 100
            maximum_items_per_page: 1000
            client_items_per_page: true
            items_per_page_parameter_name: per_page
```

I see the `page` parameter, not the `per_page` one.
