### ISSUE TITLE
[qoustion] Is it possible to extend the swagger documentation

### ISSUE THREAD

**Issue by rubenvdlinde** [api-platform/core#2457]
I would like te extend the swagger documentation in the lines of http://rebilly.github.io/ReDoc/openapi.yaml

Mainly in order to support redoc instead of swagger ui, now the normal swagger.yaml file works nicly when approached trough redoc, but I’m missing a lot of options on the yaml. Like:

```
termsOfService: 'http://swagger.io/terms/'
  contact:
    name: API Support
    email: apiteam@swagger.io
    url: https://github.com/Rebilly/ReDoc
x-logo:
    url: 'https://rebilly.github.io/ReDoc/petstore-logo.png'
    altText: Petstore logo
license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: Find out how to create Github repo for your OpenAPI spec.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: pet
    description: Everything about your Pets
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
x-tagGroups:
  - name: General
    tags:
      - pet
      - store
  - name: User Management
    tags:
      - user
servers:
  - url: //petstore.swagger.io/v2
    description: Default server
  - url: //petstore.swagger.io/sandbox
    description: Sandbox server
```

Now  I can easally manualy add those to the yaml file afther generating it, but it would then be oferwritten next time the yaml file is generated. Wichs kinda success.

Is it possible to set the above options trough the api-plaftform packadge config, where the other general swagger info is set?

**Comment by aaa2000** [comment]
If you want redoc, see maybe #2384

**Comment by rubenvdlinde** [comment]
Wel i'm already using redoc, this question is more about getting to use all the power of redoc and the available extra documentation options.

**Comment by aaa2000** [comment]
I think that you can use https://api-platform.com/docs/core/swagger/#overriding-the-openapi-specification

```php
<?php

namespace App\Swagger;

use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

final class SwaggerDecorator implements NormalizerInterface
{
    public $params;
    private $decorated;

    public function __construct(NormalizerInterface $decorated, array $params = [])
    {
        $this->decorated = $decorated;
        $this->params = $params;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $docs = $this->decorated->normalize($object, $format, $context);

        return array_merge($docs, $this->params);
    }

    public function supportsNormalization($data, $format = null)
    {
        return $this->decorated->supportsNormalization($data, $format);
    }
}
```

in api/config/services.yaml

```
    App\Swagger\SwaggerDecorator:
        #decorates: 'api_platform.swagger.normalizer.documentation'
        decorates: 'api_platform.swagger.normalizer.api_gateway'
        arguments:
            - '@App\Swagger\SwaggerDecorator.inner'
            - '%api_documentation%'
        autoconfigure: false
```

and add the parameters api/config/services.yaml:

```yml
parameters:
    api_documentation:
        servers:
        -   url: //petstore.swagger.io/v2
            description: Default server
        -   url: //petstore.swagger.io/sandbox
            description: Sandbox server
        info:
            description: |
                This is a sample server Petstore server.
                You can find out more about Swagger at
                [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
                For this sample, you can use the api key `special-key` to test the authorization filters.

                # Introduction
                This API is documented in **OpenAPI format** and is based on
                [Petstore sample](http://petstore.swagger.io/) provided by [swagger.io](http://swagger.io) team.
                It was **extended** to illustrate features of [generator-openapi-repo](https://github.com/Rebilly/generator-openapi-repo)
                tool and [ReDoc](https://github.com/Rebilly/ReDoc) documentation. In addition to standard
                OpenAPI syntax we use a few [vendor extensions](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md).

                # OpenAPI Specification
                This API is documented in **OpenAPI format** and is based on
                [Petstore sample](http://petstore.swagger.io/) provided by [swagger.io](http://swagger.io) team.
                It was **extended** to illustrate features of [generator-openapi-repo](https://github.com/Rebilly/generator-openapi-repo)
                tool and [ReDoc](https://github.com/Rebilly/ReDoc) documentation. In addition to standard
                OpenAPI syntax we use a few [vendor extensions](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md).

                # Cross-Origin Resource Sharing
                This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/).
                And that allows cross-domain communication from the browser.
                All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.

                # Authentication

                Petstore offers two forms of authentication:
                  - API Key
                  - OAuth2
                OAuth2 - an open protocol to allow secure authorization in a simple
                and standard method from web, mobile and desktop applications.

                <security-definitions />

            version: 1.0.0
            title: 'FOO BAR TITLE'
            termsOfService: 'http://swagger.io/terms/'
            contact:
                name: API Support
                email: apiteam@swagger.io
                url: https://github.com/Rebilly/ReDoc
            x-logo:
                url: 'https://rebilly.github.io/ReDoc/petstore-logo.png'
                altText: Petstore logo
            license:
                name: Apache 2.0
                url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
        externalDocs:
            description: Find out how to create Github repo for your OpenAPI spec.
            url: 'https://github.com/Rebilly/generator-openapi-repo'

```
