### ISSUE TITLE
Add support for JWTs

### ISSUE THREAD

**Issue by jmwri** [api-platform/core#2494]
Currently the swagger-ui implementation only supports apiKey which is hardcoded in `DocumentationNormalizer.php`:
```
if ($this->apiKeys) {
            foreach ($this->apiKeys as $key => $apiKey) {
                $name = $apiKey['name'];
                $type = $apiKey['type'];

                $securityDefinitions[$key] = [
                    'type' => 'apiKey',
                    'in' => $type,
                    'description' => sprintf('Value for the %s %s', $name, 'query' === $type ? sprintf('%s parameter', $type) : $type),
                    'name' => $name,
                ];

                $security[] = [$key => []];
            }
        }
```

So the following config doesn't work:
```
    swagger:
        api_keys:
            jwt:
                name: Authorization
                type: header
```
Is there a way around this, or plans to implement in the future?
