### ISSUE TITLE
Item route for messenger in yaml configuration

### ISSUE THREAD

**Issue by RonRademaker** [api-platform/core#2498]
Hi,

I'm using the new messenger features and something confuses me a lot. I know it's required to have at least an item route. However, when configuring a messenger endpoint this doesn't seem to be the case:

```
/**
 * @ApiResource(
 *     messenger=true,
 *     collectionOperations={
 *         "post"={"status"=202}
 *     },
 *     itemOperations={},
 *     outputClass=false
 * )
 */
```

And this actually works 🎉 

However, I got all my config in yml (and prefer that), so I translate this to a yaml config:

```
resources:
  My\Message:
    messenger: true
    collectionOperations:
      post:
        status: 202
        output_class: false
    itemOperations: []
```

This breaks 😢 with the (expected) `No item route associated with the type` error. Adding a get route is also not evident, because it triggers the `No identifiers defined for resource of type` error. Obviously, my messenger messages are not doctrine entities with identifiers.

**Comment by ragboyjr** [comment]
@RonRademaker in your yaml, put `output_class: false` under 

```yaml
My\Message:
  attributes:
    output_class: false
```

That should be the equivalent to what you have in your Annotations.

**Comment by mettallex** [comment]
Hello,

I have the same issue with yaml configuration. Do you have any idea ?

Thanks

**Comment by fabienCambournacAcseo** [comment]
Try :
```yaml
resources:
  My\Message:
    collectionOperations:
      post:
        status: 202
        output_class: false
    itemOperations: []
    attributes:
        messenger: true
        output: false
```
