### ISSUE TITLE
Notice: Undefined index: output when throwing an exception

### ISSUE THREAD

**Issue by h3llr4iser** [api-platform/core#2551]
Hi, I just update to master branch and I am getting an error on custom operations when I throw an exception:
Notice: Undefined index: output
JsonLdContextTrait.php line 58

```yaml
api_platform:
  exception_to_status:
    App\Exception\CustomeException: 400
```

```php

/**
 * @ApiResource(
 *     itemOperations={
 *       "example"={
 *         "method"="PUT",
 *         "path"="/entity/example/{id}",
 *         "controller"=App\Controller\Example::class,
 *       },
 *     }
 * ) 
*/
class Entity
{
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid")
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $example;
}
```

```php
public function __invoke(Entity $data): Entity
    {
       if(!$data->example) {
           throw new CustomException("Error"); 
       }

        $this->entityManager->persist($data);
        $this->entityManager->flush();

        return $data;
    }
```

**Comment by antograssiot** [comment]
I did had the same and it was linked to the normalizers priority change. Do you have custom normalizers ? I had to change mines.

**Comment by h3llr4iser** [comment]
yes, I have custom normalizers. I had been problems with normalizer since i update. Now I have only a custom normalizer:

```yaml
  App\Normalizer\ApiNormalizer:
    decorates: 'api_platform.jsonld.normalizer.item'
    arguments: [ '@App\Normalizer\ApiNormalizer.inner' ]    
```
