### ISSUE TITLE
Correctly tagged DataTransformer and output resource definition seem to be ignored.

### ISSUE THREAD

**Issue by Kishlin** [api-platform/core#2553]
Disclaimer : I know all my code is a huge overkill for what I'm doing. I'm actually just trying to make this work on a basic operation before using the stack application-wide.

What I want to achieve : make a custom api-platform operation, which fetches an entity from the DB and returns it using a view model, instead of serializing the actual doctrine entity. I'm using [custom operations](https://api-platform.com/docs/core/operations/#creating-custom-operations-and-controllers) and [DTO](https://api-platform.com/docs/core/dto/) accordingly to the documentation (so I hope).

**The issue is**, data transformation is being completely ignored, and the actual entity is serialized, not the view model. My data transformer is never called, although being appropriately tagged.

My basic entity, which just has an id and a name. The one I try to fetch and the one actually returned by the api.
```php
namespace Vs\Application\Entity;

use Vs\BusinessRules\Entity\AbstractEntity;
use Vs\Presentation\ViewModels\EntityViewModel;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation as ApiPlatform;

/**
 * @ApiPlatform\ApiResource(
 *     output=EntityViewModel::class,
 *     collectionOperations={},
 *     itemOperations={
 *         "get"={
 *             "method"="GET",
 *             "path"="/entity/{id}",
 *             "controller"=Vs\Application\Controller\GetEntity::class,
 *             "denormalization_context"={"default"}
 *         }
 *     }
 * )
 *
 * @ORM\Entity(repositoryClass="Vs\Application\Repository\EntityRepository")
 */
class Entity extends AbstractEntity
{
    /**
     * @ORM\Id
     * @ORM\Column(name="id", nullable=false, type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", nullable=false, type="string", length=30)
     */
    protected $name;
}
```

For the record, it just inherits the domain definition of the entity to specify platform-related configuration (I don't want my domain to know how I'm persisting entities, what framework I'm using, etc (e.g. api platform, doctrine configuration, and so on)).
```php
namespace Vs\BusinessRules\Entity;

abstract class AbstractEntity
{
    /**
     * @var int
     */
    protected $id;

    /**
     * @var string
     */
    protected $name;

    public function getId(): int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }
}
```

The view model, only displaying the name of the entity. I want this to be returned by my get operation.
```php
namespace Vs\Presentation\ViewModels;

use Symfony\Component\Serializer\Annotation as Serializer;

class EntityViewModel
{
    /**
     * @var string
     *
     * @Serializer\Groups({"default"})
     */
    private $name;

    public function __construct(string $name)
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }
}
```

The data transformer which transforms the concrete entity to the view model:
```php
namespace Vs\Application\DataTransformer;

use ApiPlatform\Core\DataTransformer\DataTransformerInterface;
use Vs\Application\Entity\Entity;
use Vs\Presentation\ViewModels\EntityViewModel;

final class EntityOutputDataTransformer implements DataTransformerInterface
{
    /**
     * @param Entity $object
     * @param string $to
     * @param array $context
     *
     * @return EntityViewModel
     */
    public function transform($object, string $to, array $context = [])
    {
        return new EntityViewModel($object->getName());
    }

    public function supportsTransformation($object, string $to, array $context = []): bool
    {
        return EntityViewModel::class === $to && $object instanceof Entity;
    }
}
```

Not sure why, but I've noticed (using the built-in Symfony console command debug:container) the tag isn't added to my service if I don't specify it myself, although autoconfigure is enabled. So I just hand-written it (checking I didn't make any typo).

Services definition:
```yml
services:
    _defaults:
        autowire: true
        autoconfigure: true

[...]

    Vs\Application\DataTransformer\:
        resource: '../src/Application/DataTransformer'
        tags: ['api_platform.data_transformer']
```

The tag does work, as suggests debugging the container:
```
$ de php sfy debug:container entityoutput

Information for Service "Vs\Application\DataTransformer\EntityOutputDataTransformer"
=====================================================================

 ---------------- ------------------------------------------------------------ 
  Option           Value                                                       
 ---------------- ------------------------------------------------------------ 
  Service ID       Vs\Application\DataTransformer\EntityOutputDataTransformer  
  Class            Vs\Application\DataTransformer\EntityOutputDataTransformer  
  Tags             api_platform.data_transformer  
...                             
```

If need be, the controller for the custom operation:
```php

namespace Vs\Application\Controller;

use Vs\BusinessRules\Requester\GetEntityRequestAssembler;
use Vs\BusinessRules\UseCase\GetEntity as UseCase;
use Vs\BusinessRules\Entity\AbstractEntity;

class GetEntity
{
    /**
     * @var GetEntityRequestAssembler
     */
    private $getEntityRequestAssembler;

    /**
     * @var UseCase
     */
    private $getEntityUseCase;

    public function __construct(
        GetEntityRequestAssembler $getEntityRequestAssembler,
        UseCase $getEntityUseCase
    ) {
        $this->getEntityRequestAssembler = $getEntityRequestAssembler;
        $this->getEntityUseCase = $getEntityUseCase;
    }

    public function __invoke(AbstractEntity $data): AbstractEntity
    {
        $request = $this->getEntityRequestAssembler->write($id = $data->getId());

        $response = $this->getEntityUseCase->execute($request);

        return $response->getEntity();
    }
}
```
I take it the operation works as expected, since I actually get back the entity I want, although not being transformed to the view model.

My composer.json looks like this:
```
    "require": {
        ...,
        "api-platform/api-pack": "^1.2",
        "api-platform/core": "^2.4@dev",
        ...
    },
```
This resolves to dev-master being installed for api-platform/core. I figured using only the api-pack definition, due to the minimum stability being set to stable, I couldn't get a verison of api-platform/core with data transformers and output definition.

My ApiPlatform configuration:
```yml
api_platform:
    title: 'Virtual Squirrels API'
    description: 'The Virtual Squirrels application API.'
    version: '1.0.0'
    allow_plain_identifiers: true
    mapping:
        paths: ['%kernel.project_dir%/src/Application/Entity']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html; format=utf8']
    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']
    collection:
        pagination:
            enabled: false
    graphql:
        enabled: false
```

**The Api returns**
```json
{
  "id": 1,
  "name": "fdsfsdfsdfs"
}
```

when I would expect
```json
{
  "name": "fdsfsdfsdfs"
}
```

**What I've tried so far:**

- Injecting a logger in my data transformer, and trying to write logs all around the class. None of the logs are actually written. Which makes me think the data transformer is never called. I even put logs in the constructor but neither are they written, so the service isn't even instantiated.
- Added my data transformer as a dependency in the constructor of my operation/controller/you-name-it, and calling the supportsTransformation method with dummy parameters. It works alright, I see the logs for this call.
- Changing the service configuration to be dead-specific, which doesn't work either, but makes sense since the service had the tag anyway.
```yml
    Vs\Application\DataTransformer\EntityOutputDataTransformer:
        class: Vs\Application\DataTransformer\EntityOutputDataTransformer
        tags: ['api_platform.data_transformer']
```

**What am I missing ?** Why is api-platform not even trying to use my data transformer although it has the required tag ?
