### ISSUE TITLE
openapi_context dosn't take readOnly into acount

### ISSUE THREAD

**Issue by rubenvdlinde** [api-platform/core#2604]
Quite a simple bit of pain here :)

Im using ` php bin/console api:swagger:export --output=/srv/api/public/schema/openapi.yaml --yaml --spec-version=3`  to create a yaml file. So far so good, but..... The following property

```php
/**
	 * The lastname of the person that you are trying to invite <br /><b>Schema:</b> <a href="https://schema.org/familyName">https://schema.org/familyName</a>
	 *
	 * @var string
	 * @ApiProperty(
	 *     attributes={
	 *         "openapi_context"={
	 *             "type"="string",
	 *             "example"="Do",
	 *             "required"="true",
	 *             "maxLength"=250,
	 *             "readOnly"=false
	 *         }
	 *     }
	 * )
	 * @Groups({"invite","inviteGetuige"})
	 */
	public $geslachtsnaam;	
```

(and all of his litle friends) turn into:

``` yaml
geslachtsnaam:
          type: string
          example: Do
          required: 'true'
          maxLength: 250
          readOnly: true
          description: 'The lastname of the person that you are trying to invite <br /><b>Schema:</b> <a href="https://schema.org/familyName">https://schema.org/familyName</a>'
```

So the read only flips, and that of course couses the properties to not be displayend in the preview post. So thats a bit unexpected.

How could I fix this? besides manually altering the scheme.yaml?
