### ISSUE TITLE
Can't link enum class to Resource class to have correct swagger definition with enums

### ISSUE THREAD

**Issue by Arkowsky** [api-platform/core#2613]
When I run:

` bin/console api:swagger:export -y -o var/test_definiton.yml`

for my class:

```
/**
 * @ApiResource()
 */
class DeliveryMethod
{
  ....

    /**
     * @var Collection<PaymentMethod>
     * @Assert\Choice(callback={"PaymentMethod", "toArray"})
     * @ApiProperty(
     *     iri="https://schema.org/acceptedPaymentMethod",
     *     swaggerContext={
     *          "type"="array",
     *          "items"={"type"="string", "enum"={"Cash", "CreditCard"}},
     *     }
     * )
     */
    private $acceptedPaymentMethods;

.....

    public function getAcceptedPaymentMethods(): Collection
    {
        return $this->acceptedPaymentMethods;
    }

    public function setAcceptedPaymentMethods(Collection $acceptedPaymentMethods): DeliveryMethod
    {
        $this->acceptedPaymentMethods = $acceptedPaymentMethods;
        return $this;
    }

    public function addAcceptedPaymentMethods(PaymentMethod $paymentMethod)
    {
        $this->acceptedPaymentMethods[] = $paymentMethod;
        return $this;
    }
}
```
I have in my generated swagger file correct enums:

```
    DeliveryMethod:
        type: object
        description: 'DeliveryMethod....'
        externalDocs:
            url: 'http://schema.org/DeliveryMethod'
        properties:
            id:
                type: integer
           .....
            acceptedPaymentMethods:
                type: array
                items:
                    type: string
                    enum: [Cash, CreditCard]
```

But I have PaymentMethod(enum class) and I want to use it as relation to DeliveryMethod without need to hardcode all values from this class:

```
/**
 * @ApiResource(iri="http://schema.org/PaymentMethod",
 *  collectionOperations={"get"}
 * )
 */
class PaymentMethod extends Enum
{
    /**
     * @var string
     */
    const BY_BANK_TRANSFER = 'ByBankTransfer';

    /**
     * @var string
     */
    const PAY_U = 'PayU';

    /**
     * @var string http://purl.org/goodrelations/v1#COD Collect on delivery / Cash on delivery
     */
    const COD = 'COD';
...
}
```

How to define $acceptedPaymentMethods variable to have in swagger all values from related enum class - PaymentMethod?
