### ISSUE TITLE
Pagination params in Url break response(with client config enabled)

### ISSUE THREAD

**Issue by desmax** [api-platform/core#2718]
Looks like refactoring of PaginationExtension broke pagination params in url
https://github.com/api-platform/core/commit/89c0f30d188b0ff4f15302d1ee901353417663e3#diff-b6c1bf23325d339d3b93944061c72aad

I have this config

```
api_platform:
    collection:
        pagination:
            client_items_per_page: true
            client_enabled: true
```
my test request shows `"hydra:totalItems": 40` and correct links to other pages,
though when I add `?pagination=false` it says `"hydra:totalItems": 25`. 
I would expect it to be 40 with all items in one request.

`itemsPerPage` parameter has no effect at all.

v2.3.6 works as expected for both params.
