### ISSUE TITLE
Add the ability to choose the messenger bus used in the data persister

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#2729]
See: https://github.com/api-platform/api-platform/issues/1095

**Comment by soyuka** [comment]
I thought a bit about this and CQRS related architecture.

It'd be nice to be able to use two buses in Api Platform:
- Commands (async)
- Queries (sync)

Now, to have queries we'd have to use a bus inside a DataProvider? 

Thing is, the messenger component is really powerfull and could handle Validation etc. inside middlewares (which it does already) or even doctrine transaction (https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Messenger/DoctrineTransactionMiddleware.php). All this makes me think that the messenger should be handled upper in the chain (not only in persisting).

Say I want to benefit from the power of messenger, I'd register an event listener that comes post-denormalization, retrieve a result via the messenger (skip almost all our internal listeners and use middlewares instead) to end up giving a result via our current serialization process.

Anyway, I've looked into adding multiple buses on our current implementation and unless we have some kind of BusRegistry (which imo is anti-pattern) it's hard to add.

**Comment by er1z** [comment]
Think it's quite an important thing because it may affect application scaling (eg. handling of messages locally or via worker on another machine).

**Comment by ricohumme** [comment]
Blowing of the dust on this one.
With current auto injection we could leverage this behavior as well (I think)

when injecting a bus in a constructor you could for example do either of the following:
```php
public function __construct(MessageBusInterface $messageBus) {}
```

```php
public function __construct(MessageBusInterface $commandBus) {}
```

This will in turn give you the correct bus as defined in the messenger config
```yaml
framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                default_middleware: false
                middleware:
                    - handle_message

            query.bus:
                default_middleware: false
                middleware:
                    - handle_message

            event.bus:
                default_middleware: allow_no_handlers
```

So if it would be as easy as defining the bus name on the api resource, i.e.
```php
#[ApiResource(collectionOperations: [ 'get',
        'create' => [
            'status' => 202,
            'messenger' => 'input',
            'bus' => 'command.bus',
            'input' => DTO::class,
            'output' => false,
            'method' => 'POST',
            'path' => '/my/route',
        ]
    ], itemOperations: [ 'get' ])]
```
Hope my 2 cents here are putting you in the right direction.
