### ISSUE TITLE
Cannot autowire data-persister in custom bundle

### ISSUE THREAD

**Issue by KaporalK** [api-platform/core#2737]
Hi everyone! 
In a project i needed to create a custom data-persister to simulate the POST/PUT from my api. But i need this in multiple api so i want to make a bundle of this data-persister, so i made one.

But when i install it on a project, api-paltform seem to not register the data-persister while the symfony command `debug:container` return my data-persister and if i ask for more info about it i got 
```
 ---------------- ---------------------------------------------------------------
  Option           Value
 ---------------- ---------------------------------------------------------------
  Service ID       Acme.ApiReadOnlyBundle.DataPersister.ReadOnlyDataPersister
  Class            Acme\ApiReadOnlyBundle\DataPersister\ReadOnlyDataPersister
  Tags             api_platform.data_persister
  Public           no
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        yes
  Autoconfigured   yes
 ---------------- ---------------------------------------------------------------
```

So it seem that it has the tags and all

I don't know what i'm missing. (i'm fairly new in symfony bundle making)

my services.yaml
```yml
services:

  Acme.ApiReadOnlyBundle.DataPersister.ReadOnlyDataPersister:
    class: Acme\ApiReadOnlyBundle\DataPersister\ReadOnlyDataPersister
    public: false
    autowire: true
    arguments: ['@router.request_context']
    tags: ['api_platform.data_persister']


  Acme\ApiReadOnlyBundle\DataPersister\ReadOnlyDataPersister:
    alias: Acme.ApiReadOnlyBundle.DataPersister.ReadOnlyDataPersister
    public: false
```

my AcmeExtension.php
```php
namespace Acme\ApiReadOnlyBundle\DependencyInjection;

use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;
use Symfony\Component\HttpKernel\DependencyInjection\Extension;

class AcmeApiReadOnlyExtension extends Extension
{

    public function load(array $configs, \Symfony\Component\DependencyInjection\ContainerBuilder $container)
    {

        $loader = new YamlFileLoader($container, new FileLocator(__DIR__ .'/../Resources/config'));

        $loader->load('services.yaml');

    }
}
```

And sorry for my bad english
