### ISSUE TITLE
Exception handle not work

### ISSUE THREAD

**Issue by lichnow** [api-platform/core#2741]
After config the class of exception,I can get the result of ` json-ld`,but get a html page which status is 500.
like this:
![](http://static.phpna.com/images/20190418004433.png)
I have config it in `config/packages/api-platform.yaml`
```yaml
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity','%kernel.project_dir%/config/api']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        ApiPlatform\Core\Exception\InvalidArgumentException: 'HTTP_BAD_REQUEST'
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409
        App\Component\Auth\Confirm\Exception\ConfirmCodeException: 400
```
and the class code is very simple
```php
<?php
namespace App\Component\Auth\Confirm\Exception;

final class ConfirmCodeException extends \Exception
{

}
```
and I throw it in subscriber
```php
final class UserSubscriber implements EventSubscriberInterface
{
...
    public function codeConfirm(GetResponseForControllerResultEvent $event)
    {
       ...
            throw new ConfirmCodeException('the validation code not matched.');
    }
    public static function getSubscribedEvents()
    {
       'kernel.view' => [
                ['codeConfirm', EventPriorities::POST_VALIDATE]
         ],
    }
}
```
What caused it to happen this error?
