### ISSUE TITLE
Swagger ui location

### ISSUE THREAD

**Issue by kl3sk** [api-platform/core#2753]
Hello,

I know this is ever open but I don't find any solution (for me),

### As the docs said, to change Sawgger UI location I have to:

```yaml
# api/config/packages/api_platform.yaml
api_platform:
    enable_swagger_ui: false
```
And
```yaml
# app/config/routes.yaml
swagger_ui:
    path: /new_location # <- other url
    controller: api_platform.swagger.action.ui
```

But, in this case i have this error:
`Controller "api_platform.swagger.action.ui" does neither exist as service nor as class`

### If I set to:
```yaml
# api/config/packages/api_platform.yaml
api_platform:
    enable_swagger_ui: true
```

It works back, but all my "unprotected" (public) routes respond as the swagger UI.

Any help is appreciated.

Thanks 

PHP 7.2
Nginx 1.14
Symfony 4.2.7
Api-platform 2.4.2
