### ISSUE TITLE
Api Subresource Swagger Context YAML Configuration problem

### ISSUE THREAD

**Issue by safaksaylam** [api-platform/core#2802]
I have a Api Subresource property configuration swagger context problem.

If I use to yaml configuration, messages come in body example. But I'm not adding serialization groups etc. If I use to annotation configuration, messages not come in body example. How to fix it? I want to use yaml configuration, but I didn't fix it.

resources/message_category.yaml
```
App\Entity\MessageCategory:
...
    properties:
        id:
            identifier: true
        messages:
            subresource: { collection: true, resourceClass: 'App\Entity\Message', maxDepth: 1 }
```

Body example
```
{
  "id": 0,
  "enabled": true,
  "name": "string",
  "slug": "string",
  "messages": [
    "string"
  ]
}
```

----

Entity/MessageCategory.php
```
...

    /**
     * @ApiSubresource(maxDepth=1)
     *
     * @var Message[]
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="messageCategory", cascade={"remove"})
     */
    private $messages;

...
```

Body example
```
{
  "id": 0,
  "enabled": true,
  "name": "string",
  "slug": "string"
}
```
