### ISSUE TITLE
Broken behavior processing operations with defined 'output' class

### ISSUE THREAD

**Issue by Perf** [api-platform/core#2803]
Hello,
an exception is thrown when processing request by `WriteListener.php`.
At line 81 there is a call to get Iri from object of output class. But, obviously, it's not always possible, as the output class could be another object rather than ApiResource.
```php
if ($hasOutput) {
    $request->attributes->set('_api_write_item_iri', $this->iriConverter->getIriFromItem($controllerResult));
}
```
Exception:
> No item route associated with the type "Lexik\Bundle\JWTAuthenticationBundle\Response\JWTAuthenticationSuccessResponse" at /srv/api/vendor/api-platform/core/src/Bridge/Symfony/Routing/RouteNameResolver.php line 62

Here is a sample configuration of a custom operation:
```yaml
    collectionOperations:
        confirmation:
            method: 'POST'
            path: '/users/confirmation'
            access_control: 'is_anonymous()'
            messenger: 'input'
            input: 'App\Entity\User\Input\UserConfirm'
            output: 'Lexik\Bundle\JWTAuthenticationBundle\Response\JWTAuthenticationSuccessResponse'
```

**Some additional notes:**
There was a related issue #2550 that was fixed with #2628.
It worked for a while... and seems to be was 'broken' with: https://github.com/api-platform/core/commit/433ce07877655f245f164df36f1a249a7faf2abb#diff-3bc4e0ec1a3570f4deb961f3652800a6
So, now `$hasOutput` gets `true` at line 77, because now `$controllerResult` is an instance of `$outputMetadata['class']`
https://github.com/api-platform/core/blob/125dec90d05dc383e9214cd4968428323d0a1136/src/EventListener/WriteListener.php#L77
which it totally correct... but this leads to improper call of 
https://github.com/api-platform/core/blob/125dec90d05dc383e9214cd4968428323d0a1136/src/EventListener/WriteListener.php#L81

_Imho, at line 80 it's necessary to add additional check, if object in `$controllerResult` is an "ApiResource" object._
