### ISSUE TITLE
[2.4.3] Circular Reference Error for Serializer introduced in this version

### ISSUE THREAD

**Issue by asimonf** [api-platform/core#2805]
For reference, here's my framework config:

```
api_platform:
    name_converter: serializer.name_converter.metadata_aware
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Command']
    title: Whatever API
    version: 1.0.0

    swagger:
        api_keys:
            apiKey:
              name: Authorization
              type: header
```

This produces the following error:

```
!!
!!  In CheckCircularReferencesPass.php line 67:
!!                                                                                 
!!    Circular reference detected for service "serializer.name_converter.metadata  
!!    _aware", path: "serializer.name_converter.metadata_aware -> serializer.name  
!!    _converter.metadata_aware".                                                  
!!                                                                                 
!!
!!
```

Downgrading to 2.4.2 fixed it.
