### ISSUE TITLE
No item route associated with type when using messenger and output false

### ISSUE THREAD

**Issue by raresserban** [api-platform/core#2823]
I have the following YAML configuration as per the docs:
```
WhateverClass:
        collectionOperations:
            post:
                status: 202
        itemOperations: []
        attributes:
            messenger: true
            output: false
```

This worked in Api Platform 2.4.2 fine, but does no longer work in Api Platform 2.4.3, generating the title error, even though the `output` is set to false.

This is exactly like the documentation mentions but does not work correctly:
https://api-platform.com/docs/core/messenger/
