### ISSUE TITLE
Custom controller fires before validation? v2.3

### ISSUE THREAD

**Issue by shadz3rg** [api-platform/core#2842]
Custom operation:

```
register_phone:
  path: '/account/register_phone'
  method: 'POST'
  controller: 'App\Controller\Api\AccountCreateController'
  validation_groups: ['step_2_register_phone']
```

Custom controller:
```
<?php

namespace App\Controller\Api;

use App\Components\Provider\Account\Bridge;
use App\Components\Provider\Account\AccountWizard;

class AccountCreateController
{
    private $bridge;

    public function __construct(Bridge $bridge)
    {
        $this->bridge = $bridge;
    }

    public function __invoke(AccountWizard $data): AccountWizard
    {
        var_dump('Action fires for invalid entity.');
        //$this->bridge->register($data):
        return $data;
    }
}
```

Response:
```
string(32) "Action fires for invalid entity."
{"@context":"\/api\/contexts\/ConstraintViolationList","@type":"ConstraintViolationList","hydra:title":"An error occurred","hydra:description":"agreement_personal_data_store: Must be true.","violations":[{"propertyPath":"agreement_personal_data_store","message":"Must be true."}]}
```

Am i using custom controllers incorrectly or there is a way to know validation result before executing action code?
