### ISSUE TITLE
ExistFilter not working for SubResource

### ISSUE THREAD

**Issue by peter-gemvision** [api-platform/core#2871]
I have a resource that has the `ExistsFilter` on it. This works fine on the resource itself. However when I have a sub resource it does not work. The swagger documentation does show the query parameters so that part looks to be working. Applying of the actual filter does not get executed. So if i have a resource with the field `foo` and i use `?foo[exists]=true` it will not filter when applying this to a subresource. 

As a example:
`/resource1?foo[exists]=true` <- works file
`/resource2/1/resource1?foo[exists]=true` <- does not work.

I have not been able to see find out why this is happening but i do know that the `filterProperty` function in the `ExistsFilter` class is never called. 

I looks like it might be a filter wide problem. Sorting also does not seem to work even tho the documentation is shown on the SubResouce in swagger.

**Comment by SebCargo** [comment]
I have the same problem. Not sure how to expose filters on subresources

**Comment by SebCargo** [comment]
Just found a solution:

If you use annotation it's working fine.

With Yaml:

This doesn't work with subresources:

```yaml
  Project\Entity\MySubResource:
    collectionOperations:
      get:
        method: GET
        filters: [...]
```

This is working:
```yaml
  Project\Entity\MySubResource:
    attributes:
      filters: [...]
    collectionOperations:
```
