### ISSUE TITLE
Pagination in custom data provider (without doctrine or ES) 

### ISSUE THREAD

**Issue by kpn13** [api-platform/core#2903]
Hi,

I have a custom data provider which call an API for providing data. Is there a builtin solution to use pagination, filter, etc for my array of results or do I have to make my own PaginatorInterface implementation ?

**Comment by mumy81** [comment]
You can use built-in extensions; filter, pagination e.t.c built-in solutions are extensions indeed.  

I have implemented like that: 

In services.yaml: you should register your custom data provider, you should notice that arguments, collectionExtensions are tagged with 'api_platform.doctrine.orm.query_extension.collection'.
  ```
  App\DataProvider\CollectionDataProvider:
        tags: [{ name: 'api_platform.collection_data_provider' }]
        arguments:
            $collectionExtensions: !tagged api_platform.doctrine.orm.query_extension.collection
        # Autoconfiguration must be disabled to set a custom priority
        autoconfigure: false
```
My Custom Collection Data Provider implements the below Interfaces, these built-in interfaces are used in original built in data providier.
```
use ApiPlatform\Core\DataProvider\CollectionDataProviderInterface;
use ApiPlatform\Core\DataProvider\RestrictedDataProviderInterface;
use Doctrine\Common\Persistence\ManagerRegistry;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGenerator;

final class CollectionDataProvider implements CollectionDataProviderInterface, RestrictedDataProviderInterface
{
    private $collectionExtensions;
    private $managerRegistry;
    private $excludedResources;

    public function __construct(ManagerRegistry $managerRegistry, /* iterable */ $collectionExtensions = [])
    {
        $this->collectionExtensions = $collectionExtensions;
        $this->managerRegistry = $managerRegistry;
    }
```

The getCollection method is the main method at here: It takes 3 parameters like at below:
Here you walk through all of the built-in extensions by applying current collection into them. Extensions apply their logic to queryBuilder so queryBuilder changes by extensions. End of loop, the queryBuilder contains conditions to provide filters, pagination etc.

   ```
 public function getCollection(string $resourceClass, string $operationName = null, array $context = [])
    {
        $manager = $this->managerRegistry->getManagerForClass($resourceClass);
        $repository = $manager->getRepository($resourceClass);
        $queryBuilder = $repository->createQueryBuilder('e');
        $queryNameGenerator = new QueryNameGenerator();

        foreach ($this->collectionExtensions as $extension) {

            $extension->applyToCollection($queryBuilder, $queryNameGenerator, $resourceClass, $operationName, $context);

            if ($extension instanceof QueryResultCollectionExtensionInterface && $extension->supportsResult($resourceClass, $operationName, $context)) {
                return $extension->getResult($queryBuilder, $resourceClass, $operationName, $context);
            }
        }

return $queryBuilder->getQuery()->getResult();
}
```
