### ISSUE TITLE
Allow to use custom route path prefix for resource

### ISSUE THREAD

**Issue by Strate** [api-platform/core#291]
Nowadays, if i have resource for entity "SomeName", matched url looks like "some_name". And there is only one way to change this: overriding whole set of resource operations. I suggest to add ability to pass custom route prefix directly from service tag:

```
services:
  resource.some_name:
    # rest of definition goes here
    tags:
      - { name: api.resource, pathPrefix: "/SomeName" }
```

**Comment by ogizanagi** [comment]
Well, should be pretty easy to do in the `ApiLoader`, but it's actually already doable by cheating and using the Resource `shortName` https://github.com/dunglas/DunglasApiBundle/blob/master/Api/Resource.php#L372-L375
```yaml
services:
  resource.some_name:
    # rest of definition goes here
    initShortName: 'somePrefix/someName'
    tags:
      - { name: api.resource, pathPrefix: "/SomeName" }
```

A cleaner way to do this might be good however.

**Comment by yelmontaser** [comment]
```yml
services:
  resource.some_name:
    # rest of definition goes here
    tags:
      - { name: api.resource }
    calls:
        - [ initShortName, [ somePrefix/someName ] ]

```

**Comment by ogizanagi** [comment]
Absolutely... sorry for the wrong example :)

**Comment by soyuka** [comment]
Jumping on this with a related issue (or maybe I've a bad use of the compiler pass, seems the way of doing it).

I've a `CompilerPass` that changes the name of every resources. It appends the name of the bundle to avoid resources conflicts:

```
class ResourceShortNamePass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container) {
        foreach($container->findTaggedServiceIds('api.resource') as $serviceId => $tags)  {
            $definition = $container->getDefinition($serviceId);
            $entityClass = $definition->getArguments()[0];

            $parts = explode('\\', $entityClass);
            if($parts[1] !== 'ISOBundle') {
                $definition->addMethodCall('initShortName', [str_ireplace('bundle', '', $parts[1]) . $parts[count($parts) - 1]]);
            }
        }
    }
}
``` 

Now this works great for basic resources but when I add a custom one everything's broken. The following example adds a route on the ProductProduct resource (`shortName` has a `BundleEntity` form):

```
#excerpt
    resource.product.collection_operation.get:
        class: 'Dunglas\ApiBundle\Api\Operation\Operation'
        public: false
        factory: [ '@api.operation_factory', 'createCollectionOperation' ]
        arguments: [ '@resource.product', 'GET']
    resource.product.collection_operation.post:
        class: 'Dunglas\ApiBundle\Api\Operation\Operation'
        public: false
        factory: [ '@api.operation_factory', 'createCollectionOperation' ]
        arguments: [ '@resource.product', 'POST']
    resource.product.collection_operation.search_get:
        class: 'Dunglas\ApiBundle\Api\Operation\Operation'
        public: false
        factory: [ '@api.operation_factory', 'createCollectionOperation' ]
        arguments: 
            - '@resource.product' #here is the issue
            - ['GET']
            - '/product_products/search' #route
            - 'product.action.search' #controller
            - 'api_product_products_get_search_collection' #route name
            - '@type': 'hydra:Operation'
              'hydra:title': 'Search operation'
    resource.product:
        parent: 'api.resource'
        arguments: [ 'Product\ProductBundle\Entity\Product' ]
        calls:
            - method: 'initCollectionOperations'
              arguments: [ [ '@resource.product.collection_operation.get','@resource.product.collection_operation.post', '@resource.product.collection_operation.search_get' ] ]
            - method: 'initFilters'
              arguments: [ ['@resource.product.search_filter', '@product.filter.search'] ]
            - method: 'initNormalizationContext'
              arguments: [ {groups: ["default"]} ]
            - method: 'initDenormalizationContext'
              arguments: [ {groups: ["default", "post"]} ]
        tags: [ { name: 'api.resource'} ]
```

Note that when declaring such a custom route, we inject `@resource.product` inside the operation. This one does not go through my CompilerPass and so, the `shortName` is still `Product` (from the operation point of view). Obviously, when I then request `/api/products_product/search`, route matches but it won't find my Resource (which shortname is in fact `ProductProduct`).

Could anyone enlight me about this?
