### ISSUE TITLE
[Elasticsearch] Allow shared prefix for mappings (index names)

### ISSUE THREAD

**Issue by ro0NL** [api-platform/core#2945]
To have an index per environment, im currently using the following config:

```yaml
parameters:
    api_projections.prefix: 'api_%kernel.environment%-'

api_platform:
    elasticsearch:
        hosts: ['%env(ELASTICSEARCH_HOST)%']
        mapping:
            App\Api\Projection\UserProjection: { index: '%api_projections.prefix%user' }
```

Except for the prefix, my mapping follows standard conventions, but currently im forced to list all mappings because of it.

What about the possibility to configure a shared prefix:

```yaml
api_platform:
    elasticsearch:
        hosts: ['%env(ELASTICSEARCH_HOST)%']
        index_prefix: 'api_%kernel.environment%-'
```
