### ISSUE TITLE
Best way to use a data provider on a custom operation ? 

### ISSUE THREAD

**Issue by Loooooouuuuu** [api-platform/core#2979]
Hello ! 

I'm trying to create a custom subresource (Let's say /users/{id}/test, which would return a collection of "Test" entities). 

There is no direct relation between User and Test in my database.

I wrote a data provider and I wanted to create a subresource: 

```
App\Entity\User:        
    ....
      properties:
            test:
                subresource:
                    resourceClass: 'App\Entity\Test'
                    collection: true
``` 
But it doesn't show up on swagger. If I create a fake "Test" property to my User entity, I'm getting an SQL error (which is normal because it doesn't exist in my database) and the "support()" function of my data provider isn't triggered.

I tried creating a custom operation: 
```
App\Entity\User:
    collectionOperations:
            ....
            get_user_test:
                route_name: 'get_user_test'

routes.yaml

get_user_test:
    path: /users/{id}/test
    controller: App\Controller\UserController::getUserTests
    methods: 'GET'
```

Which shows up on Swagger, but it's expecting a collection of Users, not a collection of Tests. So even if my data provider is triggered and sends Tests, the json is just empty arrays :/

I tried to add 
```    
defaults:
        _api_resource_class: App\Entity\Test
```
to my routes.yaml, but I'm getting an error "Notice: Undefined index: identifiers" in "/vendor/api-platform/core/src/Serializer/SerializerContextBuilder.php:76".

Any idea ? 

Thanks !

**Comment by Loooooouuuuu** [comment]
By adding 
```
        _api_subresource_context:
            collection: true
            property: 'id' 
            identifiers:
            - ['id', 'App\Entity\User', true]```

to my routes.yaml,

**Comment by Loooooouuuuu** [comment]
I think I found a solution, thanks to the Api Platform channel on Slack ! 

In my User.php : 

```
    /**
     * @var Test
     */
    private $tests;
```

In my services.yaml (in order to use filters on the subresource) : 
```
    'App\DataProvider\UserTestsProvider':
        arguments:
          $collectionExtension: !tagged api_platform.doctrine.orm.query_extension.collection
```

In my user.yaml

```
resources:
    App\Entity\User:
        ...
        properties:
            tests:
                subresource:
                    resourceClass: 'App\Entity\Test'
                    collection: true
                    identifiers:
                     - ['id', 'App\Entity\User', true]

```

Then you just need your data provider to implement "ApiPlatform\Core\DataProvider\SubresourceDataProviderInterface". I found it by poking around, I've never seen it in the documentation :/

For filters, you need to follow [this](https://api-platform.com/docs/core/data-providers/#injecting-extensions-pagination-filter-eagerloading-etc). In my example, it's a collection, so I replaced $itemExtensions by $collectionExtensions, and `->applyToItem` by `applyToCollection` (and removed the $id)

If there is a better solution, or if anybody need any more information, let me know !
