### ISSUE TITLE
Serialization of Embeddable break when api_docs is disable

### ISSUE THREAD

**Issue by gagaXD** [api-platform/core#3030]
Hi,

I have an entity using an embeddable

```php
     /**
     * @var CompanyContract
     * @Assert\NotBlank
     * @ORM\Embedded(class="App\Entity\Embeddable\CompanyContract", columnPrefix="company_")
     * @Groups({"contract:out"})
     */
    private $company;
```

The corresponding embeddable :

```php
/**
 * @ORM\Embeddable
 */
class CompanyContract
{
    /**
     * @var string
     * @Assert\NotBlank
     * @ORM\Column(type="string")
     * @Groups({"contract:out", "issue:out"})
     */
    private $name;

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }
}
```

## Dev

In my dev env, When I GET an entity, I receive :

```json
"company": {
    "@context": {
      "@vocab": "http:\/\/api.localhost\/api\/docs?_format=jsonld#",
      "hydra": "http:\/\/www.w3.org\/ns\/hydra\/core#",
      "name": "CompanyContract\/name",
    },
    "@type": "CompanyContract",
    "@id": "_:1088",
    "name": "test",
  }
```
Which is fine.

## Prod

In my prod env, I tried to disable the route `/api/docs`, so, in the file `config/packages/prod/api_platform.yaml`, I have this :

```yaml
api_platform:
  enable_swagger: false
  enable_swagger_ui: false
  enable_entrypoint: false
  enable_docs: false
```
This works fine, since I can't get to the route `/api/docs`

But, when I try to `GET` an entity with an `embeddable`, I got the following error

`Unable to generate a URL for the named route \"api_doc\" as such route does not exist`

which seems to be caused by : 

file: `api-platform/core/src/JsonLd/ContextBuilder.php`

```php
     /**
     * {@inheritdoc}
     */
    public function getBaseContext(int $referenceType = UrlGeneratorInterface::ABS_URL): array
    {
        return [
            '@vocab' => $this->urlGenerator->generate('api_doc', ['_format' => self::FORMAT], UrlGeneratorInterface::ABS_URL).'#',
            'hydra' => self::HYDRA_NS,
        ];
    }

```

Is there any way to disable the generation of the `@context`, knowing that my `embeddable` is not an `ApiRessource` ?

**Comment by gagaXD** [comment]
We've found a workaround ( not a pretty one 🤓)

in `config/routes/prod/api_platform.yml`
```yaml
api_doc:
  path: '/api/docs'
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: '/'
    permanent: true
```

We "declare" a new `api_doc` route, so that the router is able to generate an IRI even if the api_docs is disable
