### ISSUE TITLE
Question: ApiSubresource and JSON

### ISSUE THREAD

**Issue by Kolesar** [api-platform/core#3031]
I cannot find anywhere in documentation details about the issue what I have.

When I use JSON-LD I can get subresources with data what I defined in groups, but if I use (what I really need) JSON, I get only URLs as reference URLs to the subresources.

Is it a limitation in the API platform or I have to change my configuration?

I use platform with Symfony and my configuration atm is very simple:

```
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonapi:
            mime_types: ['application/json']
```
