### ISSUE TITLE
Releases 2.4.3+ break support for using the default messenger serializer with the Messenger component

### ISSUE THREAD

**Issue by asimonf** [api-platform/core#3065]
# Scenario

According to this [documentation](https://api-platform.com/docs/core/messenger/), one can use the messenger component to implement the CQRS pattern. Such classes don't have an IRI. Starting with Symfony 4.3, the default serializer was changed, but it can be [reverted](https://symfony.com/doc/current/messenger.html#serializing-messages) like so:

```yaml
framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        transports:
            async_priority_normal:
                dsn: # ...
                serializer: messenger.transport.symfony_serializer
```

When doing this, the `AbstractItemNormalizer` is used for message serialization like when using Symfony 4.2 on Api-Platform 4.2. The problem arises due to changes on commit 2bb4db1583521be72144d1da7da9cbe0b09808a2.   

# Expected Behavior

When using Symfony 4.2 with Api-Platform 2.4.2 using the above serializer, the expected behavior of implementing the CQRS pattern is that it should work as intended.

# Actual Behavior

When using Symfony 4.3 with any release after 2.4.2, the above fails when using the `messenger.transport.symfony_serializer` service for serialization.

The reason is that the normalizer expects to be able to obtain an _IRI_ from the object. This will not work because _Commands_ can't have an _IRI_. The guilty segment is this one:

```php
$iri = $context['iri'] ?? $this->iriConverter->getIriFromItem($object);
```

The above was previously guarded by the following _if_ and inside it:

```php
if (isset($context['resources'])) {
    $context['resources'][$iri] = $iri;
}
```

# How to reproduce

Implement the example in `https://api-platform.com/docs/core/messenger/` and make changes inside the file `messenger.yaml` to match the following:

```yaml
framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

# ...
```

Doing the above will result in the following error:

```
No item route associated with the type "App\Entity\ResetPasswordRequest".
```

**Comment by soyuka** [comment]
Mhh, is the ResetPasswordRequest annotated as an ApiResource ? Maybe that it should not be one and therefore not go through our normalizer?

**Comment by asimonf** [comment]
> Mhh, is the ResetPasswordRequest annotated as an ApiResource ? 

It is annotated with it as per the CQRS example: 

```
/**php
 * @ApiResource(
 *     messenger=true,
 *     collectionOperations={
 *         "post"={"status"=202}
 *     },
 *     itemOperations={},
 *     output=false
 * )
 */
```

> Maybe that it should not be one 

That would be a pretty severe breaking change, would it not?

Right now, [the pattern suggested in the docs](https://api-platform.com/docs/core/messenger/#dispatching-a-resource-through-the-message-bus) became broken with Symfony 4.3 and Api-Platform 2.4.3+ whenever the command has resources as fields. 

When a command is defined with objects in Api-Platform, the endpoint expects the IRIs for those resources. Once the endpoint data is denormalized, the objects are fetched from the database and assigned to the command object. 

The new default serializer for messages in Symfony 4.3 uses PHP's `serialize` and `unserialize`. Once a Doctrine object is unserialized at the other end of the transport, that object is no longer managed by the object manager. This is a break in behavior compared to 2.4.2. When trying to go back to the previous serializer used by Symfony in 4.2, the above happens. 

I guess one workaround could be to remerge those to the entity manager and refresh them to get the latest data from the DB, but that would mean quite a bit of boiler-plate that wasn't previously required. Moreover, going back to the regular serializer should also be possible, since the symfony  docs recommend doing that for when the edge cases break with the new serializer. 

Since this behavior change is not documented on the API docs, it's bound to frustrate several users, including me. I spent more than I care to admit debugging this thinking it was something I messed up when upgrading the dependencies.

**Comment by soyuka** [comment]
Interesting, tyvm about this input I'll definitely try to prioritize this next week (will have some time to work on these issues).

**Comment by soyuka** [comment]
Hi,

I reproduced this use case and I'm not sure to follow you in the sentence "Right now, the pattern suggested in the docs became broken with Symfony 4.3 and Api-Platform 2.4.3+ whenever the command has resources as fields." as that without any additional configuration everything works as expected. 

Composer version shows: 
```
api-platform/core                  v2.4.6  Build a fully-featured hypermedia or GraphQL API in minutes
symfony/messenger                  v4.3.4  Symfony Messenger Component
```

Messenger configuraiton:

```
framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\Entity\ResetPasswordRequest': async
```

I don't get why you would need to change the serializer especially that you should handle the doctrine-related things in your handler yourself. 
Also, note that messenger is still experimental which means it can break and we can not guarantee it's stability within Api Platform because of this.
 
> Since this behavior change is not documented on the API docs

It's still open source software and we try to follow updates as fast as they get done. Please help us to improve the documentation if you think it's missing something.

If I manage to add blank node identifiers (see https://github.com/api-platform/core/pull/2954) this will work but I still would not recommend to change the messenger serializer in this use case as I don't get the interest, especially that it'd have a negative impact in performances.
