### ISSUE TITLE
Content type

### ISSUE THREAD

**Issue by Vaxa** [api-platform/core#3078]
Updated to 2.5.0 core

The content-type \"application/json\" is not supported. Supported MIME types are \"\".

how to fix?

**Comment by TrogWarZ** [comment]
Same here, updating from `v2.4.7` to `v2.5.0` triggers this error in custom actions.

Configuration is default `symfony console debug:config api_platform`:
```yaml
api_platform:
    formats:
        jsonld:
            mime_types:
                - application/ld+json
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html
```

It has errors only in custom actions (for me) that are defined like that:

```php
<?php

namespace App\Controller;

use App\Entity\FooEntity;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class FooAction
{
    /**
     * @Route(
     *     name="api_foos_bars",
     *     path="/api/foos/{id}/bar_action",
     *     methods={"POST"},
     *     defaults={
     *         "_api_resource_class"=FooEntity::class,
     *         "_api_item_operation_name"="api_foos_bars"
     *     }
     * )
     *
     * @param FooEntity $foo
     * @param Request   $request
     *
     * @return Response
     */
    public function __invoke(FooEntity $foo, Request $request): Response
    {
        // ... nevermind ...
    }
}
```

Request looks like this:
```
POST /api/foos/42/bar_action HTTP/1.1
Accept: application/json+ld, */*
Accept-Encoding: gzip, deflate
Authorization: Bearer AUTH_JWT_TOKEN
Connection: keep-alive
Content-Length: 14
Content-Type: application/json
Host: example.com

{
    "some":"data"
}
```
