### ISSUE TITLE
Yaml subresource error

### ISSUE THREAD

**Issue by cacahouwete** [api-platform/core#3110]
| label | version |
| --- | --- |
| api-platform/core | 2.4.5 |
| php | 7.2.21 |
| symfony/* | 4.3.3 |

Hello, everybody.

I have a little problem when I configure a subresource with Yaml file configuration but if I put the same configuration in XML file it works. My files:

```yaml
App\Domain\TourBuilding\Model\AggregateRoot\Plan\Plan:
  properties:
    resources:
      subresource: { collection: true, resourceClass: 'App\Domain\TourBuilding\Model\Aggregate\Resource\Resource' }
```
```xml
<?xml version="1.0" ?>

<resources xmlns="https://api-platform.com/schema/metadata"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://api-platform.com/schema/metadata
           https://api-platform.com/schema/metadata/metadata-2.0.xsd">
    <resource
            class="App\Domain\TourBuilding\Model\AggregateRoot\Plan\Plan"
    >
        <property name="resources">
            <subresource collection="true" resourceClass="App\Domain\TourBuilding\Model\Aggregate\Resource\Resource" />
        </property>
    </resource>
</resources>
```

The error:
```shell
In SubresourceMetadata.php line 27:
                                                                               
  Argument 1 passed to ApiPlatform\Core\Metadata\Property\SubresourceMetadata  
  ::__construct() must be of the type string, null given, called in /app/vend  
  or/api-platform/core/src/Metadata/Property/Factory/ExtractorPropertyMetadat  
  aFactory.php on line 150                                                     
```
