### ISSUE TITLE
Nested objects are not returned in the GraphQL mutation response

### ISSUE THREAD

**Issue by neverdane** [api-platform/core#3119]
I'm unable to get the objects related to the entity I just created with `api-platform/core@v2.2.7`. 

Here is a simple example of my problem:

```
mutation createCard {
  createCard(
    input: {
      sentence: "Sentence"
      labels: ["/labels/3"]
      clientMutationId: "randomId"
    }
  ) {
    id
    labels {
      edges {
        node {
          id
        }
      }
    }
  }
}
```

Below is the result I get with GraphiQL:

```
{
  "data": {
    "createCard": {
      "id": "/cards/138",
      "labels": {
        "edges": null
      }
    }
  }
}
```

Here is the result I expected, which is also the result I get when I query my Card with its `id` immediately after my mutation:

```
{
  "data": {
    "card": {
      "id": "/cards/138",
      "labels": {
        "edges": [
          {
            "node": {
              "id": "/labels/3"
            }
          }
        ]
      }
    }
  }
}
```

Did I do something wrong?

Thanks for your help

**Comment by dpfaffenbauer** [comment]
BTW, this also happens when I change the Summary Resource to have a output class, like:

doesn't work:

```yml
ViewModel\Cart\CartSummaryView:
        shortName: 'CartSummary'
        collectionOperations: []
        subresourceOperations:
            items_get_subresource:
                  method: get
                  path: '/cart/{id}/items'
                  access_control: 'is_granted("api_cart_item", object)'
                  security_message: 'Sorry, but you are not the cart owner'
        itemOperations:
            get:
                path: '/cart/{id}'
                requirements:
                    id: '\d+'
                normalization_context:
                    groups: ['cart_summary:item:get']
                access_control: 'is_granted("api_cart", object)'
        graphql:
            item_query:
                pagination_enabled: false
        attributes:
            output: ViewModel\Cart\CartSummaryView
```

works:

```yml
ViewModel\Cart\CartSummaryView:
        shortName: 'CartSummary'
        collectionOperations: []
        subresourceOperations:
            items_get_subresource:
                  method: get
                  path: '/cart/{id}/items'
                  access_control: 'is_granted("api_cart_item", object)'
                  security_message: 'Sorry, but you are not the cart owner'
        itemOperations:
            get:
                path: '/cart/{id}'
                requirements:
                    id: '\d+'
                normalization_context:
                    groups: ['cart_summary:item:get']
                access_control: 'is_granted("api_cart", object)'
        graphql:
            item_query:
                pagination_enabled: false
```
