### ISSUE TITLE
Normalization context

### ISSUE THREAD

**Issue by yelmontaser** [api-platform/core#316]
Hi,
Currently the API Bundle lets you specify a group serialization through the service of a resource.

```yml
services:
    resource.person:
        parent:     api.resource
        tags:       [ { name: api.resource } ]
        arguments:  [ AppBundle\Entity\Person ]
        calls:
            - [ initNormalizationContext, [ { groups: [ list ] } ] ]
```

The problem is that the method ```initNormalizationContext``` is applied to all operations on items and collections.

If for example in a person list, we need to display only the givenName and familyName, we apply the ```list``` group. yet in the person detail page we need more informations: birhtDate, telephone etc. and we want to add the ```detail``` group.

```php
namespace AppBundle\Entity;

use ...

/**
 * A person (alive, dead, undead, or fictional).
 * 
 * @see http://schema.org/Person Documentation on Schema.org
 * 
 * @ORM\MappedSuperclass
 * @Iri("http://schema.org/Person")
 */
abstract class Person extends Thing
{
    /**
     * @var string Family name. In the U.S., the last name of an Person. This can be used along with givenName instead of the name property.
     * ...
     * @Groups({"list", "detail"})
     */
    private $familyName;

    /**
     * @var string Given name. In the U.S., the first name of a Person. This can be used along with familyName instead of the name property.
     * ...
     * @Groups({"list", "detail"})
     */
    private $givenName;

    /**
     * @var \DateTime Date of birth.
     * ...
     * @Groups({"detail"})
     */
    private $birthDate;

    /**
     * @var string The telephone number.
     * ...
     * @Groups({"detail"})
     */
    private $telephone
```
I see 2 solutions: 

##### 1. Use the ```api.retrieve``` event 

```php
<?php
namespace AppBundle\EventListener;

use Dunglas\ApiBundle\Event\DataEvent;

class MyEventListener
{
    /**
     * @param DataEvent $dataEvent
     */
    public function onRetrieve(DataEvent $dataEvent)
    {
        $resource = $dataEvent->getResource();

        $resource->initNormalizationContext(array_merge(
            $resource->getNormalizationGroups(),
            ['detail']
        ));
    }
```
Define the service:
```yml
services:
    my_event_listener:
        class: "AppBundle\EventListener\MyEventListener"
        tags:  [ { name: kernel.event_listener, event: api.retrieve, method: onPostCreate } ]
```
##### 2. Use ```initItemOperations``` and override ```item_operation.get``` via a controller:

```php
<?php
namespace AppBundle\Controller;

use Dunglas\ApiBundle\Controller\ResourceController;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class OperationController
 * @package AppBundle\Controller
 */
class CustomController extends ResourceController
{
    /**
     * @param Request $request
     * @param int $id
     *
     * @return \Dunglas\ApiBundle\JsonLd\Response
     */
    public function getAction(Request $request, $id)
    {
        $resource = $this->getResource($request);

        $resource->initNormalizationContext(array_merge(
            $resource->getNormalizationGroups(),
            ['detail']
        ));

        return parent::getAction($request, $id);
    }
}
```
Define the service:

```yml
services:
    resource.person:
        parent:     api.resource
        tags:       [ { name: api.resource } ]
        arguments:  [ AppBundle\Entity\Person ]
        calls:
            - [ initNormalizationContext, [ { groups: [ list ] } ] ]
            - [ initItemOperations, [ [ @resource.person.item_operation.get ] ] ]

    resource.person.item_operation.get:
        public: false
        class: Dunglas\ApiBundle\Api\Operation\Operation
        factory: [ @api.operation_factory, createItemOperation ]
        arguments: [ @resource.person, [ GET ], null, AppBundle:Custom:get ]
```

Both solutions works, but it's an assault course for add a simple serialization group.

**Comment by yelmontaser** [comment]
I propose to add ```cget``` or ```collection``` and ```get``` or ```item``` to the array expected by ```initNormalizationContext```.

eg:
```yml
services:
    resource.person:
        parent:     api.resource
        tags:       [ { name: api.resource } ]
        arguments:  [ AppBundle\Entity\Person ]
        calls:
            -
                - initNormalizationContext
                - [ { groups: { cget: [ list ], get: [ list, detail ] } } ]
            # OR
            -
                - initNormalizationContext
                - [ { groups: { collection: [ list ], item: [ list, detail ] } } ]
```
what do you think?

**Comment by dunglas** [comment]
This problem is being solved in the 2.0 version (but it's not finished yet): all details such as the serialization context will be stored by operations instead of globally. This makes more sense in all case.

For 1.0, a workaround can be to use a custom Normalizer using hardcoded groups.

**Comment by yelmontaser** [comment]
I agree, have more sense that the operations manages the serialization context. How can i see  the progress to contribute?

**Comment by yelmontaser** [comment]
3rd solution custom normalizer suggested by @dunglas : 

```yml
api.serializer.normalizer.item:
    public: false
    class: AppBundle\Serializer\CustomItemNormalizer
    parent: api.json_ld.normalizer.item
    tags: [ { name: serializer.normalizer } ]
```

```php
<?php
namespace AppBundle\Serializer;

use Dunglas\ApiBundle\JsonLd\Serializer\ItemNormalizer;

/**
 * Class CustomItemNormalizer
 * @package AppBundle\Serializer
 */
class CustomItemNormalizer extends ItemNormalizer
{
    /**
     * @inheritdoc
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $resource = $this->guessResource($object, $context, true);

        $resource->initNormalizationContext(array_merge(
            $resource->getNormalizationGroups(),
            ['detail']
        ));

        return parent::normalize($object, $format, $context);
    }
}
```

**Comment by yelmontaser** [comment]
Maybe the advantage of using a controller is that you can easily modify the serialization context into take account the authorizations ```$this->isGranted()```


```php
$resource = $this->getResource($request);
$object = $this->findOrThrowNotFound($resource, $id);

if ($this->isGranted('read', $object)) {
    $resource->initNormalizationContext(array_merge(
        $resource->getNormalizationGroups(),
        ['user_read']
    ));
}
```

what do you think?

**Comment by dunglas** [comment]
I recommend you use composition instead of extension, it will help you when you will need to other normalizers to tweak the output format:

```php
namespace AppBundle\Serializer;

use Symfony\Component\Serializer\NormalizerInterface;
use Symfony\Component\Serializer\DenormalizerInterface

class CustomItemNormalizer implements NormalizerInterface, DenormalizerInterface
{
    private $normalizer;

    public function __construct(NormalizerInterface $normalizer)
    {
        if (!$normalizer instanceof DenormalizerInterface) {
            throw new \InvalidArgumentException('The normalizer must implement the DenormalizerInterface');
        }

        $this->normalizer = $normalizer;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $resource = $this->guessResource($object, $context, true);

        $resource->initNormalizationContext(array_merge(
            $resource->getNormalizationGroups(),
            ['detail']
        ));

        return parent::normalize($object, $format, $context);
    }

    public supportsNormalization($data, $format = null)
    {
        return $this->normalizer->supportsNormalization($data, $format);
    }

    public function denormalize($data, $class, $format = null, array $context = array())
    {
        return $this->normalizer->denormalize($data, $class, $format, array $context);
    }

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $this->normalizer->supportsDenormalization($data, $type, $format);
    }
}
```

**Comment by yelmontaser** [comment]
Thank you @dunglas

**Comment by yelmontaser** [comment]
Here are the full working example:

Define the service:
```yml
api.serializer.normalizer.item:
    public: false
    class: AppBundle\Serializer\CustomItemNormalizer
    arguments: [ @api.json_ld.normalizer.item ]
    tags: [ { name: serializer.normalizer } ]
```

The custom normalizer:

```php
namespace AppBundle\Serializer;

use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

/**
 * Class CustomItemNormalizer
 * @package AppBundle\Serializer
 */
class CustomItemNormalizer implements NormalizerInterface, DenormalizerInterface
{
    /**
     * @var NormalizerInterface
     */
    private $normalizer;

    /**
     * CustomItemNormalizer constructor.
     *
     * @param $normalizer
     */
    public function __construct(NormalizerInterface $normalizer)
    {
        if (!$normalizer instanceof DenormalizerInterface) {
            throw new \InvalidArgumentException('The normalizer must implement the DenormalizerInterface');
        }

        $this->normalizer = $normalizer;
    }

    /**
     * {@inheritdoc}
     */
    public function denormalize($data, $class, $format = null, array $context = array())
    {
        return $this->normalizer->denormalize($data, $class, $format, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function supportsDenormalization($data, $type, $format = null)
    {
        return $this->normalizer->supportsDenormalization($data, $type, $format);
    }

    /**
     * {@inheritdoc}
     */
    public function normalize($object, $format = null, array $context = array())
    {

        $resource = $this->normalizer->guessResource($object, $context, true);

        $resource->initNormalizationContext(array('groups' => array_merge(
            $resource->getNormalizationGroups(),
            ['detail']
        )));

        return $this->normalizer->normalize($object, $format, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function supportsNormalization($data, $format = null)
    {
        return $this->normalizer->supportsNormalization($data, $format);
    }
}
```
