### ISSUE TITLE
Defining Filters in XML

### ISSUE THREAD

**Issue by gomcodoctor** [api-platform/core#3185]
```<?xml version="1.0" encoding="UTF-8" ?>
<resources xmlns="https://api-platform.com/schema/metadata"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://api-platform.com/schema/metadata
           https://api-platform.com/schema/metadata/metadata-2.0.xsd">
    <resource class="App\Entity\Order" description="My Offer" shortName="Orders">
        <attribute name="route_prefix">/libra</attribute>
        <collectionOperations>
            <collectionOperation name="get">
                <attribute name="filters">
                    <attribute>api_platform.doctrine.orm.date_filter</attribute>
                </attribute>
            </collectionOperation>
        </collectionOperations>
    </resource>
</resources>```

I am using above xml to define filter, but its not working.. whats correct process?

**Comment by soyuka** [comment]
https://api-platform.com/docs/core/filters/#filters

**Comment by gomcodoctor** [comment]
I tried using that only , I am using api_platform.doctrine.orm.date_filter instead of offer.date_filter as shown in example, but its not shown in 
![image](https://user-images.githubusercontent.com/10648299/67077821-a916f100-f1ad-11e9-8938-768de835310f.png)

**Comment by soyuka** [comment]
you can't use our service directly, you need to have your own that specifies properties to filter on:

```
# api/config/services.yaml
services:
    # ...
    offer.date_filter:
        parent: 'api_platform.doctrine.orm.date_filter' # here the reference to our filter
        arguments: [ { dateProperty: ~ } ] # See here
        tags:  [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined
        # You may want to isolate filters in a dedicated file to avoid adding them
        autowire: false
        autoconfigure: false
        public: false
```

You can also use filter annotations to ease the setup.
