### ISSUE TITLE
Batch resources update by POST request and filters GET paramters

### ISSUE THREAD

**Issue by alebedev80** [api-platform/core#3222]
I need to implement batch update of > 1 resources of one Entity which should be filtered in the same way as list of resources by the filter parameters.

`
`

**Comment by norkunas** [comment]
You could create a custom controller injecting the collection extensions iterator, apply them to your query builder, then get the matched results and after that update your entities and flush.

**Comment by alebedev80** [comment]
@norkunas thank you! 

after three hours of investigation stackoverflow (especially this one post https://stackoverflow.com/questions/55020369/filter-required-in-api-platform/58460863#58460863) i've implemented solution. But only per GET operation (GET /sms/ops/batch_cancel?[filters]) because POST method using deserialization and validation.  

How to set-up api platform to process POST request to collection  as GET?

**Comment by alebedev80** [comment]
Found solution. Added read: false and output: false. And added exception by route name prefix to the custom deseriazers listeners.

```
    sms_ops_cancel:
      route_name: sms_batch_post_cancel
      filters: ['sms.search_filter']
      read: false
      output: false
```

```
        if(strpos($route, 'sms_batch') === 0) {
            return;
        }
```
