### ISSUE TITLE
Add a way to define the type of a property at resource level

### ISSUE THREAD

**Issue by julienfalque** [api-platform/core#3254]
When deserializing a request body into a resource object, API Platform currently resolves each property type using Doctrine mappings or PHPDoc tags. Though, as far as I know, there is no way to define a type explicitly in the API resource mapping itself.

This would allow separating the type declaration from the actual object API Platform will provide, e.g.:
```php
class Dto {
    /** @var FooInterface */
    public $foo;
}
```
```yaml
resources:
    Dto:
        properties:
            foo:
                type: FooImplementation
```
