### ISSUE TITLE
[GraphQL] Embedded resources does not work for mutations

### ISSUE THREAD

**Issue by Fgruntjes** [api-platform/core#3258]
**API Platform version(s) affected**: 2.5.1

**Description**  
When resources are defined in yaml instead of Doctrine GraphQL will not show them as embedded resources for mutations.

The schema definition
```yaml
App\Entity\Book:
    collectionOperations: ~
    itemOperations: ~
    attributes:
        normalization_context:
            groups: ['Book']
        denormalization_context:
            groups: ['Book']
    properties:
        id:
            readonly: true
        title:
            required: true
        pages:
            subresource:
                resourceClass: 'App\Entity\Page'
                collection: true

App\Entity\Page:
    collectionOperations: ['get']
    itemOperations: ['get']
    attributes:
        normalization_context:
            groups: ['Book']
        denormalization_context:
            groups: ['Book']
    properties:
        id:
            readonly: true
        content:
            required: true
```

And serialization config
```yaml
App\Entity\Book:
    attributes:
        id:
            groups: ['Book']
        title:
            groups: ['Book']
        pages:
            groups: ['Book']

App\Entity\Page:
    attributes:
        id:
            groups: ['Book']
        content:
            groups: ['Book']
```

Will create the following `createBookInput` object in graphql
![image](https://user-images.githubusercontent.com/984466/68872290-16129d80-06fe-11ea-9de9-6ab80904464d.png)

**How to reproduce**  
- Checkout the project https://github.com/Fgruntjes/api-platform-graphql-issue
- composer install
- Open GraphiQl viewer

**Additional Context**  
Similar to these issues but @alanpoulain suggested that they are likely not the same.
- https://github.com/api-platform/api-platform/issues/836
- https://github.com/api-platform/api-platform/issues/1043
