### ISSUE TITLE
Autowire input DTO model

### ISSUE THREAD

**Issue by ro0NL** [api-platform/core#3268]
Given i have a API resource like

```yaml
input: Vendor\InputDto
controller: Vendor\EntityController:someAction
```

We could autowire the controller action like

```php
public function someAction(Request $request, Entity $data, InputDto $input): Entity
{
    $data->richness($input->value, $this->service->getValue());

    return $data;
}
```

Related to #3261, assuming `$input` is de-serialized and validated.

**Comment by julienfalque** [comment]
Isn't this already supported by Symfony (with `sensio/framework-extra-bundle`)? Though `$data` is always the deserialized payload of the request, so you would rather have
```php
public function someAction(Request $request, Entity $entity, InputDto $data): Entity
{
    $data->richness($input->value, $this->service->getValue());

    return $data;
}
```
Maybe related: #3263

**Comment by ro0NL** [comment]
This is a real life example:

```yaml
App\Entity\Stock:
    itemOperations:
        get: ~
        transfer:
            method: POST
            path: /stock/{id}/transfer.{_format}
            controller: App\Controller\StockController:transferAction
            input: App\Model\Dto\StockTransfer
```

indeed, i've currently implemented a ParamConverter to get me the input:

```php
/**
 * @ParamConverter("transfer", options={"api_input_dto"=true})
 */
public function transferAction(Request $request, Stock $data, StockTransfer $transfer)
```
