### ISSUE TITLE
Normalize accept header parameters

### ISSUE THREAD

**Issue by ro0NL** [api-platform/core#3337]
Given

```
api_platform:
    formats:
        json:
            - application/json
```

and a request with `Accept: application/json;key=value`, i get

```
Requested format "application/json;key=val" is not supported.
Supported MIME types are "application/json".
```

It feels like a bug, as it forces me to configure each possible mimetype variant, whereas all are `application/json` really.
