### ISSUE TITLE
PUT/POST nested entities (relations) without modifying them

### ISSUE THREAD

**Issue by akomm** [api-platform/core#334]
Assume following uni-directional relation:

Product > many-to-many > Additive

Product has visibility on Additive via "additives"-property.

Endpoint additives: /additives/*
Endpoint products: /products/*

1. I want to modify the relation between Additive and Product via /products/* - endpoint (additives property of product).
2. I do not want to modify Additive data via /products/* endpoint
3. I do not want to create new additives via /products/* endpoint
4. I want to embed Additives::number when fetching from /products/* (both collection & item)

I know how to archive each of the above points. But the problem is when having it all together.
At least I do not find any clue in the documentation, how to manage it, if there is any way.

The issue is, that on an API you want to be able to GET a resource, make modification and PUT it back for example. 

- Now if you make both denormalization and normalization equal, you break 2. & 3. because when you embed it, you would also be able to write it back or even create new additives, providing the validation succeed.

- When i use a normalization group which includes the Additive::number, but a denormalization group, which equals, except Additive::number property it also does not work, because in that case a plain IRI-collection is expected. But when you fetch embedded data, you have something like that:
```json
[{"@id": "IRI_1", "more": "more"}, {"@id": "IRI_2", "more": "more"}]
```
And this is expected:
```json
["IRI_1", "IRI_2"]
```
This breaks the concept of GET & PUT back.

An alternative would be to create a /products/{id}/additives resource, but currently its an issue-driven way, because its not backed by the "Bundle" and certain things get fiddly.

**Comment by akomm** [comment]
Very interessting. I'v actually found a way now. Maybe it can be added to the documentation:

Basic example:

```yaml
Additive:
   attributes:
      @id:
         groups: [ 'product.write' ]
      number:
         groups: [ 'product.read' ]
```

```yaml
Product:
   attributes:
      title:
         groups: [ "product.read", "product.write" ]
      additives:
         groups: [ "product.read", "product.write"  ]
```

```yaml
   resource.product:
      parent: "api.resource"
      arguments: [ Product ]
      calls:
         -  method: "initNormalizationContext"
            arguments: [ { groups: [ "product.read" ] } ]

         -  method: "initDenormalizationContext"
            arguments: [ { groups: [ "product.write" ] } ]

      tags: [ { name: "api.resource" } ]
```
