### ISSUE TITLE
Use setup-php action in ci for GA

### ISSUE THREAD

**Issue by Smolevich** [api-platform/core#3347]
**Description**  
Use [shivammathur/setup-php@v1](https://github.com/shivammathur/setup-php) for setup php

**Example**  
```
uses: shivammathur/setup-php@v1
with:
  php-version: '7.4'
  tools: php-cs-fixer, phpunit
```
