### ISSUE TITLE
Embeddables require an identifier

### ISSUE THREAD

**Issue by jannes-io** [api-platform/core#3370]
**API Platform version(s) affected**: ^2.1

**Description**  
Doctrine embeddables require a scalar identifier for api-platform to recognize them. This makes no sense since the fields are placed directly into the parent's table.

**How to reproduce**  
ORM:
```
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping">
    <embeddable name="App\Component\Core\Model\DateRange">
        <field name="from" type="date"/>
        <field name="to" type="date"/>
    </embeddable>
</doctrine-mapping>
```
api-platform:
```
resources:
  App\Component\Core\Model\DateRange:
    attributes:
      denormalization_context:
        groups: ['date_range']
    collectionOperations:
      get:
        normalization_context:
          groups: ['date_range']
    itemOperations:
      get:
        normalization_context:
          groups: ['date_range']
```

Then create some entity that uses the embed.
```
<embedded name="visible" class="DateRange"/>
<embedded name="register" class="DateRange"/>
<embedded name="process" class="DateRange"/>
```

Now I can add a field "$id: int" with  just default value `0` and not assign it to any normalization group but this pollutes the table so it's not a viable workaround.

**Possible Solution**  
Remove the requirement for an id on sub-entities, since a sub-entity is not always a relationship.

**Additional Context**
