### ISSUE TITLE
Example values not rendered for non-resource objects related to Resource in Swagger UI

### ISSUE THREAD

**Issue by fgamess** [api-platform/core#3385]
**API Platform version(s) affected**: 2.5.4/2.5.x-dev

**Description**  
When [Using Objects As Relations Inside Resources](https://api-platform.com/docs/core/dto/#using-objects-as-relations-inside-resources) which means the object is not a resource, we have indeed the doc generated for those objects but the **examples** values set in the **properties** of the **Resource** are not rendered. We can see **string** as the value for all the fields of the **non-resource object**. When configuring the object as a **resource** then this does not happen. 

**How to reproduce**  

```yaml
# my_resource.yaml

App\Entity\MyResource:
    properties:
        id:
            identifier: true
            attributes:
                openapi_context:
                    type: string
                    format: uuid
                    example: b5b2843dbd9f396d9307197e20999dba
        myNonResource:
            readableLink: true # whatever value I put here, it does not matter
            attributes:
                openapi_context:
                    type: object
                    properties:
                        foo:
                            type: string
                            example: example string
                        bar:
                            type: string
                            format: date-time
                            example: 2020-02-11T12:39:25+00:00
                        baz:
                            type: string
                            format: email
                            example: fake@mail.com
```

The resource entity class:

```php
<?php

namespace App\Entity;

/**
 * @ORM\Entity
 */
class MyResource
{
    private $id;
 
    private $myNonResource;

// getters and setters

}
```
The non-resource class:

```php
<?php

namespace App\Entity;

/**
 * @ORM\Entity
 */
class MyNonResource
{
    private $foo;
 
    private $bar;

    private $baz;

// getters and setters

}

```

then the generated schemas in the Swagger UI documentation below:

```

id | string($uuid)
      example: b5b2843dbd9f396d9307197e20999dba
      readOnly: true
myNonResource | MyNonResource 
        {
            foo* string
            bar* string
            baz* string
        }
```

**Possible Solution**  
- Support the creation of Swagger custom [components](https://swagger.io/docs/specification/components/). It could eventually override the **generated** schemas for the ** non-resource object** in the Swagger UI. Declaring Swagger components is not possible currently, a question about this is already discussed https://stackoverflow.com/questions/52877461/how-to-use-ref-reference-and-declare-components-from-swagger-in-api-platform
- Fill the **example values** in the **generated** schemas for the ** non-resource object** with the examples from the properties of the **Resource**. If I have a **resource MyResource** related to a **non-resource MyNonResource** it should be possible to describe the properties of **MyResource** with examples, including the **myNonResource** property and then see all the example values displayed in both **MyResource** and **MyNonResource** schemas. Also, the schemas generated for the serialization groups

**Additional Context**
