### ISSUE TITLE
Support stale-while-revalidate and stale-if-error cache-control extensions

### ISSUE THREAD

**Issue by akira28** [api-platform/core#3421]
**Description**  
At the moment neither stale-while-revalidate nor stale-if-error are supported natively by Api Platform HTTP cache system. These extensions are described in [this RFC](https://tools.ietf.org/html/rfc5861) and supported in Symfony through [SensioFrameworkExtraBundle](https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/cache.html)

**Example**  
Using this configuration:
```
api_platform:
    http_cache:
        max_age: 0
        shared_max_age: 3600
        stale_while_revalidate: 15
        stale_if_error: 30
``` 
or using the cacheHeaders attribute in the entity:
```
/**
 * @ApiResource(cacheHeaders={"max_age"=0, "shared_max_age"=3600, "stale_while_revalidate"=15, "stale_if_error"=30})
 */
```

would produce this cache-control:
`max-age=0, s-maxage=3600,  stale-while-revalidate=15, stale-if-error=30`
