### ISSUE TITLE
Normalization context example value problem for yaml operation

### ISSUE THREAD

**Issue by safaksaylam** [api-platform/core#3430]
**API Platform version(s) affected**: 2.5.4

**Description**  
**1.** Operation normalization_context:
Pin entity resource:
```
App\Entity\Pin:
    itemOperations:
        get:
            method: "GET"
            normalization_context:
                groups: ['pin.item.get']
...
```
/api/pins/{id} example value:
```
{
  "id": 0,
  "name": "string",
  "type": "string"
}
```

**2.** Global entity normalization_context:
Pin entity resource:
```
App\Entity\Pin:
    attributes:
        normalization_context:
            groups: ['pin.item.get']
    itemOperations:
        get:
            method: "GET"
...
```
/api/pins/{id} example value:
```
{
  "id": 0,
  "name": "string",
  "type": {
    "id": 0,
    "name": "string"
  }
}
```

**Other configurations:**
Pin entity serialization:
```
App\Entity\Pin:
    attributes:
        id:
            groups: ['pin.item.get']
        name:
            groups: ['pin.item.get']
        type:
            groups: ['pin.item.get']
```

PinType entity resource:
```
App\Entity\PinType:
    itemOperations:
        get:
            method: "GET"
            normalization_context:
                groups: ['pin_type.item.get']
...
```
PinType entity serialization:
```
App\Entity\PinType:
    attributes:
        id:
            groups: ['pin_type.item.get', 'pin.item.get']
        name:
            groups: ['pin_type.item.get', 'pin.item.get']
```

Two option have same results. Only different first option use operation normalization context groups, second option use global entity normalization context.
