### ISSUE TITLE
How to expose code custom exceptions in "bad request" response ?

### ISSUE THREAD

**Issue by sfi-fgarnier** [api-platform/core#3524]
Hi !

I’m using custom exceptions in my API project.
I’m trying to expose code exception (and more details) in the “400 bad request” response returned by api-platform (jsonld format).

Actually, only the message exception is exposed as you can see :

```json
"@context": "/api/contexts/Error",
"@type": "hydra:Error",
"hydra:title": "An error occurred",
"hydra:description": "Undeliverable shipping address with country: FR",
"trace": []
```

Code is useful to give more details on the exception occurred.

What would be the guidelines to do so ?

Thanks.

**Comment by MartkCz** [comment]
https://api-platform.com/docs/core/errors/ does not help? 

You can try implement symfony's HttpExceptionInterface https://github.com/symfony/http-kernel/blob/master/Exception/HttpExceptionInterface.php

**Comment by sfi-fgarnier** [comment]
API Platform errors doc does not help :(
It only talks about custom mapping to change the HTTP code response.

I would like to expose my code/slug exception in json response like this :
```json
"@context": "/api/contexts/Error",
"@type": "hydra:Error",
"hydra:title": "An error occurred",
"hydra:description": "Undeliverable shipping address with country: FR",
"trace": []
"code": 202
"slug": "undeliverable_shipping_address"
```

This is how my custom exception loos like :

```php
class ShipmentUndeliverableAddressException extends \LogicException
{
    public $message = 'Undeliverable shipping address with country: %s';
    protected $code = 202;
    public $slug = 'undeliverable_shipping_address';

    /**
     * @param string $countryCode
     * @param Throwable|null $previous
     */
    public function __construct(string $countryCode, Throwable $previous = null)
    {
        $this->message = sprintf($this->message, $countryCode);
        parent::__construct($previous);
    }
}
```

**Comment by MartkCz** [comment]
IMO you must decorate ErrorNormalizer (https://github.com/api-platform/core/blob/master/src/Hydra/Serializer/ErrorNormalizer.php)

**Comment by sfi-fgarnier** [comment]
@MartkCz : good point but i got circular reference o.0 (Symfony 5 + API Platform v2.5.4)

config/services.yaml :
```yaml
App\Infrastructure\ApiPlatform\Serializer\DomainHydraDecorator:
    decorates: 'api_platform.hydra.normalizer.error'
    arguments: [ '@App\Infrastructure\ApiPlatform\Serializer\DomainHydraDecorator.inner' ]
```

App\Infrastructure\ApiPlatform\Serializer\DomainHydraDecorator.php :
```php
<?php

declare(strict_types=1);

namespace App\Infrastructure\ApiPlatform\Serializer;

use App\Domain\Exception\DomainException;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class DomainHydraDecorator implements NormalizerInterface
{
    private $decorated;

    public function __construct(NormalizerInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    /**
     * @inheritDoc
     */
    public function normalize($object, string $format = null, array $context = [])
    {
        $data = $this->decorated->normalize($object, $format, $context);

        // custom logic here...

        return $data;
    }

    /**
     * @inheritDoc
     */
    public function supportsNormalization($data, string $format = null)
    {
        return $this->decorated->supportsNormalization($data, $format);
    }
}
```

Result :
```
Circular reference detected for service "serializer", path: "serializer -> App\Infrastructure\ApiPlatform\Serializer\DomainHydraExceptionListener -> serializer".
```

**Comment by MartkCz** [comment]
close

```php
class DomainHydraDecorator implements NormalizerInterface, CacheableSupportsMethodInterface, NormalizerAwareInterface, ContextAwareNormalizerInterface
{

	use NormalizerAwareTrait;

	private const CIRCULAR_PROTECTION = 'Domain_Hydra_Decorator_Circular_Protection';

	/**
	 * {@inheritdoc}
	 */
	public function normalize($object, string $format = null, array $context = [])
	{
		$context[self::CIRCULAR_PROTECTION] = true;

		$data = $this->normalizer->normalize($object, $format, $context);
		$data['custom'] = 'value';

		return $data;
	}

	/**
	 * {@inheritdoc}
	 */
	public function supportsNormalization($data, string $format = null, array $context = [])
	{
		if (isset($context[self::CIRCULAR_PROTECTION])) {
			return false;
		}

		return $format === 'jsonld' && ($data instanceof ErrorExtensionInterface);
	}

	/**
	 * {@inheritdoc}
	 */
	public function hasCacheableSupportsMethod(): bool
	{
		return false;
	}

}
```

```yaml
DomainHydraDecorator:
        tags: ['serializer.normalizer']
```

**Comment by sfi-fgarnier** [comment]
Thank for your help.
Your solution works !

I think "circular reference" problem was caused by declaring my decorated service too early...
```yaml
App\Infrastructure\ApiPlatform\Serializer\DomainHydraDecorator:
    decorates: 'api_platform.hydra.normalizer.error'
    arguments: [ '@App\Infrastructure\ApiPlatform\Serializer\DomainHydraDecorator.inner' ]
    
App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Kernel.php,Entity,Migrations}'
```

Finally, this code works too :
```yaml    
# makes classes in src/ available to be used as services
# this creates a service per class whose id is the fully-qualified class name
App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Kernel.php,Entity,Migrations}'

App\Infrastructure\ApiPlatform\Serializer\DomainHydraDecorator:
    decorates: 'api_platform.hydra.normalizer.error'
    arguments: [ '@App\Infrastructure\ApiPlatform\Serializer\DomainHydraDecorator.inner' ]
```
