### ISSUE TITLE
Filter on subresource not working

### ISSUE THREAD

**Issue by ilicmsreten** [api-platform/core#3534]
**API Platform version(s) affected**: 2.5.1

**Description**  

Filters not working on subresources, but are generated in API documentation.

**How to reproduce**  

```
resources:
    App\EntityA:
        collectionOperations:
            get:
                filters: ['somefilter']
    App\EntityB:
        properties:
            entityA:
                subresource:
                    collection: true
                    resourceClass: 'App\EntityA'
........
```

[DocumentationNormalizer](https://github.com/api-platform/core/blob/2.5/src/Swagger/Serializer/DocumentationNormalizer.php#L416) use `get` operation to generate documentation and attach `somefilter`, but [FilterExtension](https://github.com/api-platform/core/blob/2.5/src/Bridge/Doctrine/Orm/Extension/FilterExtension.php#L58) for subresource operations use filters defined in `attributes` level of `resourceClass` in this case `EntityA`.
