### ISSUE TITLE
[Hydra] Link header injection not working

### ISSUE THREAD

**Issue by pesseyjulien** [api-platform/core#3536]
Hi,

I'm trying to setup the admin but I have an issue with the link header. I have checked the docs and related issues, it's not because of Nelmio cors (I have tried without it, same issue). 

Finally, my conclusion is that the **AddLinkHeaderListener** is not working for me. I don't know why, but for now I had to do the following patch :

```
 /**
     * @param ResponseEvent $event
     */
    public function onKernelResponse(ResponseEvent $event): void
    {
        $request = $event->getRequest();
        if($linkProvider = $request->attributes->get('_links')){

            $apiDocUrl = $this->urlGenerator->generate('api_doc', ['_format' => 'jsonld'], UrlGeneratorInterface::ABS_URL);

            $headers = $event->getResponse()->headers;
            $headers->set('Link', '<'.$apiDocUrl.'>; rel="http://www.w3.org/ns/hydra/core#apiDocumentation"');
        }
    }
```

With a low priority so it's triggered after the **AddLinkHeaderListener** :

```
    myworks.reponse.listener:
        class: AppBundle\EventListener\Request\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: 'onKernelResponse', priority: -9 }
```
My nemlio cors config :

```
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(cors_allow_origin)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Preload', 'Fields']
        expose_headers: ['Link']
        max_age: 3600
```

Any idea why the **AddLinkHeaderListener** is not working on its own ?
