### ISSUE TITLE
Resource setting is very rough

### ISSUE THREAD

**Issue by tebaly** [api-platform/core#3539]
**Description**  
Hello. Resource setting is very rough. 

`src/Bridge/Symfony/Routing/ApiLoader.php `

I suggest:
* Select the loading of routes from the list of files in a separate service. Perhaps **ApiFileLoader** for loading routes from a specific `file_path`.
* Create additional route loaders.
    * from bundles directory - _api_directory_

### ApiDirectoryLoader

Like Symfony Routing `Loader/DirectoryLoader.php`

To be able to load routes from a third-party bundle and specify their prefix for them.

**Example** 

### api_directory (type)

```yaml
#config/routes/api_platform.yaml
api_some_bundle:
    resource: '@BundleName/Entity/' # eg
    type: api_directory
    prefix: /some/api 
```

#### ApiDirectoryLoader
```php
    public function load($file, string $type = null)
    {
        $path = $this->locator->locate($file);

        $collection = new RouteCollection();
        $collection->addResource(new DirectoryResource($path));

        foreach (scandir($path) as $dir) {
            if ('.' !== $dir[0]) {
                $this->setCurrentDir($path);
                $subPath = $path.'/'.$dir;
                $subType = null;

                if (is_dir($subPath)) {
                    $subPath .= '/';
                    $subType = 'api_directory';
                }

                $subCollection = $this->import($subPath, $subType, false, $path);

                // TODO: Use a dedicated service 
                // to load routes from resource files marked @ApiPlatform annotation
                // It seems to work out just using a redirect to the loader `api_file` ApiFileLoader
                // just by specifying `$subType = 'api_file';` (and creating ApiFileLoader service)
                // -----------------------------------------------------------------------------------------
            }
        }

        return $collection;
    }
```

---

Transfer almost everything from `ApiLoader.php` to new `ApiFileLoader.php` - _api_file_
`ApiLoader.php` - leave only receiving a list of files from the config and address loading the route from a specific file in a loop for `ApiFileLoader.php` like `$this->import($filePath, 'api_file', false, $path);`

**Comment by tebaly** [comment]
Draft changes.

**Comment by tebaly** [comment]
### Route loader structure
```
api_platform
    api_external_autoload
    api_directory_autoload
    api_resource_autoload
        api_resource
        api_subresource
```

**Comment by tebaly** [comment]
I can restructure. And write a configuration. I can not test the logic you wrote. The tests are broken.

**Comment by tebaly** [comment]
```
api_platform
    api_directory_autoload
        api_directory # recursive loading resources
   ...
```

**Comment by tebaly** [comment]
src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPass.php

This `CompilerPass` - Very strange. It may be necessary to review its implementation. It depends on 'api_platform.resource_class_directories' - this is a big hindrance.

**Comment by tebaly** [comment]
Ability to configure sources

## Config
```yaml
# new section
    resources:
        autoload: true # auto loading resources
        sources:
            configs: false # from config file
            doctrine: true # from Entities
            mongodb: false # from Mongodb doc 
        bundles:
            include: [] # for manual loading, if `autoload: false`
            exclude: [] # from auto loading resources
```

**Comment by tebaly** [comment]
Suggestion: disable auto loading of resources from bundles.

```yaml 
# default config
  resources:
    autoload: false
```

**Explicitly specify a bundle** for importing resources.
Or
Manually **enable autoload and exclude** unnecessary bundle for importing resources.
