### ISSUE TITLE
Subresource Operation Overrides Custom Subresource Operation in Swagger Documentation

### ISSUE THREAD

**Issue by mab05k** [api-platform/core#3551]
Given I have the following configuration
```
# config/resources/question.yaml
resources:
  App\Entity\Question:
    properties:
      answers:
        subresource:
          collection: true
            resourceClass: App\Entity\Answer

  App\Entity\Answer:
    collectionOperations:
      subresource_post:
        method: POST
        path: /questions/{id}/answers
        defaults:
          _api_subresource_context:
            identifiers:
            - [ 'id', 'App\Entity\Question', true ]
```
I have a custom DataPersister for handling the POST.

Problem:
When the Swagger is generated in the `ApiPlatform\Core\Swagger\Serializer\DocumentationNormalizer`, the following snippet within the `normalize()` function `:174` is causing the problem
```
foreach ($this->subresourceOperationFactory->create($resourceClass) as $operationId => $subresourceOperation) {
  $paths[$this->getPath($subresourceOperation['shortNames'][0], $subresourceOperation['route_name'], $subresourceOperation, OperationType::SUBRESOURCE)] = $this->addSubresourceOperation($v3, $subresourceOperation, $definitions, $operationId, $resourceMetadata);
}
```

Prior to this, the `paths` ArrayCollection is created for my operation like this
```
[  '/questions/{id}/answers' => [ 'post' => post_operation...] ]
```

After the above snippet is run, instead of updating to this
```
[  '/questions/{id}/answers' => [ 'post' => post_operation..., 'get' => subresource_operation... ] ]
```
We get
```
[  '/questions/{id}/answers' => subresource_operation... ]
```

I think we'd need to somehow resolve what operation the subresource is and nest it properly in the `paths` array

```
  $paths[$this->getPath($subresourceOperation['shortNames'][0], $subresourceOperation['route_name'], $subresourceOperation, OperationType::SUBRESOURCE)][OPERATION METHOD HERE!!!] = $this->addSubresourceOperation($v3, $subresourceOperation, $definitions, $operationId, $resourceMetadata);
```

It doesn't look like there is currently any data available about the subresource at this point that indicates what operation type we're dealing with, so maybe default to "GET"?
