### ISSUE TITLE
[BUG] C'ant change Paginations 'itemsPerPage' default value, Globally 

### ISSUE THREAD

**Issue by ahmed-bhs** [api-platform/core#3569]
With this configuration:

```
api_platform:
    ...
    collection:
        pagination:
            client_items_per_page: true
            items_per_page_parameter_name: 'limit'
            items_per_page: 20 # should be the default value.
```

I'm getting always 30 as default value for pagination:

<img src="https://i.imgur.com/LtHLRLb.png"></img>

By the way for  a specific resource, it works great but globally it does not work!

This is my current api version:
```
api-platform/api-pack                        v1.2.1
api-platform/core                            v2.5.4 
```
