### ISSUE TITLE
Can not override openapi_context tags in subresource operation

### ISSUE THREAD

**Issue by h3llr4iser** [api-platform/core#3573]
**Description**  
When trying to override tags in openapi_context for a subresource is not working.

**How to reproduce**  
```yaml
App\Entity\App\ListDistribution:
  subresourceOperations:
    list_gdpr_get_subresource:
      method: 'GET'
      path: "/list/{id}/list_gdpr"
      openapi_context:
        tags:
          - Audience

  properties:
    listGdpr:
      subresource:
        resourceClass: 'App\Entity\App\ListGdpr'
        collection: false
```

**Additional Context**  
I get auto generated tags ans not the defined tag for the path in documentation json:
- List
- ListGdpr
