### ISSUE TITLE
[CORS] React app not able to PUT to API

### ISSUE THREAD

**Issue by TimeSplitters** [api-platform/core#3601]
Hi!

I have an API that is running perfectly with one React Native app, one React webapp and 2 websites that consume the API. But, we are building another React frontend, and without a Node server we can't PUT to the API. Meanwhile, we are able to GET and POST.

I learned that PUT has a specific preflight check, but how can we enable the React frontend to PUT without a Node server?

Here is a simple JS example we tried locally: 

```
var myHeaders = new Headers();
myHeaders.append("Authorization", "Bearer  [the token]");
myHeaders.append("Content-Type", "application/json");

var raw = JSON.stringify({
	"givenName": "Chris",
	"phoneNumber": "zer",
	"email": "efezrg",
	"service": "zer"
});

var requestOptions = {
  method: 'POST',
  headers: myHeaders,
  mode: 'cors',
  body: raw,
  redirect: 'follow'
};

fetch("https://url-of-the-api.com/v1/leads", requestOptions)
  .then(response => response.text())
  .then(result => console.log(result))
  .catch(error => console.log('error', error));
```

This POST works fine, but when we PUT it doesn't work. However the PUT works fine from Postman / Insomnia.

Here is my nelmio_cors config:
```
nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['*']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization']
    max_age: 3600
  paths:
    '^/': ~
```

Any idea?

Thanks for your help!
