### ISSUE TITLE
Configurable filter query string parameters

### ISSUE THREAD

**Issue by julienfalque** [api-platform/core#3606]
Filters use a single name as both the query string parameter and the underlying path to the filtered property. This ties the query string parameter to the underlying model: if the model changes, the parameter changes as well and its consumers must be updated. It also exposes internal details that the consumers might not have to be aware of.

I propose to allow setting different names for the query parameters by supporting passing an array of settings to filter properties configuration, e.g.:

**before**
```yaml
services:
  foo.search_filter:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      -
        foo.bar.baz: exact
```

**after**
```yaml
services:
  foo.search_filter:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      -
        baz:
          property: foo.bar.baz
          strategy: exact
```
