### ISSUE TITLE
OpenAPI schema object null type

### ISSUE THREAD

**Issue by Korbeil** [api-platform/core#3709]
**API Platform version(s) affected**: v2.5.4

**Description**  
When we generate an OpenAPI schema from our API, if we have a nullable field, it does add it as an array as following:
```
{
  "Object": {
    "properties": {
      "foo": {"type": ["string", "null"]}
    }
  }
}
```
Actually, this is totaly wrong. According to the OpenApi v3.0.3 (last OpenApi version):
> **type** - Value MUST be a string. Multiple types via an array are not supported.

(see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schemaObject for more details)

To handle nullable fields we should use the `nullable` field which is a boolean.

I don't know what introduced this bug, but this was working fine before, something added this behavior recently.
Since we have some OpenAPI parser behind our schema, I can't export my API anymore since this update.

**How to reproduce**  
Having a resource with a property that is nullable.

**Possible Solution**  
Replace adding a "null" to the `field` by setting the `nullable` field to `true`.

**Additional Context**

**Comment by WhiteRabbitDE** [comment]
I think we already support the nullable config parameter tbh. The nullable is merged into the schema with this method 
https://github.com/api-platform/core/blob/8d78b3fe0fdca8aa223a3560e1806f92003b3ff1/src/JsonSchema/TypeFactory.php#L147

and was introduced with this PR i think:
https://github.com/api-platform/core/pull/3402/files

I did not double check in my swagger.json but i think its covered by tests. I will test in my api later and report back to you.

**Comment by Korbeil** [comment]
The issue is not related to having nullable or not.
The issue is that we have an array as type (which is totaly wrong based on OpenAPI 3 spec).

I wrote about nullable because one of the type in my array was "null" (and should be supported in nullable field, not as "null" type).

**Comment by WhiteRabbitDE** [comment]
What i meant is that i cant find code that would produce that array in "type" and that if a field is nullable it is converted into "nullable" => true.

I would like to investigate that problem. Can you give an example of a object that would produce the error ?

**Comment by c1tru55** [comment]
problem still exists, API Platform generates invalid OpenAPI schema. example:
```
#[ORM\Entity]
#[ApiResource]
class Product
{
    #[ORM\Id]
    #[ORM\CustomIdGenerator(class: UuidGenerator::class)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\Column(type: UuidType::NAME)]
    #[ApiProperty(identifier: true)]
    public ?Uuid $id = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    public ?string $name = null;

    #[ORM\Column(nullable: true)]
    public ?string $description = null;

    #[ORM\Column(nullable: true)]
    public ?int $position = null;
}
```
resulting schema:
```
components:
  schemas:
    Product:
      type: object
      description: ''
      deprecated: false
      properties:
        id:
          readOnly: true
          type:
            - string
            - 'null' <---
          format: uuid
        name:
          type: string
        description:
          type:
            - string
            - 'null' <---
        position:
          type:
            - integer 
            - 'null' <---
      required:
        - name

```
