### ISSUE TITLE
Operation output class name should be used if set instead Resource short name in summary texts

### ISSUE THREAD

**Issue by maxtorete** [api-platform/core#3740]
**API Platform version(s) affected**: 2.5.7

**Description**  
If you create an operation for a resource that returns a different resource class (for example making a custom operation for a subresource), Swagger UI documentation shows the Resource class a returning type, even if you set a different output class in operation parameters. 

**How to reproduce**  
Create a Resource A and a Resource B. In resource A add this collection operation:

```
    get_subresource:
      method: GET
      route_name: my_route
      output:
        class: App\ResourceB
        name: ResourceB
      openapi_context:
        parameters:
          - { name: id, in: path, required: true, type: string }
```

**Possible Solution** 
If output is set take the class name from it in operation summary, take resourceShortName otherwise

**Comment by dunglas** [comment]
I don't think we should change this. DTOs are intended to be used as alternative representations of the same resource (https://api-platform.com/docs/core/dto/#using-data-transfer-objects-dtos). Users are already confused about the usage of DTO, I fear this change will increase the confusion. WDYT @api-platform/core-team?

**Comment by maxtorete** [comment]
Hi @dunglas !

I'm not using with DTOs, but to set the returning type of a collection operation on a ParentResource that returns a NestedResource. I'm using it in a custom action and custom controller.

**Without the output parameter**, Swagger UI says that it returns a Collection of ParentResources, even if it is returning a NestedResources collection. It works fine as the controller returns a NestedResource collection, but Swagger UI is wrong.

**With the output parameter**, Swagger UI is inconsistent, as it says that it returns a Collection of Resources, but shows the NestedResource schema for items instead. You can see it in action in the attached screenshot.

Here is the operation in the Resource definition:

```
  collectionOperations:
    get_subresource:
      method: GET
      route_name: parent_resource_get_subresource
      collection: true
      output:
        class: App\NestedResource
        name: NestedResource
      openapi_context:
        parameters:
          - { name: id, in: path, required: true, type: string, description: 'Parent Resource identifier' }
```

And here is the result in Swagger UI, where it says that is a ParentResource collection, but shows the NestedResource item schema:

![Screenshot_2020-09-30 API Platform](https://user-images.githubusercontent.com/1867132/94664181-e450f800-030a-11eb-8c15-91f8deba2961.png)
