### ISSUE TITLE
[Bridge/Symfony/Bundle] configurable asset package

### ISSUE THREAD

**Issue by smatyas** [api-platform/core#3760]
**Description**  
Using the Symfony framework, it would be useful in some cases if we could configure the "asset package" used by the api platform.
In this way, we would have more control over the generated asset urls: https://symfony.com/doc/4.4/reference/configuration/framework.html#packages

**Example**  
There could be a new config option with the currently used `null` default value, so it would be backward-compatible.

```yaml
# app/config/packages/api_platform.yaml
api_platform:
    asset_package: 'custom_package'
```

The current templates should need only some minor modifications i.e.:

```diff
- <link rel="stylesheet" href="{{ asset('bundles/apiplatform/style.css') }}">
+ <link rel="stylesheet" href="{{ asset('bundles/apiplatform/style.css', asset_package) }}">
```

And of course that new parameter has to be set for the templates i.e. in `\ApiPlatform\Core\Bridge\Symfony\Bundle\Action\SwaggerUiAction::getContext`

**Comment by soyuka** [comment]
This would be to change the css used by Swagger ui ? I think that the best for this is just to add your own swagger ui using the `/docs.json` entrypoint.

**Comment by smatyas** [comment]
The opposite! I'd like to keep the default ui, which is totally fine for me.

But if for whatever reason I have to modify the **default** `base_path`, that will break the api platform default swagger ui (because that will use the same default setting). Now _this_ is what I'd like to solve using a configurable asset package name.

For example, if I have to use this config, that will break the api platform ui:

```yaml
# config/packages/framework.yaml
framework:
    # ...
    assets:
        base_path: '/custom_base_path'
```

With the proposed changes, I believe I could use the following assets config to make everything work:

```yaml
# config/packages/framework.yaml
framework:
    # ...
    assets:
        base_path: '/custom_base_path' # the default
        packages:
            api_platform:
                base_path: '/'
```
and

```yaml
# app/config/packages/api_platform.yaml
api_platform:
    asset_package: 'api_platform'
```

----

Probably any package that uses the `asset` twig function should have such a configurable option.
