### ISSUE TITLE
Allow many values for SearchFilter with every strategies

### ISSUE THREAD

**Issue by benja-M-1** [api-platform/core#3782]
**Description**  
For now the SearchFilter accept many values only with the "exact" strategy: https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Filter/SearchFilter.php#L122
This is a limitation and we could make it possible to search partially many values.

With many values, the exact strategy adds a WHERE IN clause. 
Doing the same for the partial, start, end and word_start we could add LIKE OK LIKE [...] clause.

**Example**  

```php
/**
 * @ApiFilter(SearchFilter::class, properties={"email": "partial"})
 */
class Contact 
{
    private $email;
}
```

```yaml
Contact:
    john:
        email: "john@company.com"
    jane:
        email: "jane@ext-company.com"
```

Requesting `/contacts?email[]=@company.com&email[]=@ext-company.com` would return john and jane.

I can send a draft PR, I implemented it on my project. Let me know if this would be interesting :)
