### ISSUE TITLE
[CORS] Method PUT is not allowed by Access-Control-Allow-Methods in preflight response

### ISSUE THREAD

**Issue by djpremier** [api-platform/core#3944]
**API Platform version(s) affected**: 2.6.0 Beta 1

**Description**  
Is not possible make PUT/PATCH operations from web.

`Access to XMLHttpRequest at 'https://*****/categories/db0536b7-4563-4bf6-81b0-543fd911e16b' from origin 'http://localhost:3001' has been blocked by CORS policy: Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.`

Checking the Options request for this route, the method is not authorized:
![image](https://user-images.githubusercontent.com/17091381/103704500-2e8bea00-4f88-11eb-864b-d4d82073be8d.png)

Related issue: #3601 

**How to reproduce**  

**Possible Solution**  

**Additional Context**  

```
# nelmio_cors.yaml

nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Preload', 'Fields']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
```
