### ISSUE TITLE
Not possible to disable OpenAPI, swagger UI 

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#3960]
**API Platform version(s) affected**: 2.6

**Description**

Using the following configuration fails: 
  
```
api_platform:
    enable_swagger: false
    enable_swagger_ui: false
    enable_profiler: false
    enable_docs: false
    enable_entrypoint: false
    enable_re_doc: false
```

Indeed, it looks for services declared in 

```
        $loader->load(__DIR__.'/../../../vendor/api-platform/core/src/Bridge/Symfony/Bundle/Resources/config/openapi.xml');
        $loader->load(__DIR__.'/../../../vendor/api-platform/core/src/Bridge/Symfony/Bundle/Resources/config/json_schema.xml');
```

Some of the needed services must be loaded even when these flags are set to false (see Configuration.php).
