### ISSUE TITLE
Latest update introduces missing dependency error

### ISSUE THREAD

**Issue by jkabat** [api-platform/core#3998]
**API Platform version(s) affected**: 2.6.1

**Description**  
On production I'm having swagger disabled:
```yaml
    enable_swagger: false
    enable_swagger_ui: false
    enable_re_doc: false
    enable_entrypoint: false
```

After update I'm getting:
`
 The service "api_platform.action.documentation" has a dependency on a non-existent service "api_platform.openapi.factory".
`

openapi is disabled when swagger is disabled... Is there any possible configuration option to switch off documentation? As it is not needed for me. `enable_doc: false` did not helped.

**How to reproduce**  
```bash
bin/console cache:clear --env=prod # with above configuration
```
