### ISSUE TITLE
Unable to set extensionProperties with yaml schema definition

### ISSUE THREAD

**Issue by Cbruyere** [api-platform/core#4002]
**API Platform version(s) affected**: 2.6.1
Symfony 5.2 project

**Description**  
Regarding this link :
[https://api-platform.com/docs/core/openapi/](url)
I was able in a decorated OpenApiFactory to add some extensionProperties like that : 

`$openApi = $openApi->withExtensionProperty('x-value', 'Custom x-value value');
`
I was unfortunately unable to set those custom attributes in my schemas definitions, here are different tries i did : 
```
resources:
    Skeleton\Entity\DummyAddress:
        attributes:
            pagination_client_items_per_page: true
            filters:
                - dummy_address.search_filter
                - dummy_address.or_search_filter
                - dummy_address.multiple_strategies_search_filter
                - dummy_address.ymd_format_date_filter
                - dummy_address.is_not_search_filter
                - dummy_address.disable_softdeleteable_filter
        collectionOperations:
            get:
                x-visibility: hide
                openapi_context:
                     x-visibility: hide
                normalization_context:
                    enable_max_depth: true
                    groups: ['dummy_address:collection:read']
                    swagger_definition_name: "Read"
            join_pool:
                extensionProperties:
                        x-visibility: hide
                path: /custom/route
                name: 'custom_operation'
                method: POST
                controller: App\Controller\CustomOperation
                openapi_context:
                    x-visibility: hide
                    extensionProperties:
                        x-visibility: hide
```
also a custom parameter in openapi_context won't be passed anymore in collection/items operations as it was in 2.5.* versions

like : 
```
openapi_context:
      visibility: hide
```

I Think it's a bug regarding OpenApi documentation on path definitions
"This object MAY be extended with Specification Extensions.

Specification Extensions
While the OpenAPI Specification tries to accommodate most use cases, additional data can be added to extend the specification at certain points.

The extensions properties are implemented as patterned fields that are always prefixed by "x-".
^x- | Any | Allows extensions to the OpenAPI Schema. The field name MUST begin with x-, for example, x-internal-id. The value can be null, a primitive, an array or an object. Can have any valid JSON format value."
