### ISSUE TITLE
Enable serialization group in doctrine ORM yml file

### ISSUE THREAD

**Issue by 3kynox** [api-platform/core#403]
Hello,

following the doc, to enable serialization group on property, it's needed to set annotations : 

```php
    /**
     * @Groups({"contacts"})
     */
    protected $moyensComm;
```

I would like to enable it using yml ORM doctrine file instead : 

```yml
ContactBundle\Entity\Ami:
    associationOverride:
        moyensComm:
            groups: [ "contacts" ]
```

It looks like adding serialization group inside yaml doctrine file has no effect.

I'm in need of this because i get error when I'm trying to add a new phone at Contact->Ami : 

![](http://i.imgur.com/7LcwO86.png)

Contact is a mappedSuperclass. Ami/Ennemi class extends that mappedSuperclass.
Contact got manyToMany association to abstract class moyensComm and Telephone class extends moyensComm (with alone 'numero' property).

Error is explicit, it tells to define serialization group on moyensComm Ami class property inherited from from Contact. SerializationGroup is already enabled on moyensComm Contact class property. But as moyensComm property do not exists in Ami/Ennemi class, and only a associationOverride is defined in these classes, how to set the serializationGroup in it ?

That's why I wanna use yml ORM Doctrine file instead of annotations to be able to define it inside associationOverride.

Thanks for help.

**Comment by theofidry** [comment]
Hello @3kynox,

I'm not sure to understand your issue, `@Groups` are not a Doctrine annotation, but a [Serializer one](http://symfony.com/doc/current/components/serializer.html#attributes-groups). As such, if you want to configure it in a YAML or XML file, it is not done in the Doctrine mapping configuration one.

**Comment by dunglas** [comment]
@theofidry is right. If you want to defini groups in YAML, use the config file of the Symfony serializer, not the one from Doctrine.

**Comment by dunglas** [comment]
Can we close this issue?

**Comment by 3kynox** [comment]
Not yet please. Thanks for answer guys. It gives some explanations of what I was doing wrong.

If I follow what it is said on documentation, 

- I loaded serializer component -> composer require symfony/serializer
- I enabled serializer in config file : 
```yml

framework:
    secret: %secret%
    validation:      { enable_annotations: true }
    serializer:      { enabled: true }
    // ...
```
- I created a ContactBundle/Resources/config/serializer/Telephone.yml file for testing with inside : 

```yml
ContactBundle\Entity\Telephone:
    attributes:
        numero:
            groups: ['contacts']
```

- I updated my Telephone class : 
```php
<?php

namespace ContactBundle\Entity;

use Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory;
use Symfony\Component\Serializer\Mapping\Loader\YamlFileLoader;

$classMetadataFactory = new ClassMetadataFactory(new YamlFileLoader(__DIR__.'\..\Resources\config\serializer\Telephone.yml'));

class Telephone extends MoyenCommunication
{
    protected $numero;

    public function setNumero($numero)
    {
        $this->numero = $numero;

        return $this;
    }

    public function getNumero()
    {
        return $this->numero;
    }
}
```

And It looks like my numero field doesn't appear in my api request and it have no effects.

![](http://i.imgur.com/bwf6ju6.png)

I'm sure I'm miising something.

**Comment by 3kynox** [comment]
Hello again, any news ?

I'm not sure anyway to be able to use serialization groups using yaml file will help me get rid of the error I face.

To see exact UML model, see image : 

![](http://i.imgur.com/7rG3zuC.png)

Serialization group items defined are : 

- Contact : every properties except id
- Ami / Ennemi : amiDepuis / ennemiDepuis properties

>  Ami / Ennemi got [associationOverride](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#association-override) on mapping yml files (Ami.orm.yml & Ennemi.orm.yml) for moyensComm property where I can't set a serializationGroup

- MoyenCommunication : property id
- Telephone / Email / Adresse : every properties

When I send a POST request with data : 
```json
{
    "nom": "DOE",
    "prenom": "John",
    "dateNaissance": "",
    "articleSection": "2016-02-14",
    "moyensComm": [
    {
      "@type": "Telephone",
      "numero": "123456"
    }
  ]
}
```

Kicked error is : 

```json
{
  "@context": "/CRM/api/contexts/Error",
  "@type": "Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Nested objects for attribute \"moyensComm\" of \"ContactBundle\Entity\Ami\" are not enabled. Use serialization groups to change that behavior."
}
```

Sending same request without moyensComm works.

Thanks for help.

**Comment by marcin-piela** [comment]
Did you update service definition?
https://api-platform.com/doc/1.0/api-bundle/serialization-groups-and-relations#using-serialization-groups

**Comment by 3kynox** [comment]
Yup, service definition looks like this currently : 

```yml
services:
    resource.ami:
        parent:    "api.resource"
        arguments: [ "ContactBundle\\Entity\\Ami" ]
        calls:
            - method:     "initNormalizationContext"
              arguments:  [{ groups: [ "contacts" ] }]
        tags:      [ { name: "api.resource" } ]

    resource.ennemi:
        parent:    "api.resource"
        arguments: [ "ContactBundle\\Entity\\Ennemi" ]
        calls:
            - method:     "initNormalizationContext"
              arguments:  [{ groups: [ "contacts" ] }]
        tags:      [ { name: "api.resource" } ]

    resource.moyencommunication:
        parent:    "api.resource"
        arguments: [ "ContactBundle\\Entity\\MoyenCommunication" ]
        tags:      [ { name: "api.resource" } ]

    resource.telephone:
        parent:    "api.resource"
        arguments: [ "ContactBundle\\Entity\\Telephone" ]
        tags:      [ { name: "api.resource" } ]
```

For testing purposes I did not included Email and Adresse for the moment.

config.yml serializer component is back activated with annotations : 

```yml
framework:
    secret: %secret%
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
```

**Comment by marcin-piela** [comment]
But you want enable it in POST, so:
https://api-platform.com/doc/1.0/api-bundle/serialization-groups-and-relations#denormalization

**Comment by 3kynox** [comment]
You right, I updated Ami / Ennemi service definition as follow : 

```yml
    resource.ami:
        parent:    "api.resource"
        arguments: [ "ContactBundle\\Entity\\Ami" ]
        calls:
            - method:     "initNormalizationContext"
              arguments:  [{ groups: [ "contacts" ] }]
            - method:    "initDenormalizationContext"
              arguments:  [{ groups: [ "contacts" ] }]
        tags:      [ { name: "api.resource" } ]
```

Error changed : 
```yml
{
  "@context": "/CRM/api/contexts/Error",
  "@type": "Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Cannot create an instance of ContactBundle\Entity\MoyenCommunication from serialized data because it is an abstract resource"
}
```
