### ISSUE TITLE
Annotations and yaml configuration not merged

### ISSUE THREAD

**Issue by benja-M-1** [api-platform/core#4036]
**API Platform version(s) affected**: 2.5.7

**Description**  
Configuring a resource partly with annotations and yaml does not work I expected it. Don't know if it is really a bug or a feature.

**How to reproduce**  
Add an entity with the following ApiResource annotations:

```php
/**
 * @ApiResource( attributes={"pagination_enabled": false"})
 */
class Book 
{
  // ... rest is ommitted
}
```

And then in `resources.yaml` 

```yaml
App\Entity\Book:
    attributes:
        normalization_context:
            groups: ['book:read']
        denormalization_context:
            groups: ['book:write']
```

Then the normalization attributes are not set.

**Possible Solution**  
The problem (if ever there is) is that the [ExtractorResourceMetadataFactory](https://github.com/api-platform/core/blob/main/src/Metadata/Resource/Factory/ExtractorResourceMetadataFactory.php#L95) ignores the values of properties set by annotations (which is the first strategy parsed when I debugged).

I can see two fixes:
- either throw an exception when two strategies overwrites one another and add something in the documentation about not mixing two type of configurations  (maybe here https://api-platform.com/docs/core/getting-started/#product)
- either merging the two values but then one should define which is the one that overwrites over the others
