### ISSUE TITLE
Modify routes name and overriding controllers

### ISSUE THREAD

**Issue by 3kynox** [api-platform/core#404]
Hello,

I'm searching the way to : 

- Modify route name, example : rename route ../api/contacts to api/persons
- Override a controller specific action for a given entity. example : to format returned string of a entity property.

Thanks for informations.

**Comment by marcin-piela** [comment]
1. Call method initShortName in resource service with arguments: ["persons"]
2. https://api-platform.com/doc/1.0/api-bundle/controllers#using-a-custom-controller
Create custom action, next call method initCollectionOperations or initItemOperations (depends what you want achieve)

**Comment by 3kynox** [comment]
Thanks, first works like a charm
Second is harder to implements but looks like to fit : 
1. Set the custom controller
2. Using services and above methods specify on which exposed entity apply the custom controller

If I understood all of this :)

**Comment by 3kynox** [comment]
Hello again, I'm having [this issue](http://paste2.org/zsXLVM5f).

Here is my controller : 

```php
// src\Nucleus\ContactBundle\Controller\EchangeController.php

<?php

namespace Nucleus\ContactBundle\Controller;

use Dunglas\ApiBundle\Controller\ResourceController;
use Symfony\Component\HttpFoundation\Request;

class EchangeController extends ResourceController
{
    public function cgetAction(Request $request)
    {
        $this->get('logger')->info('This is my custom controller.');
        return parent::cgetAction($request);
    }
}
```

And here is my service config file for the part of this controller call : 

```yml
    resource.collection_operation.echange_cget:
      class:   "Dunglas\ApiBundle\Api\Operation\Operation"
      public:  false
      factory: [ "@api.operation_factory", "createItemOperation" ]
      arguments:
          -    "@resource.echange"
          -    [ "CGET"]
          -    "/echanges"
          -    "NucleusContactBundle:Echange:cget"
          -    "filteredEchanges"
          -    # Context (will be present in Hydra documentation)
               "@type":       "hydra:Operation"
               "hydra:title": "A custom operation"
               "returns":     "xmls:string"

    resource.echange:
        parent:    "api.resource"
        arguments: [ "Nucleus\\ProspectBundle\\Entity\\Echange" ]
        calls:
            - [ "initCollectionOperations", [ [ "@resource.collection_operation.echange_cget"] ] ]
        tags:      [ { name: "api.resource" } ]
```

I tried every possibilities in service resource.collection_operation.echange_cget on how to call controller, no changes, createNotFoundException from ResourceController is always returned.

Any idea ? Thanks

**Comment by bwegrzyn** [comment]
@3kynox try using GET instead of CGET for the 2nd argument.

**Comment by 3kynox** [comment]
Thanks for answer @bwegrzyn but no changes, same error returned.

**Comment by dunglas** [comment]
The fix suggested by @bwegrzyn should work. Have you cleared the cache?

**Comment by 3kynox** [comment]
Hi Dunglas, yes, I clear the cache every time I make any change in services. 

I replaced CGET to GET. I moved my controller to another bundle where concerned entities resides (src\Nucleus\ProspectBundle\Controller\EchangeController.php).

Now my services looks like that : 

```yml
    resource.collection_operation.echange_cget:
        class:   "Dunglas\ApiBundle\Api\Operation\Operation"
        public:  false
        factory: [ "@api.operation_factory", "createItemOperation" ]
        arguments:
            -    "@resource.echange"
            -    [ "GET" ]
            -    "/echanges"
            -    "NucleusProspectBundle:Echange:cget"
            -    "filteredEchanges"
            -    "@type":       "hydra:Operation"
                 "hydra:title": "A custom operation"
                 "returns":     "xmls:string"

    resource.echange:
        parent:    "api.resource"
        arguments: [ "Nucleus\\ProspectBundle\\Entity\\Echange" ]
        calls:
            - method:    "initNormalizationContext"
              arguments:  [{ groups: [ "echanges" ] }]
            - method:    "initDenormalizationContext"
              arguments:  [{ groups: [ "echanges" ] }]
            - method:    "initCollectionOperations"
              arguments: [[ "@resource.collection_operation.echange_cget" ]]
        tags:      [ { name: "api.resource" } ]
```

EchangeController got no new changes except namespace who had changed : 

> namespace Nucleus\ProspectBundle\Controller;

Using 1.1@beta of API-Bundle.
Tested with 2 projects, one using micro-framework, and one with full-stack Symfony project.

Still facing 404 Not Found - createNotFoundException.
