### ISSUE TITLE
More options for elasticsearch config

### ISSUE THREAD

**Issue by CvekCoding** [api-platform/core#4059]
**Description**  
I have a case when I need to tune some elastic client settings - my cloud provider require to use https (which is ok) but uses self-signed ca-certificate. Default behavior of elasticsearch client to skip this type of connection. So I need to have a way to tune this connection [this way](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/connceting.html#_self_signed_certificates).
I believe there are more cases when we need to have a way to fine tune elasticsearch client library. So I propose to add an `options` key to elastic config.
**Example**  
```
# src/config/packages/api_platform.yaml
api_platform:
    elasticsearch:
        hosts: ['%env(ELASTICSEARCH_HOST)%']
        options:
            sslVerification: '%env(resolve:ELASTICSEARCH_CA_ROOT)%'
```
We need only a few changes to implement it. I can create a merge request for this.
WDYT?
