### ISSUE TITLE
Support globally disabling operations (with override)

### ISSUE THREAD

**Issue by chuckadams** [api-platform/core#4063]
**Description**  
I have an API that is 90% read-only, and would like to be able to disable all operations except 'read' without having to annotate every last Entity class.  Currently it seems that decorating the DataPersister to throw a permission error is my best option, but that feels terribly hacky when I would rather have a global setting that could be overridden on a per-resource basis.

**Example**  
```
api_platform:
  operations:
    get: true
    post: false
    put: false
    delete: false
    patch: false

  graphql:
    operations:
      collection_query: true
      item_query: true
      create: false
      update: false
      delete: false
```
