### ISSUE TITLE
[OpenApi] Additional property "scheme" in SecuritySchema

### ISSUE THREAD

**Issue by WhiteRabbitDE** [api-platform/core#4071]
**API Platform version(s) affected**: 2.6.2

**Description**  

```
  securitySchemes:
    oauth:
      scheme: oauth2 <--- this one
```

The error is : components.securitySchemes.oauth should NOT have additional properties. This field is also not mentioned on https://swagger.io/docs/specification/authentication/oauth2/

**How to reproduce**  
Enable the implicit flow in the apiplatform configuration.

**Possible Solution**  
The value is nullable but its pre set here 
https://github.com/api-platform/core/blob/959f0829747eb733f496b5ddc6508b433b4f6792/src/OpenApi/Factory/OpenApiFactory.php#L459

Set the default value to null.

Edit: I just saw that its used for BasicAuth.
```
components:
  securitySchemes:
    basicAuth: 
      type: http
      scheme: basic
```
