### ISSUE TITLE
[OpenApi] Invalid securityScheme when using implicit flow

### ISSUE THREAD

**Issue by WhiteRabbitDE** [api-platform/core#4079]
**API Platform version(s) affected**: 2.6

**Description**  
When oauth is enabled in the api-platform configuration all urls (token/refresh/authorization) have a default value e.g.
```
"tokenUrl": "/oauth/v2/token",
```
This leads to an invalid swagger.json if one is using the implicit-flow for example because 
```  
components.securitySchemes.oauth.flows.implicit
should NOT have additional properties
additionalProperty: tokenUrl
```

**How to reproduce**  
Configure oauth like
``` 
 oauth:
        enabled: true
        clientId: my_client
        type: 'oauth2'
        flow: implicit
        authorizationUrl: 'http://my-custom-server/openid-connect/auth'
        scopes: []
``` 

**Possible Solution**  
I think there are some ways to fix this problem. 
1. remove the default values (the fields are nullable in the OAuthFlow class)
2. add some kind of documentation that you have to set them to null if not needed/allowed in your flow
3. add validation in the OAFactory to check if the generated flow is valid ( <-- thats maybe a bit overhead )
