### ISSUE TITLE
normalization_context on subresource, schema is not generated

### ISSUE THREAD

**Issue by TheKassaK** [api-platform/core#4095]
**API Platform version(s) affected**: 2.6.2

**Description**  

If I add a normalization_context on a subresource in yml, the open api schema is not generated, I have to generate this schema manually in the factory.

**How to reproduce**  

```
subresourceOperations:
        api_campaigns_users_get_subresource:
            normalization_context:
                groups: [ 'campaign-user:read:users' ] # Schema generated in OpenApiFactory
```
