### ISSUE TITLE
getBundlePath for entity mapping paths

### ISSUE THREAD

**Issue by maranqz** [api-platform/core#4101]
**Description**  

Add getBundlePath for https://github.com/api-platform/core/blob/94863cd5a813e5cb3bdfc051c3afa9ab0d8382d1/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L325

**Example**  

I want integrate bundle entities with api-platform but I need to write a full path.
```yaml
api_platform:
    mapping:
        paths:
            - 'vendor/vendorName/AcmeBundle/Entity'
            - 
```
By this feature
```yaml
         paths:
            - '@AcmeBundle/Entity'
```

**Comment by maranqz** [comment]
Sorry, enough write mappings for bundle.

```yaml
doctrine:
    orm:
        mappings:
            AcmeBundle:
                is_bundle: true
                type: annotation
                dir: './Entity'
                prefix: 'AcmeBundle\Entity'
                alias: AcmeBundle
````
