### ISSUE TITLE
[GraphQL] Use same type for mutations and queries if normalization context is equal

### ISSUE THREAD

**Issue by javajan** [api-platform/core#4102]
**Description** 

[https://api-platform.com/docs/core/graphql/#different-types-when-using-different-serialization-groups](https://api-platform.com/docs/core/graphql/#different-types-when-using-different-serialization-groups)

In your documentation it states that if the normalization context is the same, then the generated type will be equal. However, looking at the TypeBuilder's code this appears to only be the case for collection_query and item_query. It would be nice if this was also the case for mutations and even custom mutations, because otherwise certain features of popular clients like Apollo don't work as expected (e.g. caching).

**Comment by alanpoulain** [comment]
Where do you see that it is not the case?

**Comment by javajan** [comment]
https://github.com/api-platform/core/blob/94863cd5a813e5cb3bdfc051c3afa9ab0d8382d1/src/GraphQl/Type/TypeBuilder.php#L70-L81

Not certain, but it looks like for `item_query` and `collection_query` the normalization context is compared, but not for mutations. The issue seems to lie in line 79: `Data` is always added to the name no matter the normalization context.

Heres a quick example illustrating what I mean:

```
App\Entity\Conversation\ConversationMessage:
  graphql:
    item_query:
      normalization_context:
        groups: [ 'conversation:read', 'user:read' ]

    createText:
      args:
        text:
          type: String!
      normalization_context:
        groups: [ 'conversation:read', 'user:read' ]
```

```
type Query {
    conversationMessage(id: ID!): ConversationMessage
}

type Mutation {
    createTextConversationMessage(input: createTextConversationMessageInput!): createTextConversationMessagePayload
}

type ConversationMessage implements Node {
  id: ID!
  text: String!
}

type createTextConversationMessagePayload {
  conversationMessage: createTextConversationMessagePayloadData
  clientMutationId: String
}

type createTextConversationMessagePayloadData implements Node {
  id: ID!
  text: String!
}
```

In my opinion `createTextConversationMessagePayloadData` is not needed as it is the same as `ConversationMessage`, because the context is the same.
