### ISSUE TITLE
[OpenAPI] Tag is not taken from openapi_context 

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#4113]
**API Platform version(s) affected**: 2.6.2

**Description**  
                openapi_context:
                    tags: [ User - Profile ]

**Comment by AnisGloulou** [comment]
following

**Comment by soyuka** [comment]
Mhh just tried this and it works try maybe:

```
 tags: 
  - User 
  - Profile
 ```

**Comment by AnisGloulou** [comment]
Other example:
 I have addresses of profile and addresses of professional
I need  a tag to subresource profile like ` professional addresses` : 
```
. . . 
        properties:
            addresses:
                subresource:
                    resourceClass: 'App\Entity\Addresses'
                    collection: true
                readable: true
                writable: true
                required: true
. . .
subresourceOpereations:
            addresses_get_subresource:
                openapi_context:
                    tags: [ Addresses professional ]
```
This tag does n't work.
