### ISSUE TITLE
Cant use filter on subresource

### ISSUE THREAD

**Issue by TheKassaK** [api-platform/core#4127]
**API Platform version(s) affected**: 2.6.3

**Description**  

I have 3 entities : User, Basket and BasketProduct

User oneToOne Basket
Basket oneToMany BasketProduct

So for retrieve a user basket, I did a Subresource : 

```
    /**
     * @ApiSubresource
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Basket", mappedBy="user")
     */
    private ?Basket $basket = null;
```
I need to add a filter on this subresource, on a boolean field in BasketProduct (I need to retrive only specific products in my basket), so this is my filter in yml : 

```
    app.basket.basket_product.saved_for_later.filter:
        parent: 'api_platform.doctrine.orm.boolean_filter'
        arguments: [ { basketProducts.savedForLater: true } ]
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
```
The key is basketProducts.savedForLater : 

 basketProducts : the name of my relation Basket oneToMany BasketProduct
 savedForLater : the name of my boolean in BasketProduct

After that, I need to activate my filter in my yml, like : 

```
App\Entity\Basket:
    collectionOperations:
        api_users_basket_get_subresource:
            filters:
                - 'app.basket.basket_product.saved_for_later.filter'
    subresourceOperations:
        api_users_basket_get_subresource:
            security: "is_granted('CAN_GET_SUB_RESOURCE_USER', _api_normalization_context['subresource_resources'])"
```
**First thing weirg, I have to declare the filter under collectionOperations, not under subresourceOperations**

With this, I can see my filter in the doc : 

![basket](https://user-images.githubusercontent.com/4355752/110661579-022d5d80-81c5-11eb-9fc7-987189b2354a.png)

But when I try to call : **/api/users/47/basket?basketProducts.savedForLater=1**, the filter doesnt work, the list is not filtered and I have all my items.

**Additional Context**  

In the vendor folder, in ApiPlatform\Core\Bridge\Doctrine\Orm\SubresourceDataProdiver, if I force **$context['collection'] = true** before : 

```
if (true === $context['collection']) {
            foreach ($this->collectionExtensions as $extension) {
                // We don't need this anymore because we already made sub queries to ensure correct results
                if ($extension instanceof FilterEagerLoadingExtension) {
                    continue;
                }

                $extension->applyToCollection($queryBuilder, $queryNameGenerator, $resourceClass, $operationName, $context);
                if ($extension instanceof QueryResultCollectionExtensionInterface && $extension->supportsResult($resourceClass, $operationName, $context)) {
                    return $extension->getResult($queryBuilder, $resourceClass, $operationName, $context);
                }
            }
        } else {
            foreach ($this->itemExtensions as $extension) {
                $extension->applyToItem($queryBuilder, $queryNameGenerator, $resourceClass, $identifiers, $operationName, $context);
                if ($extension instanceof QueryResultItemExtensionInterface && $extension->supportsResult($resourceClass, $operationName, $context)) {
                    return $extension->getResult($queryBuilder, $resourceClass, $operationName, $context);
                }
            }
        }
```

My filter work...

So, what I need to do for my filter on this subresource ?
