### ISSUE TITLE
More flexible Hal Json Format

### ISSUE THREAD

**Issue by alexander-schranz** [api-platform/core#4141]
**Description**  

In our case of [Sulu CMS](github.com/sulu/sulu) the hal format which we support in the frontend looks a little bit different to the one in api platform.

I want to list here first the difference as example for a  custom `event` entity:

**Api Platform**

```json
{
     "_embedded": {
          "item": []
     },
     "totalItems": 0,
     "itemsPerPage": 10
}
```

**Sulu Platform**

Example Request: `/admin/api/events?locale=de&limit=1&page=2`

```json
{
    "_embedded": {
         "events": []
    },
    "limit": 10,
    "total": 0,
    "page": 1,
    "pages": 1
}
```

To get as near as possible api platform to sulu I did test the following configuration in my test [Pull Request in the Sulu Demo](https://github.com/sulu/sulu-demo/pull/57)

Also when we define in the api platform:

```yaml
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    # Custom
    formats:
        jsonhal:
            mime_types:
                - application/hal+json
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html

    collection:
        pagination:
            client_items_per_page: true
            items_per_page_parameter_name: limit
```

The `items_per_page_parameter_name` has effect on the query parameter but not on the actually returned response.

So we have the following issues:

 - [ ] ApiPlatform has the [`item`](https://github.com/api-platform/core/blob/1ba77218dfe61ca9e6cff1bbb3e9a4a6658d4538/src/Hal/Serializer/CollectionNormalizer.php#L94) hardcoded for all entities and does not support to define here a specific key, sulu requires here the specific resource key like "events", "contacts", ...
 - [ ] The [`totalItems`](https://github.com/api-platform/core/blob/1ba77218dfe61ca9e6cff1bbb3e9a4a6658d4538/src/Hal/Serializer/CollectionNormalizer.php#L70) are hardcoded, sulu use here a different name "total"
 - [ ] The [`itemsPerPage`](https://github.com/api-platform/core/blob/1ba77218dfe61ca9e6cff1bbb3e9a4a6658d4538/src/Hal/Serializer/CollectionNormalizer.php#L74) are hardcoded, sulu use here a different name "limit"
 - [ ] Things like current `page` are not provided, I think this could also be provided by api platform maybe we can discuss here a name which you are okay with it
 - [ ] Things like available `pages` are not provided, I think this could also be provided by api platform maybe we can discuss here a name which you are okay with it

**Example**  

I could think that something  like `page`, `pages` could be maybe added and the hal format had some option to be configureable e.g.:

```yaml
     use_inflector: true
     totalItems_name: 'total'
     itemsPerPage_name: 'limit'
     page_name: 'page'
     maxPages_name: 'pages'
```

I would be really happy to support api platform apis in the sulu cms admin ui. I would be interested which things make sense in api platform core, or which things we need to handle in sulu, also appricate there what it would be the right way to hook into the hal collection normalizer?
