### ISSUE TITLE
Conflict between defaults.order and collection.order configs

### ISSUE THREAD

**Issue by guilliamxavier** [api-platform/core#4170]
**API Platform version(s) affected**: 2.6.3

**Description**
The `defaults.order` config value, which would work as the global equivalent of https://api-platform.com/docs/core/default-order/#overriding-default-order (fields _array_), is also used in place of `collection.order` (direction _string_), which causes a TypeError.

**How to reproduce**
Config:
```yaml
api_platform:
    defaults:
        order: [createdAt, id]
```

Error (on collection GET request):
> Argument 1 passed to ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Extension\\OrderExtension::__construct() must be of the type string or null, array given

**Possible Solution**
Revert the order-related changes of https://github.com/api-platform/core/commit/dc461fcc504e8b52e5134013f2f3c7d947325dd0 (note that, unlike the `collection.pagination.*` non-`*_parameter_name` keys, `collection.order` is _not_ deprecated, so I don't see the reason for wanting to move it to `defaults.order`, even more so since that key was already used after #3151)

**Additional Context**
Workaround for now: use the explicit `attributes` sublevel:
```yaml
api_platform:
    defaults:
        attributes:
            order: [createdAt, id]
```
