### ISSUE TITLE
v2 metadata - YAML resource config

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#421]
This is a discussion on PR #375

It seems like the current code only supports using the `Resource` annotation?

**Comment by dunglas** [comment]
Yes. YAML and XML (I prefer XML but the better is to support both) is planned. As always, all help is very welcome.

**Comment by 3kynox** [comment]
:+1:

**Comment by soyuka** [comment]
How are you picturing this? 

1. CompilerPass
2. Read tagged services `api_platform.resource`
3. Add classes to the ResourceCollectionMetadata 
4. Generate ResourceItemMetadata (operations, filters, normalization contexts etc)

- Should a resource be a service? By that I mean that we can add method calls on definitions. Or, do we simply parse configurations and handle them like we handle annotations?   
- normalization contexts are defined by operations now right? So are filters apparently? 

Maybe we could start by setting up the full configuration schema? 

Proposal:

```yaml
    resource.product:
        class:  'Product\ProductBundle\Entity\Product'
        parent: '?'
        itemOperations:
            - methods: ['POST']
              denormalization: ['some', 'context', 'group']
            - methods: ['GET'] # Following is applied to every 'GET itemOperation' 
              dataprovider: 'instance of ItemDataProviderInterface'
            - methods: ['GET']
              route_name: 'some_route_name' # Following will be active on the current Operation identified by the route_name
              route: '/my/new/route' 
              controller: '@some.service'
              dataprovider: 'instance of ItemDataProviderInterface' 
        collectionOperations:
            - methods: ['GET', 'POST'] # Apply filters and data provider to every collectionOperation methods
              filters: ['@some.filter'] 
              dataprovider: 'instance of CollectionDataProviderInterface'
        tags: [ { name: 'api_platform.resource'} ]
```

Now a base resource would be defined as:

```
    resource.person:
        class: 'Party\PartyBundle\Entity\Person'
```

IMO it'd be nice that a configuration defined Operation just extends the base ones. For example, here the `collectionOperations`  will still have the `POST` method, even if not declared. I don't know if there's any interest in adding a way of not having standard REST method, I don't see any. To override an Operation it'd require a configuration on the Operation identifier, here the `route_name` (maybe it's not the right identifier?). 

From what I've seen, there's a lot of reusable code in Annotation parsing.

**Comment by teohhanhui** [comment]
@soyuka You're getting the wrong idea.

In this case the yml files are for configuration, like the Symfony Serializer and Validator configuration files. They are not Symfony services.

**Comment by soyuka** [comment]
I know yes but in v1 the configuration declares a kind of service (hence
the parent attribute).
Le mer. 24 févr. 2016 à 13:02, Teoh Han Hui <notifications@github.com> a
écrit :

**Comment by dunglas** [comment]
@soyuka there are 2 distinct things:

* Adding a YAML (and XML) loader for the new metadata system. It doesn't need any configuration or service, it should be independent of Symfony (except maybe some component like the YAML one). You can take a look at how it's done for the Symfony Serializer as an example: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Mapping/Loader/YamlFileLoader.php
* Creating a compatibility layer with the v1. IMO it should be a special metadata loader using the Symfony kernel to retrieve resources and filters service definition from the v1 and convert them into instance of `*Metadata` classes of the v2

**Comment by soyuka** [comment]
Thanks @dunglas it's clearer. 

Still, what about filters, normalization groups etc. which are defined by operations, no more by resources. Should they still fit the v1 configuration schema? Agreed that they should be a compatibility layer in any case.

**Comment by dunglas** [comment]
Everything was service in the v1, and now everything is value objects (*Metadata). It should be possible to have a BC layer for most of them but it's a hard work IMO.

**Comment by soyuka** [comment]
+1, that said the configuration in v2 can be better than the one in v1 (for example defining normalization groups by operation).

**Comment by dunglas** [comment]
Yes it was one of the goals of this large refactoring. The new system is a solid foundation, with to dependency to the Symfony framework (can be used with Laravel or Drupal as well).

**Comment by soyuka** [comment]
Indeed, we're on the same page. So, what would the new configuration schema look like (if we skip the BC layer)? From what I understood this is a configuration parsing, this means that no symfony services will be injected.

If I transform my previous try it'd be something like:

```
\\MyBundle\Resources\config\resources.yml (or xml)
resources:
    product:
        shortName: 'someproductshortname'
        description: 'Product resource'
        class:  'Product\ProductBundle\Entity\Product'
        itemOperations:
            - methods: ['GET']
              filters: ['product.my_awesome_filter'] # this is the filter id 
            - methods: ['GET']
              route_name: 'some_route_name'
              route: '/my/new/route' # Controller can be set in the routing configuration for a given path with symfony 
        collectionOperations:
            - methods: ['GET', 'POST'] # Apply filters and data provider to every collectionOperation 
              denormalizationContext: {groups: ['some', 'context', 'groups']}
methods
        iri: 'someirischema'
```

Where filters have an `id` which does the link (instead of having a symfony service). 

I haven't found (yet) where dataProvider (now split into `CollectionDataProvider` and `ItemDataProvider`) defines the resources that are supported. Anyway this is linked to Doctrine so I left it aside.

What about Annotations on top of Configuration? Should they merge?

**Comment by dunglas** [comment]
```yaml
resources:
    product:
        shortName: 'someproductshortname'
        description: 'Product resource'
        class:  'Product\ProductBundle\Entity\Product'
        itemOperations:
            my_op_name: {} # an arbitrary associative array that can contain anything
            my_other_op_name: {} # same
        collectionOperations:
            my_collection_op: {} # same again...
        iri: 'someirischema'
        attributes: {} # Another random associate array
        properties: # Here is the mapping for Metadata\Property\ItemMetadata
            price:
                description: 'The price of the product'
                #type: I would let this away for now, as the PropertyInfo loader already do the job
                readable: true
                writeable: true
                readableLink: true
                writeableLink: true
                required: true
                iri: 'http://example.com'
                identifier: false
                attributes: {} # An associate array, still without constraints
```

**Comment by soyuka** [comment]
Interesting, could you please explain what properties metadata is used for? I saw that the normalizer uses some of them to check if they are writeable/readable.  If I'm not mistaken, this was handled in the v1 through the PropertyInfo component (within symfony), and still is in v2 on the Symfony bridge.

What's the readableLink/writeableLink use case?

Thanks!

**Comment by teohhanhui** [comment]
@dunglas I'm trying to figure out how to borrow the Loader pattern from the Symfony Serializer, and fit it into the chain of decorator factories. Do we just forgo the Loader pattern altogether and create another factory, e.g. `YamlResourceMetadataFactory`?

**Comment by teohhanhui** [comment]
And I'd definitely love to support this kind of functionality:

https://github.com/symfony/framework-bundle/blob/e65c60c9d8f8288a93ab3a6fdfa8165bbc2b2af0/DependencyInjection/FrameworkExtension.php#L941-L978

**Comment by soyuka** [comment]
+1 about using the symfony `Finder` to do automatic configuration parsing like this (maybe only in the Bridge?). 
This should support XML too. Maybe that there will be common paths between XML and YML factories that would have to merge in some kind of loader?

**Comment by soyuka** [comment]
I was going through the json schema documentation and reading it remind me of the resource configuration proposal two posts above. 

For example the json schema hypermedia overview:

```
{
    "title": "Written Article",
    "type": "object",
    "properties": {
        "id": {
            "title": "Article Identifier",
            "type": "number"
        },
        "title": {
            "title": "Article Title",
            "type": "string"
        },
        "authorId": {
            "type": "integer"
        },
        "imgData": {
            "title": "Article Illustration (small)",
            "type": "string",
            "media": {
                "binaryEncoding": "base64",
                "type": "image/png"
            }
        }
    },
    "required" : ["id", "title", "authorId"],
    "links": [
        {
            "rel": "full",
            "href": "{id}"
        },
        {
            "rel": "author",
            "href": "/user?id={authorId}"
        }
    ]
}
```

Just a thought, but declaring properties in a resource configuration feels too much. Also, json schema's are kind of declaring everything we need here, and are truly portable (you can do a lot based on json schema's).

**Comment by teohhanhui** [comment]
@soyuka I believe JSON Schema is out of scope and undesirable for this project. It's been built around JSON-LD and Hydra (though there's support for XML serialization). The domain model should be RDF (JSON-LD is a serialization format for RDF), though it doesn't seem to be enforced especially since there's no support provided here for building / maintenance of RDF schema. A good starting point would be schema.org

**Comment by soyuka** [comment]
@teohhanhui  agreed that it's out of scope here. I just want to understand the use of 

```
        properties: # Here is the mapping for Metadata\Property\ItemMetadata
            price:
                description: 'The price of the product'
                #type: I would let this away for now, as the PropertyInfo loader already do the job
                readable: true
                writeable: true
                readableLink: true
                writeableLink: true
                required: true
                iri: 'http://example.com'
                identifier: false
                attributes: {} # An associate array, still without constraints
            # Mapping for other properties here
```
in the configuration. I don't see the need, nor the use case.

Still, a json schema can represent a json-ld resource and be helpful for validating input data.
