### ISSUE TITLE
Unable to configure openapi_context in yaml config

### ISSUE THREAD

**Issue by bram123** [api-platform/core#4233]
**API Platform version(s) affected**: 2.6.4

**Description**  
Using only config/api-platform/x.yaml files, it's not possible to configure the openapi_context settings.

**How to reproduce**  
Setup yaml config file (`config/api_platform/resources.yaml`):
```yaml
resources:
  App\Entity\X:
    attributes:
      openapi_context:
        tags:
          - "Entity"
          - "EntityX"
```

**Possible Solution**  
I managed to fix this by changing `ApiPlatform\Core\Metadata\Resource\Factory\OperationResourceMetadataFactory`, and adding `openapi_context` in the methods `createOperations` & `normalize`.
But I'm not familiar enough with Api-Platform to see which things will be influenced in total by changing this.

**Comment by abdounikarim** [comment]
Hello @bram123 
I'm also using API Platform with yaml files and the `openapi_context` key works for me. 
For example i have something like this in my file : 
```yaml
resources:
    App\Entity\Book:
        collectionOperations:
            book_collection_get:
                openapi_context:
                    summary: Get books
                    description: Get all books
                method: GET
                path: /books.{_format}
```

Does this work for you ?
