### ISSUE TITLE
OpenAPI is missing additionalProperties:false (when allow_extra_attributes=false)

### ISSUE THREAD

**Issue by guilliamxavier** [api-platform/core#4248]
**API Platform version(s) affected**: 2.6.4

**Description**  
(extracted from https://github.com/api-platform/core/issues/4215#issuecomment-819667033)
With default config + `denormalizationContext={"allow_extra_attributes": false}`, the generated OpenAPI schemas don't have `"additionalProperties": false`.

**How to reproduce**  
Config:
```yaml
api_platform:
    defaults:
        denormalization_context:
            allow_extra_attributes: false
```
and some dummy API resource.
Command (in a Symfony app): `php bin/console api:openapi:export`

**Possible Solution**  
Remove [this line](https://github.com/api-platform/core/blob/v2.6.4/src/OpenApi/Factory/OpenApiFactory.php#L154):
```php
            $schema->setDefinitions($schemas);
```
(introduced by a commit titled ["Improve openapi performances"](https://github.com/api-platform/core/pull/4138/commits/e5cf715f8662509e0263cb859e27cb0070215863)).

**Additional Context**  
Even #4247 doesn't fix it.
But if I customize the config by adding this:
```yaml
    formats:
        jsonld: ['application/ld+json']
    patch_formats:
        json: ['application/merge-patch+json']
```
then [well, I lose /docs.json and Swagger UI, but I can still run the command, and] the generated schemas *do* have `"additionalProperties": false` 🤔
