### ISSUE TITLE
URL syntax to check null value in dateFilter

### ISSUE THREAD

**Issue by 3kynox** [api-platform/core#431]
Hello, I created a dateFilter on nested object property (v1.1) : 

common json without filtering ...

```json
{
  "@context": "/app_dev.php/api/contexts/Echange",
  "@id": "/app_dev.php/api/echanges",
  "@type": "hydra:PagedCollection",
  "hydra:totalItems": 2,
  "hydra:itemsPerPage": 30,
  "hydra:firstPage": "/app_dev.php/api/echanges",
  "hydra:lastPage": "/app_dev.php/api/echanges",
  "hydra:member": [
    {
      "@id": "/app_dev.php/api/echanges/1",
      "@type": "Echange",
      "description": "Prise de contact avec la société Nucleus.",
      "type": {
        "@id": "/app_dev.php/api/type_echanges/1",
        "@type": "TypeEchange",
        "type": "Téléphonique"
      },
      "rdv": [],
      "entreprise": {
        "@id": "/app_dev.php/api/entreprises/1",
        "@type": "Entreprise",
        "enseigne": "Nucleus"
      },
      "interlocuteurs": null
    },
    {
      "@id": "/app_dev.php/api/echanges/2",
      "@type": "Echange",
      "description": "Conférence à trois. Demande de rendez-vous acceptée.",
      "type": {
        "@id": "/app_dev.php/api/type_echanges/2",
        "@type": "TypeEchange",
        "type": "Mail"
      },
      "rdv": [
        {
          "@id": "/app_dev.php/api/rendez_vouses/1",
          "@type": "RendezVous",
          "dateRendezVous": "2020-12-24T00:00:00+00:00"
        }
      ],
      "entreprise": {
        "@id": "/app_dev.php/api/entreprises/1",
        "@type": "Entreprise",
        "enseigne": "Nucleus"
      },
      "interlocuteurs": null
    }
  }
}
```

It returns two entries, one without 'rdv', and the other with 'rdv'. 'rdv' is a nested collection of meeting dates.

Now I set my dateFilter : 

```yml
    resource.rdv_filter:
        parent:    "api.doctrine.orm.date_filter"
        arguments: [ { "rdv.dateRendezVous": ~ } ]

    resource.echange:
        parent:    "api.resource"
        arguments: [ "Nucleus\\ProspectBundle\\Entity\\Echange" ]
        calls:
            - method:    "initNormalizationContext"
              arguments:  [{ groups: [ "echanges" ] }]
            - method:    "initDenormalizationContext"
              arguments:  [{ groups: [ "echanges" ] }]
            - method:    "initFilters"
              arguments: [ [ "@resource.rdv_filter" ] ]
        tags:      [ { name: "api.resource" } ]
```

If using in URL -> .../api/echanges?rdv.dateRendezVous[after]=2016

it returns only one record, that is ok : 

```json
{
  "@context": "/app_dev.php/api/contexts/Echange",
  "@id": "/app_dev.php/api/echanges?rdv.dateRendezVous[after]=2016",
  "@type": "hydra:PagedCollection",
  "hydra:totalItems": 1,
  "hydra:itemsPerPage": 30,
  "hydra:firstPage": "/app_dev.php/api/echanges?rdv_dateRendezVous%5Bafter%5D=2016",
  "hydra:lastPage": "/app_dev.php/api/echanges?rdv_dateRendezVous%5Bafter%5D=2016",
  "hydra:member": [
    {
      "@id": "/app_dev.php/api/echanges/2",
      "@type": "Echange",
      "description": "Conférence à trois. Demande de rendez-vous acceptée.",
      "type": {
        "@id": "/app_dev.php/api/type_echanges/2",
        "@type": "TypeEchange",
        "type": "Mail"
      },
      "rdv": [
        {
          "@id": "/app_dev.php/api/rendez_vouses/1",
          "@type": "RendezVous",
          "dateRendezVous": "2020-12-24T00:00:00+00:00"
        }
      ],
      "entreprise": {
        "@id": "/app_dev.php/api/entreprises/1",
        "@type": "Entreprise",
        "enseigne": "Nucleus"
      },
      "interlocuteurs": null
    }
  ],
  "hydra:search": {
    "@type": "hydra:IriTemplate",
    "hydra:template": "/app_dev.php/api/echanges{?rdv.dateRendezVous[before],rdv.dateRendezVous[after]}",
    "hydra:variableRepresentation": "BasicRepresentation",
    "hydra:mapping": [
      {
        "@type": "IriTemplateMapping",
        "variable": "rdv.dateRendezVous[before]",
        "property": "rdv.dateRendezVous",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "rdv.dateRendezVous[after]",
        "property": "rdv.dateRendezVous",
        "required": false
      }
    ]
  }
}
```

Now I need to have the contrary, get 'echanges' that do not have any 'rdv.dateRendezVous' (or empty 'rdv' collection).

Documentation show that it is possible to check if a date value is null, but [Date Filter](https://api-platform.com/doc/1.0/api-bundle/filters#date-filter) example is exactly the same given below at [Managing null values](https://api-platform.com/doc/1.0/api-bundle/filters#managing-null-values) with no URL description example to check null value.

My question, how to check null values on a date or non-existing property (on nested objects collection) ?

Thanks.
