### ISSUE TITLE
Unable to use config/api_platform/resources.yaml

### ISSUE THREAD

**Issue by smilesrg** [api-platform/core#4324]
**API Platform version(s) affected**: 2.6.4

**Description**  
In the documentation, there are examples pointing to `config/api_platform/resources.yaml` https://api-platform.com/docs/core/openapi/#using-the-openapi-and-swagger-contexts

**How to reproduce**  
Hotel class:
https://gist.github.com/smilesrg/dbfb061ab9a6fc88d26cc58da835e6fb

resources.yaml: 
https://gist.github.com/smilesrg/45a0849859e31970598ed4cbce98c220

You can use those files and take a look at the "Example" part of the generated documentation. `hotelNameUk` should be `one`, but it has value `string`. 

**Possible Solution**  
Update the documentation. Or fix the code.

**Additional Context**  
I'm using Doctrine MongoDB integration, removed Doctrine ORM completely.

**Comment by alanpoulain** [comment]
You can't use YAML configuration *and* attributes. You need to remove the `#[ApiResource]` attribute.

**Comment by smilesrg** [comment]
I removed that. Both `#[ApiResource]` and `#[ApiProperty]` attributes. Tried to use this content:
```yaml
resources:
    App\Document\Hotel:
        collectionOperations:
            get: ~ # nothing more to add if we want to keep the default controller
        itemOperations:
            get: ~
        properties:
            hotelId:
                identifier: true
            hotelNameUk:
                attributes:
                    openapi_context:
                        type: string
                        enum: ['one', 'two']
                        example: one
```

and this: 
```yaml
#resources:
App\Document\Hotel:
    collectionOperations:
        get: ~ # nothing more to add if we want to keep the default controller
    itemOperations:
        get: ~
    properties:
        hotelId:
            identifier: true
        hotelNameUk:
            attributes:
                openapi_context:
                    type: string
                    enum: ['one', 'two']
                    example: one

``` 

What I've got is: `No operations defined in spec!`

I tried to search `resources.yaml` in the vendor/api-platform/core directory, and it seems that this file is not used anywhere.

**Comment by smilesrg** [comment]
Done! Mappings to `api_platform.yaml` should be added.

https://api-platform.com/docs/core/getting-started/#product

```yaml
# api/config/packages/api_platform.yaml
api_platform:
    mapping:
        paths: 
            - '%kernel.project_dir%/src/Entity' # default configuration for annotations
            - '%kernel.project_dir%/config/api_platform' # yaml or xml directory configuration
```
It's a good idea to mention it in the provided examples.
