### ISSUE TITLE
JSON Schema is incorrect for associative array properties.

### ISSUE THREAD

**Issue by yoshz** [api-platform/core#4384]
**API Platform version(s) affected**: 2.6.5

**Description**  
JSON Schema is incorrect for associative array properties.

**How to reproduce**  
Define a property like:
```php
    /**
     * @var array<string,string>
     */
    private array $list = [];
```

Which results in generated JSON schema:
```yaml
        list:
          type: array
          items:
            type: string
```

Which should be:
```yaml
        list:
          type: object
          additionalProperties:
            type: string
```

**Possible Solution**  
I will submit a MR.

**Additional Context**
