### ISSUE TITLE
Security when using DataProvider

### ISSUE THREAD

**Issue by iva3682** [api-platform/core#4436]
**API Platform version(s) affected**: 2.6.5

**Description**  
I use api-platform in conjunction with Symfony 5.3. When you call the protected getCollection method from a custom DataProvider, the code in the method is executed and 401 code is returned. Expected that the code in this method will not be executed if the security settings do not allow it. Symfony 5.2 does not have this problem.

**How to reproduce**  
security.yaml:
```
    ...
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/
            security: true
            stateless: true
     ...
```

Entity.php:
```
...
 * @ApiResource(
 *     attributes={
 *         "security"="is_granted('ROLE_AUTH')"
 *     },
 *     collectionOperations={
 *          "markup"={
 *              "method"="GET",
 *              "path"="/products/markup",
 *              "normalization_context"={"groups"={"product:markup"}},
 *              "pagination_enabled"=true,
 *              "pagination_items_per_page"=1
 *          }
 *     },
 *     itemOperations={
 *          "get"
 *     }
 * )
 * ...
```
The same issue is described here: https://github.com/api-platform/core/issues/2694.

In my opinion, this is a serious security issue.

![image](https://user-images.githubusercontent.com/1547944/132682394-51b179b4-6632-4ff7-91df-cf87a3c3d088.png)
![image](https://user-images.githubusercontent.com/1547944/132682468-b4128524-ae70-40ff-98cf-73de932470dd.png)
