### ISSUE TITLE
Add configuration for Test Client

### ISSUE THREAD

**Issue by Lenny4** [api-platform/core#4459]
**Description** 
Api platform: 2.6.5
In `src/Bridge/Symfony/Bundle/Test/Client.php`
We have the default option for the client:
```php
public const API_OPTIONS_DEFAULTS = [
    'auth_basic' => null,
    'auth_bearer' => null,
    'query' => [],
    'headers' => ['accept' => ['application/ld+json']],
    'body' => '',
    'json' => null,
    'base_uri' => 'http://example.com',
    'extra' => [],
];
```
If we want to modify these options we have to create a client and then modify the options:
```php
use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase;

class MyClassTest extends ApiTestCase
{
    //...
    public function testMyTest(): void
    {
        $client = self::createClient();
        $client->setDefaultOptions([/*...*/]);
    }
}
```
Because these options could not be modify directly in the [configuration](https://api-platform.com/docs/core/configuration/)

Can I create a PR which will add these options in the configuration and then will automatically replace the default options ?
```yaml
# api/config/packages/api_platform.yaml
api_platform:
#...
    test:
        client:
            auth_basic: ~
            auth_bearer: ~
            query: ~
            headers: ~
            body: ~
            json: ~
            base_uri: ~
            extra: ~
#...
```
