### ISSUE TITLE
[Bridge/Symfony/Bundle] configurable asset package is not used for every asset

### ISSUE THREAD

**Issue by mkrauser** [api-platform/core#4469]
**API Platform version(s) affected**: 2.6.4 (for swagger-ui), all for graphiql and graphiql-playground

**Description**: The asset_path introduced in GH-3764 is not used for every asset

**How to reproduce**: Just set a base_path in your assets.yaml like this:

```yaml
framework:
    assets:
        base_path: '/whatever'
```

**Possible Solution**:  use the asset_package for every asset

**Additional Context**:  original issue #3760

I'll provide a PR for this
