### ISSUE TITLE
OpenAPI/Swagger does not reflect route prefixes

### ISSUE THREAD

**Issue by TheCrealm** [api-platform/core#4488]
**API Platform version(s) affected**: 2.7.x-dev

**Description**  
I use an `/api` route prefix for api since i started using api platform. On 2.7-x-dev swagger just drops this prefix.

`bin/console debug:router`: 
![image](https://user-images.githubusercontent.com/8281157/135968732-1aeb54c3-0ae2-4dee-9435-b874504cb00d.png)

`Swagger`:
![image](https://user-images.githubusercontent.com/8281157/135968658-b4529653-f8b5-465f-8d4b-7fa02fe53343.png)

**How to reproduce**  
Just use the following route config for api platform:
```
api_platform:
    resource: .
    type: api_platform
    prefix: /api
```

**Possible Solution**  
Somehow utilize the OperationPathResolver like before.

Old getPath function: https://github.com/api-platform/core/blob/2.6/src/OpenApi/Factory/OpenApiFactory.php#L343
New getPath function: https://github.com/api-platform/core/blob/main/src/OpenApi/Factory/OpenApiFactory.php#L327

**Additional Context**  
As i tried its more effort as just use it on the new system (or i am dumb rn). I currently did not figured out how to do a proper fix.

**Comment by alanpoulain** [comment]
Hello,

I've made a fix to manage it correctly, thanks for the report: https://github.com/api-platform/core/pull/4489.

However, using `prefix` is not doable anymore with the new metadata system (API Platform 2.7).

Please use:
```yaml
# api/config/packages/api_platform.yaml
api_platform:
    defaults:
        route_prefix: '/prefix'
```
See also:
- https://api-platform.com/docs/core/configuration/#global-resources-defaults
- https://api-platform.com/docs/core/operations/#prefixing-all-routes-of-all-operations
