### ISSUE TITLE
Patching Embedded Relation with application/merge-patch+json

### ISSUE THREAD

**Issue by ikamikaz3** [api-platform/core#4513]
Hello,

I have a problem when PATCH'ing a resource's collection using api platform, I'm not sure where the issue lies but here's my entities :
```
class Experience
{
    /**
     * @var Collection
     * @ORM\ManyToMany(targetEntity=AcquiredSkill::class, cascade={"persist"}, orphanRemoval=true)
     */
    private $acquiredSkills;
}
```

```
class AcquiredSkill
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Skill::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $skill;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $value;
}
```

```
class Skill
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;
}
```

My PATCH operation definition :
```
            patch:
                path: '/admin/surveys/answers/{id}'
                method: 'PATCH'
                denormalization_context:
                    groups: [ 'answer:patch', 'admin:answer:patch' ]
                normalization_context:
                    groups: [ 'answer:read', 'admin:answer:read' ]
```

Serialization groups:
```
App\Entity\Experience:
  attributes:
    acquiredSkills:
      groups: [ 'admin:student:answer:read', 'student:answer:read', 'answer:patch', 'answer:write', 'answer:read', 'survey:me' ]

App\Entity\AcquiredSkill:
  attributes:
    id:
      groups: [ 'admin:student:answer:read', 'student:answer:read', 'answer:read' ]
    skill:
      groups: [ 'admin:student:answer:read', 'student:answer:read', 'answer:patch', 'answer:write', 'answer:read', 'survey:me' ]
    value:
      groups: [ 'admin:student:answer:read', 'student:answer:read', 'answer:patch', 'answer:write', 'answer:read', 'survey:me' ]
```

Let's say my `Experience` already has a `acquiredSkill` with `id=30`.
This is my body for the patch to update my `acquiredSkill` array in the `Experience` entity :
```
{
  "experience": {
    "acquiredSkills": [
      {
        "@id": "/api/admin/acquired_skills/30",
        "skill": "/api/admin/skills/1",
        "value": "new value"
      }
    ]
  }
}
```
What I get as the response body is the following :
```
    "acquiredSkills": {
      "1": {
        "@id": "/api/admin/acquired_skills/31",
        "@type": "AcquiredSkill",
        "id": 31,
        "skill": "/api/admin/skills/1",
        "value": "string"
      }
    },
```
So first of all, the @id has changed, meaning that the `acquiredSkill` is a new entity : I have `orphanRemoval` setup in the `Experience` entity so I don't mind that it is not a real update.
My main issue tho, is that the `acquiredSkills` is now an object instead of an array ?
This seems very strange to me and it breaks my front-end aswell since it's obviously not meant to be an object.
Is my patch format wrong ? Or maybe my serialization groups ? I can't seem to find similar issues, so might aswell post it here.
