### ISSUE TITLE
SerializedName and other name converters are not applied in JSON-LD context serialization

### ISSUE THREAD

**Issue by kriswillis** [api-platform/core#4752]
**API Platform version(s) affected**: 2.6.8

**Description**  
Properties annotated with `#[SerializedName]` have their original name in the output of `/api/contexts/Entity`, other name converters are also not applied.

**How to reproduce** 
Configure camel case to snake case name converter…
```yaml
# /config/packages/api_platform.yaml
api_platform:
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
```
Create an ApiResource that has camel case properties and/or properties annotated with `#[SerializedName]`…
```php
#[ApiResource]
class Person
{
    #[ApiProperty(identifier: true)]
    private int $id;

    private string $familyName;

    private string $givenName;

    #[SerializedName('date_of_birth')]
    private DateTime $dob;

    #[Ignore]
    private bool $visible = true;
}
```
Query the API for the context…
```bash
# curl https://127.0.0.1:8000/api/contexts/Person -H 'Accept: application/ld+json' | jq
{
  "@context": {
    "@vocab": "https://127.0.0.1:8000/api/docs.jsonld#",
    "hydra": "http://www.w3.org/ns/hydra/core#",
    "familyName": "Person/familyName",
    "givenName": "Person/givenName",
    "dob": "Person/dob"
  }
}
```
`CamelCaseToSnakeCaseNameConverter` is not applied to `familyName` and `givenName`, nor is `#[SerializedName]` applied to `dob`. Interestingly, the `#[Ignore]` annotation *is* applied to the `visible` property.
