### ISSUE TITLE
Handling circular references with custom normalizer (continued)

### ISSUE THREAD

**Issue by TimothyDalbey** [api-platform/core#481]
I have a custom normalizer - and I attempted to follow your example in deploying a circular reference handler via the custom normalizer to results that were less than satisfactory.  Here's what I've been working with:

Custom Normalizer:

``` php
class CustomNormalizer extends AbstractNormalizer
{

    public function __construct(){

        parent::__construct();

        $this -> setCircularReferenceHandler(function ($object) {

            return json_encode(array('id' => $object -> getId()));

        });

    }
```

Service definitions:

``` yaml
framework:
    serializer:
        enabled: true
        enable_annotations: true
```

``` yaml
    zaius.customNormalizer:
        class: MHE\zaiusBundle\Service\CustomNormalizer
        tags: [ { name: serializer.normalizer, priority: 128 } ]
```

Entity (where the $parent is causing the circular reference):

``` php
class Projectgroup{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Groups({"object_view","group_index","group_view", "organization_view"})
     */
    protected $id;

    //-------------------------------------------------------------------------------

    /**
     * @ORM\OneToMany(targetEntity="Projectgroup", mappedBy="parent")
     * @Groups({"group_view"})
     **/
    private $children;

    /**
     * @ORM\ManyToOne(targetEntity="Projectgroup", inversedBy="children", cascade={"merge", "persist"})
     * @ORM\JoinColumn(name="parent_projectgroup_id", referencedColumnName="id")
     * @Groups({"object_view","group_index","group_view", "organization_view"})
     **/
    private $parent;
```

S2 version:

``` bash
root@c2d938a0b9d8:/tengu/Symfony# app/console --version
Symfony version 2.7.10 - app/dev/debug
```

Any guidance concerning what I might be doing wrong?
