### ISSUE TITLE
Missing field at Swagger doc

### ISSUE THREAD

**Issue by abelardolg** [api-platform/core#4840]
**API Platform version(s) affected**: x.y.z
"api-platform/core": "^2.6",
**Description**  

This is my  resources\User.yaml
```
App\Entity\User:
  attributes:
    normalization_context:
      groups: [user_read]
  collectionOperations:
    register:
      method: POST
      path: /users/register
      controller: App\Api\Action\User\Register
      denormalization_context:
        groups: [user_post]
      openapi_context:
        summary: Register a new user
  itemOperations:
    get:
      method: GET

```

This is my serialization\User.yaml:
```
App\Entity\User:
  attributes:
    id:
      groups: [user_read]
    name:
      groups: [user_read, user_post]
    email:
      groups: [user_read, user_post]
    password:
      groups: [user_post]
    avatar:
      groups: [user_read]
    active:
      groups: [user_read]
    createdAt:
      groups: [user_read]
    updatedAt:
      groups: [user_read]
```
This is the property $updatedAt inside the User entity:
![image](https://user-images.githubusercontent.com/22522883/179807141-6902f04e-d1ec-4708-9891-59dc4823719e.png)

Inside the mapping file:
![image](https://user-images.githubusercontent.com/22522883/179807257-bc2b0450-cb8f-4a6d-aea4-14f1fc8e13b1.png)

At the user table:
![image](https://user-images.githubusercontent.com/22522883/179807335-1950657f-10be-456d-a69f-d70bff0e69e1.png)

But, at the Swagger corner, nobody can't see it:
![image](https://user-images.githubusercontent.com/22522883/179807490-ec458f02-c30f-4215-ad68-5ff6ce422d4e.png)

I am following this Udemy (Spanish) video. As you can see, I have correctly executed those steps:
https://www.udemy.com/course/crear-api-con-symfony-y-api-platform/learn/lecture/21927682#overview

Working with Docker, Symfony "^5.1.0"

What's wrong? Best regards.
