### ISSUE TITLE
No identifier defined after bump to 2.7

### ISSUE THREAD

**Issue by ro0NL** [api-platform/core#4961]
Hi,

I've bumped a minor of this library:

````
Upgrading api-platform/core (v2.6.8 => v2.7.0)
````

My tests fail:

```
Symfony\Component\Config\Exception\LoaderLoadException:
No identifier defined in "App\Entity\Address".
You should add #[\ApiPlatform\Core\Annotation\ApiProperty(identifier: true)]" on the property identifying the resource." in . (which is being imported from "/app/config/routes/api_platform.yaml").
Make sure there is a loader supporting the "api_platform" type.
```

My YAML config did not change:

```yaml
App\Entity\Address:
    properties:
        id:
            identifier: true
    # ...
```
