### ISSUE TITLE
Metadata cache uses `ArrayAdapter` instead of APCu

### ISSUE THREAD

**Issue by usu** [api-platform/core#4975]
**API Platform version(s) affected**: 3.0.0

**Description**  
3.0 uses `ArrayAdapter` as Metadata Cache. In 2.7 the default was to utilize APCu when it was installed.

Was this changed by purpose? 

--> If **yes**, I couldn't find this documented. The [docu](https://api-platform.com/docs/core/performance/#enabling-the-metadata-cache) still says:

> If the Symfony Cache component is available (the default in the API Platform distribution), it automatically enables support for the best cache adapter available.

--> If **no**, I think the following commit introduced the issue:
https://github.com/api-platform/core/commit/c76720ebbbd9200ac9cda7dbff03de4b7c132189#

Or do I need to change any config on my side during 3.0 upgrade?

**How to reproduce**  
Upgrade to 3.0
Check symfony profiler for cache hit rate, which is significantly lower than before, as no Metadata is cached between separate requests.

**Comment by emmanuelballery** [comment]
Hi!

`registerCacheConfiguration` in the `ApiPlatformExtension` is indeed breaking the main caching abilities of our apps.

https://github.com/api-platform/core/blob/c76720ebbbd9200ac9cda7dbff03de4b7c132189/src/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L499-L511

In `prod` we lost the filesystem cache. `ArrayAdapter` is not enough. Removing those lines from `ApiPlatformExtension` is fixing this caching mecanism because `config/metadata/resource.xml` is referencing the `cache.system` (`adapter.filesystem` in prod).

https://github.com/api-platform/core/blob/c76720ebbbd9200ac9cda7dbff03de4b7c132189/src/Symfony/Bundle/Resources/config/metadata/resource.xml#L65-L67

For big apps, `dev` is really slow, as each required metadata is created once for each request, adding seconds to the clock. Opening Swagger UI is not possible (well xdebug stops us at 30 secondes) and exporting the full `openapi` schema is... difficult.

@alanpoulain I'm really sorry to bother you. Since  you worked on this, would you be king enough to take a look when you'll have the time and maybe guide us to help fix this.

Thank you!

**Comment by acirulis** [comment]
I have successfully migrated first project from 2.6 to 3.0 (Nice first impressions 👍) - however I immediately spotted significant drop in performance. Request, which took under 500ms now takes >1500ms on (ENV=dev, DEBUG=true) and also takes 400ms vs 200ms on (ENV=prod, debug=false). 
I am using Redis Cache adapter for Symfony, no changes in configuration between 2.6 and 3.0. 

It seems that changes mentioned by @emmanuelballery - `registerCacheConfiguration` in the `ApiPlatformExtension` helps to bring back performance to normal.

**Comment by webda2l** [comment]
> I have successfully migrated first project from 2.6 to 3.0 (Nice first impressions +1) - however I immediately spotted significant drop in performance. Request, which took under 500ms now takes >1500ms on (ENV=dev, DEBUG=true) and also takes 400ms vs 200ms on (ENV=prod, DEBUG=false). I am using Redis Cache adapter for Symfony, no changes in configuration between 2.6 and 3.0.
> 
> It seems that changes mentioned by @emmanuelballery - `registerCacheConfiguration` in the `ApiPlatformExtension` helps to bring back performance to normal.

In dev, https://symfony.com/blog/new-in-symfony-6-1-serializer-profiling come at cost but there is definitely a performance issue related to the cache with the 3.0.

**Comment by acirulis** [comment]
Oh nice, @webda2l - since I started project with 6.0, after upgrade to 6.1 Serializer Profiling was disabled by default. After your mention I enabled it & it will be great tool for debugging. Performance impact is minimal.

**Comment by emmanuelballery** [comment]
Meanwhile, you can avoid this performance issue by overriding api platform cache in your `services.yaml`:

```yaml
services:
    api_platform.cache.metadata.property:
        parent: cache.system
        tags: [ cache.pool ]
    api_platform.cache.metadata.resource:
        parent: cache.system
        tags: [ cache.pool ]
    api_platform.cache.metadata.resource_collection:
        parent: cache.system
        tags: [ cache.pool ]
    api_platform.cache.route_name_resolver:
        parent: cache.system
        tags: [ cache.pool ]
    api_platform.cache.identifiers_extractor:
        parent: cache.system
        tags: [ cache.pool ]
    api_platform.elasticsearch.cache.metadata.document:
        parent: cache.system
        tags: [ cache.pool ]
```

**Comment by MrSpider** [comment]
The service `api_platform.metadata.property.identifier_metadata_factory` which is suggested to be removed in 3.0 by a TODO comment (`TODO: in 3.0 the serializer property metadata factory doesn't need the resource metadata anymore so these will be removed`) has no cache associated with it.

After adding a simple array cache for this service the performance significantly improves when the metadata caches are rebuilt.

    # Speeds up api-platform cache build substantially
    # May have to be removed soon when api-platform removes these services
    # see vendor/api-platform/core/src/Symfony/Bundle/Resources/config/metadata/property.xml:41
    api_platform.cache.metadata.identifier:
        parent: cache.adapter.array
        tags: [ cache.pool ]
    api_platform.metadata.property.identifier_metadata_factory.cached:
        class: ApiPlatform\Metadata\Property\Factory\CachedPropertyMetadataFactory
        decorates: api_platform.metadata.property.identifier_metadata_factory
        decoration_priority: 99
        arguments:
            - '@api_platform.cache.metadata.identifier'
            - '@api_platform.metadata.property.identifier_metadata_factory.cached.inner'

**Comment by soyuka** [comment]
Is there something I can do to help with this?

**Comment by acirulis** [comment]
Ok, I think we got to the bottom of this - back in 2016 there was PR introducing ArrayAdapter for dev environment ( https://github.com/api-platform/core/pull/653 ) because Symfony 2.x required to manually clear cache after every configuration change. Current version of Symfony does it automatically and it would be ok to remove Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php:registerCacheConfiguration() method altogether and rely on framework cache config.

**Comment by soyuka** [comment]
Nice @acirulis do you have some time to open a patch? 

Shouldn't we also fix our services to inline with:

```
services:
    api_platform.cache.metadata.property:
        parent: cache.system
        tags: [ cache.pool ]
    api_platform.cache.metadata.resource:
        parent: cache.system
        tags: [ cache.pool ]
    api_platform.cache.metadata.resource_collection:
        parent: cache.system
        tags: [ cache.pool ]
    api_platform.cache.route_name_resolver:
        parent: cache.system
        tags: [ cache.pool ]
    api_platform.cache.identifiers_extractor:
        parent: cache.system
        tags: [ cache.pool ]
    api_platform.elasticsearch.cache.metadata.document:
        parent: cache.system
        tags: [ cache.pool ]
```
