### ISSUE TITLE
[2.7.0] ApiResource output data-transformers are not called in a relationship context anymore

### ISSUE THREAD

**Issue by ambroisemaupate** [api-platform/core#4988]
**API Platform version(s) affected**: 2.7.0

### Description

I've registered an ApiResource only for read item operation:

```yaml
App\GeneratedEntity\NSGalleryBlock:
    iri: GalleryBlock
    shortName: GalleryBlock
    collectionOperations: {  }
    attributes:
        output: App\Api\Dto\GalleryBlockOutput
    itemOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - nodes_sources
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
```

Then I've got another resource which will store relationships to differents kind of resources:

```yaml
App\Model\WebResponse:
    collectionOperations: {}
    itemOperations:
        getByPath:
            method: 'GET'
            path: '/web_response_by_path'
            read: false
            controller: RZ\Roadiz\CoreBundle\Api\Controller\GetWebResponseByPathController
            pagination_enabled: false
            normalization_context:
                pagination_enabled: false
                groups:
                    - get
                    - web_response
                    - nodes_sources
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
```

---

#### Direct resource call

If I call item operation for `NSGalleryBlock` resource directly, for example: 
```http
GET /api/gallery_blocks/2811
``` 
then `GalleryBlockOutputDataTransformer` is automatically called to hydrate `GalleryBlockOutput` DTO.
![image](https://user-images.githubusercontent.com/380026/191235247-a669cfd8-9a38-4a70-b276-db5d83913c2f.png)

**`media` property is populated by `GalleryBlockOutputDataTransformer`**

#### Indirect resource call
If I call item operation for `WebResponse` resource, for example
```http
GET /api/web_response_by_path?path=/path-to-my-web-response
```
and this `WebResponse` holds a relationship to `/api/gallery_blocks/2811` then `GalleryBlockOutputDataTransformer` is not called anymore! Only `WebResponseDataTransformer` is called because it is the main resource class for this operation.
![image](https://user-images.githubusercontent.com/380026/191235113-4a9d111d-6a36-441a-a6ed-43f8e6520856.png)

**`media` property cannot be populated by `GalleryBlockOutputDataTransformer`**, it remains empty

### Possible Solution
This worked on 2.6.x because `InputOutputMetadataTrait` was getting `output` class from current normalizing object metadata, not the current operation context.

https://github.com/api-platform/core/blob/2.6/src/Serializer/InputOutputMetadataTrait.php#L48
