### ISSUE TITLE
Can't use ODM and ORM together

### ISSUE THREAD

**Issue by Oskmoz** [api-platform/core#5020]
Hi, 

I'm facing a problem on my application using both an SQL and a MongoDB database.
Using only the SQL databases with ORM and PHP attributes everything works fine. 
However, as soon as I `composer require doctrine/mongodb-odm-bundle` (Tried with many versions), the POST resources break and I'm unable to POST anything. I tried with ODM annotations and attributes, this doesn't fix the issue.

Here is the doctrine_mongodb.yaml I am using :

Is there any solution to make attributes and resource work both with Documents and Entities ?

```
doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}
    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            # auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App

```
![bug](https://user-images.githubusercontent.com/44194350/192831372-21a71452-55b5-44ee-9171-ec61556223fd.png)
