### ISSUE TITLE
"shortName" setting is expected to be null or an array, string given in 

### ISSUE THREAD

**Issue by wouter-toppy** [api-platform/core#5117]
**API Platform version(s) affected**: 3.0.0

**Description**  
Error when setting the shortName on a ApiResource using yaml
`"shortName" setting is expected to be null or an array, string given` 

**How to reproduce**  

Have a resource with the shortName (or description) manually set. 

Resource: 
```yaml
Toppy\Bundle\PurchaseBundle\Entity\PurchaseOrder\Item:
    shortName: 'PurchaseOrderItem'
    operations:
        ApiPlatform\Metadata\Get: ~
```

**Possible Solution**  

The [YamlPropertyExtractor.php:66](https://github.com/api-platform/core/blob/main/src/Metadata/Extractor/YamlPropertyExtractor.php#L66) expects everything to be an array, thats not true as far as I can see. 

**Additional Context**  

Symfony 6.2
PHP 8.1
