### ISSUE TITLE
2.7.3 ignores the `route_prefix` prefix settings

### ISSUE THREAD

**Issue by DarkChyper** [api-platform/core#5179]
Hello,
I found this message in a closed issue named "Issues found on 2.7" because i reproduce this issue with 2.7.3 (SF 4.4.45 PHP 7.4)

`route_prefix` is still ignored when i try to migrate from 2.6 to 2.7 (cannot go to 3.x now).

I don't find any fix for this (but i'm not good to read PR, i could miss it)

edit: it works if i add setting on each resource : 
config/api/resources/myresource.yaml
```
resources:
  My\Resource:
    routePrefix: 'v2'
```
        @soyuka, it seems the latest version ignores the `route_prefix` prefix settings

config/packages/api_platform.yaml

```
api_platform:
...
    metadata_backward_compatibility_layer: false
    openapi:
        backward_compatibility_layer: false
    defaults:
        route_prefix: '/api'
```

`GET /users/{id} Retrieves a User resource.`
Instead of
`GET /api/users/{id} Retrieves a User resource.`

Tested with d876e6638acad4b82887a4f93fd4eca361584d00

_Originally posted by @lermontex in https://github.com/api-platform/core/issues/4613#issuecomment-1126735174_

**Comment by DarkChyper** [comment]
Thanks for the answer ! 

I'll try to provide a reproducer, maybe the issue come from something with symfony 4.4.45 or yaml serializer (we don't use annotation on entities)

**Comment by vincentchalamon** [comment]
Ah ok, it changes some things indeed. I can now reproduce the bug using the following configuration:

```yaml
resources:
    App\Entity\Greeting:
        routePrefix: v2
    App\Entity\Book: ~
```

I only have the bug on API Platform 2.7, not on 3.0
