### ISSUE TITLE
ArrayDenormalizer ignores configured normalizers after upgrade to 2.7

### ISSUE THREAD

**Issue by PawelSuwinski** [api-platform/core#5198]
Hi

After upgrade from 2.6 to 2.7 (as a first step to 3.0) deserialization of array with custom serializer service has stoped working. And I am wonder is it a bug or I miss something. At that moment I am still try to figure out why it is now working in different way, some hint may save a day.

In a state provider I need to use `PropertyNormalizer` to populate private resource id field. 

```yaml
# config/services.yml
(...)
    property_serializer:
        # Needed to prevent replacement of default serializer service.
        autoconfigure: false
        class: Symfony\Component\Serializer\Serializer
        arguments:
            - ['@serializer.normalizer.property', '@serializer.denormalizer.array']
            - ['@serializer.encoder.json']
       
     App\State\SyncedCollectionProvider:
        decorates: 'api_platform.state_provider'
        autoconfigure: false
        arguments:
            $decorated: '@.inner'
            $serializer: '@property_serializer'
       (...)
```

```php
class SyncedCollectionProvider implements ProviderInterface
(...)
   public function provide(Operation $operation, array $uriVariables = [], array $context = [])
    {
        $resourceClass = $operation->getClass();
        (...)
         var_dump($data, $serializer->deserialize($data, $resourceClass.'[]', 'json'));
         var_dump($data2, $serializer->deserialize($data2, $resourceClass, 'json'));
```
gives

```
string(89) "[{"id":5984,"name":"translate"}]"
array(1) {
  [0]=>
  object(App\Generated\Entity\Workflow)#2725 (2) {
    ["id":"App\Generated\Entity\Workflow":private]=>
    NULL
    ["name":"App\Generated\Entity\Workflow":private]=>
    string(9) "translate"
  }
}
string(87) "{"id":5984,"name":"translate"}"
object(App\Generated\Entity\Workflow)#2725 (2) {
  ["id":"App\Generated\Entity\Workflow":private]=>
  int(5984)
  ["name":"App\Generated\Entity\Workflow":private]=>
  string(9) "translate"
}
```

Denormalizing of single item work fine - `PropertyNormalizer` is used as configured, but doing same with array of this items does not work. In theory  in this case `ArrayDenormalizer` should came in to play that after all should use `PropertyNormalizer` for denormalizing of single item within a loop because only this one is available in this particular serializer service, but it seems that it uses `ItemNormalizer` for that (?). Any hints?

**Comment by PawelSuwinski** [comment]
Solved, `@serializer.denormalizer.array` is shared service and somehow new set of config (profiler?) cause that it contains main serializer service with all its normalizers, so this brings it make work as previous:

```yaml
# config/service.yml
(...)
    property_serializer:
        autoconfigure: false
        class: Symfony\Component\Serializer\Serializer
        arguments:
            -
                - '@serializer.normalizer.property'
                - !service
                    class: Symfony\Component\Serializer\Normalizer\ArrayDenormalizer
            - ['@serializer.encoder.json']

```
