### ISSUE TITLE
Cannot define a v2.7 resource via YAML

### ISSUE THREAD

**Issue by lifo101** [api-platform/core#5230]
**API Platform version(s) affected**: 2.7

**Description**  
Cannot define a v2.7 "sub-resource" linkage or other custom properties via YAML. Using PHP Attributes works fine. See issue #5117 for similar information. I cannot try this in v3.0 yet, but looking at the core code it seems the related yaml extraction code is the same.

**How to reproduce**  
YAML config to reproduce the error.
```yaml
App\Entity\Preview:
  uriTemplate: '/documents/{id}/previews'
  uriVariables:
    id:
      toProperty: 'document'
      fromClass: App\Entity\Document
  operations:
    ApiPlatform\Metadata\GetCollection: ~
```

If I define a similar resource using PHP Attributes, it works fine
```php
#[ApiResource]
#[ApiResource(
    uriTemplate: '/documents/{id}/previews',
    operations: [ new GetCollection() ],
    uriVariables: [
        'id' => new Link(toProperty: 'document', fromClass: Document::class)
    ]
)]
class Preview
```

**Possible Solution**  
Using arbitrary key names in the YAML config almost works, but it doesn't really collect all the properties
```yaml
App\Entity\Preview:
  preview: ~
  document_previews:
    uriTemplate: '/documents/{id}/previews'
    uriVariables:
      id:
        toProperty: 'document'
        fromClass: App\Entity\Document
    operations:
      ApiPlatform\Metadata\GetCollection: ~
```

**Additional Context**

**Comment by soyuka** [comment]
works at https://github.com/api-platform/core/blob/main/tests/Fixtures/TestBundle/Resources/config/api_resources_orm/resources.yaml#L7 is there something different in your case? can we see some errors?

**Comment by lifo101** [comment]
The main error was:

     "uriTemplate" setting is expected to be null or an array, string given.

But I realize now thanks to your test yaml config above I did in fact need to use an array to define the config. So, I'm not currently getting any errors, but the route is not being generated for the sub-resource. Not sure what I'm doing wrong.

 This is what I have:

```yaml
App\Bundle\Entity\Preview:
  - ~
  - uriTemplate: '/documents/{id}/previews'
    uriVariables:
      id:
        fromClass: App\Bundle\Entity\Document
        toProperty: 'document'
    operations:
      ApiPlatform\Metadata\GetCollection: ~
```

There is no route for ```/api/documents/{id}/previews```

	/var/www/docs_dev$ rm -rf var/cache/dev/*; off;bin/console debug:router | grep -i documents
	  documents                                ANY              ANY      ANY    /
	  api_documents_get_collection             GET              ANY      ANY    /api/documents.{_format}
	  api_documents_post_collection            POST             ANY      ANY    /api/documents.{_format}
	  api_documents_get_item                   GET              ANY      ANY    /api/documents/{id}.{_format}
	  api_documents_delete_item                DELETE           ANY      ANY    /api/documents/{id}.{_format}
	  api_documents_put_item                   PUT              ANY      ANY    /api/documents/{id}.{_format}
	  api_documents_patch_item                 PATCH            ANY      ANY    /api/documents/{id}.{_format}

	/var/www/docs_dev$ off;bin/console router:match /api/documents/1/previews
	 [ERROR] None of the routes match the path "/api/documents/1/previews"
	

However, if I define the resources using #[ApiResource] attributes (as shown in my original post) then it works fine and I get the route (albeit the route name is all screwy in 2.7|3.0)

	/var/www/docs_dev$ rm -rf var/cache/dev/*; off;bin/console debug:router | grep -i documents
	  _api_/documents/{id}/previews_get_collection   GET              ANY      ANY    /api/documents/{id}/previews
