### ISSUE TITLE
Resource configuration is in wrong case

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/core#5321]
## Description

Using YAML or XML, the global configuration is in the following case:
```yaml
api_platform:
    defaults:
        pagination_client_enabled: true
```

But any resource configuration is in the following case:
```yaml
resources:
    App\Entity\Book:
        paginationClientEnabled: true
```
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<resources
     xmlns="https://api-platform.com/schema/metadata/resources-3.0"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://api-platform.com/schema/metadata/resources-3.0
     https://api-platform.com/schema/metadata/resources-3.0.xsd">
 <resource class="App\Entity\Book" paginationClientEnabled=true />
</resources>
```

## Proposition

Following Symfony Best Practices, the configuration should be as following:
```yaml
resources:
    App\Entity\Book:
        pagination_client_enabled: true
```
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<resources
     xmlns="https://api-platform.com/schema/metadata/resources-3.0"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://api-platform.com/schema/metadata/resources-3.0
     https://api-platform.com/schema/metadata/resources-3.0.xsd">
 <resource class="App\Entity\Book" pagination-client-enabled=true />
</resources>
```
