### ISSUE TITLE
Extend property metadata accessors

### ISSUE THREAD

**Issue by klobastov** [api-platform/core#5336]
**Description**  
Method ExtractorPropertyMetadataFactory::update does not allow set property like push:true in yaml config.

Property descripton applied, because accessor in list. But another properties cant be set

![image](https://user-images.githubusercontent.com/3277751/212277078-f12875c5-154b-4bff-ba4f-d86cd6af2456.png)

**Example**  
```
resources:
  Gate\Entity\Gate:
    order:
      serialId: ASC

    normalizationContext:
      groups: [ 'gate:output' ]
    denormalizationContext:
      groups: [ 'gate:input' ]

    operations:
      gate_list:
        class: 'ApiPlatform\Metadata\GetCollection'
        filters: [ 'default.id', 'default.name' ]
        security: is_granted('GATE_LIST', object)

      gate_view:
        class: 'ApiPlatform\Metadata\Get'
        security: is_granted('GATE_LIST', object)

      gate_create:
        class: 'ApiPlatform\Metadata\Post'
        security: is_granted('GATE_CREATE', object)

      gate_update:
        class: 'ApiPlatform\Metadata\Put'
        security: is_granted('GATE_UPDATE', object) and (previous_object.getCreatedBy() === user.getUsername() or is_my_storehouse(object.getStoreHouse().getId() ?? null))

      gate_update_partial:
        class: 'ApiPlatform\Metadata\Patch'
        security: is_granted('GATE_UPDATE', object) and (previous_object.getCreatedBy() === user.getUsername() or is_my_storehouse(object.getStoreHouse().getId() ?? null))

      gate_delete:
        class: 'ApiPlatform\Metadata\Delete'
        security: is_granted('GATE_CREATE', object) and (previous_object.getCreatedBy() === user.getUsername() or is_my_storehouse(object.getStoreHouse().getId() ?? null))

properties:
  Gate\Entity\Gate:
    storeHouse:
      description: test1
      push: true
```
