### ISSUE TITLE
Default operations doesn't work anymore

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#5399]
API Platform 2.x on peut faire ca dans la configuration globale:

```
# api_platform.yaml

...
defaults:
  operations:
    - get
    - post
```

c'est pas mal pour que API Platform génère pas un CRUD par défaut mais que quelques routes.

Il faudrait réparer ca en 3.x ca donne:

```yaml
defaults:
  operations:
    - ApiPlatform\Metadata\Get
    - ApiPlatform\Metadata\Post
```

Et dans le code les défaults ils devraient être utilisés dans `AttributesResourceMetadataCollectionFactory`
