### ISSUE TITLE
Resource properties configuration in YAML doesn't work

### ISSUE THREAD

**Issue by maxtorete** [api-platform/core#5482]
**API Platform version(s) affected**:  3.1.0

**Description**  
I tried to set the openapiContext property in a Yaml file, but it doesn't work. It woks fine in XML, even if I set the resource in a YAML file and the properties in XML. 

**How to reproduce**  
Try this conf [from docs](https://api-platform.com/docs/core/openapi/#using-the-openapi-and-swagger-contexts):
```yaml
properties:
    App\Entity\Product:
        timestamp:
            attributes:
                openapiContext:
                    type: string
                    format: date-time
```
Property's openapiContext configuration is ignored. And then try the same configuration but in XML format, also taken from docs:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- api/config/api_platform/properties.xml -->

<properties xmlns="https://api-platform.com/schema/metadata/properties-3.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://api-platform.com/schema/metadata/properties-3.0
           https://api-platform.com/schema/metadata/properties-3.0.xsd">
    <property resource="App\Entity\Product" name="timestamp">
        <openapiContext>
            <values>
                <value name="type">string</value>
                <value name="format">date-time</value>
            </values>
        </openapiContext>
    </property>
</properties>
```
And this one works just fine. Resource shows the date-time format for timestamp property in SwaggerUI.

PS: I also tried removing the `attributes` key as I don't see it on YamlPropertyExtractor, but it doesn't work either.

![image](https://user-images.githubusercontent.com/1867132/226718639-11846fe6-c3d3-460b-acb7-7fdfe28e5ac6.png)
