### ISSUE TITLE
Invalid constructor arguments with ES document normalizer and default serializer context

### ISSUE THREAD

**Issue by dannyvw** [api-platform/core#5483]
**API Platform version(s) affected**: 3.1.2

**Description**  
When configure a default context for the serializer inside the Symfony framework configuration the following error occurred.

`Invalid constructor argument 8 for service "api_platform.elasticsearch.normalizer.document": argument 7 must be defined before. Check your service definition.`

**How to reproduce**  
Add default_context configuration

```yaml
framework:
    serializer:
        default_context:
            datetime_format: 'Y-m-d'
```
