### ISSUE TITLE
[FR] Add ability to alter Processor context

### ISSUE THREAD

**Issue by kissifrot** [api-platform/core#5507]
**Description**  
Hello,

I'm using API ¨Platform 3.1.x, and I'm using the SerializerContextBuilderInterface::createFromRequest method to add context used by Providers (mainly to avoid injecting symfony's RequestStack service inside providers to retrieve specific request's headers).

However, on Processor side this whole context is lost, and we only have `operation`, `resource_class` and `previous_data`.
Would it be possible to add a way to populate this "write" context too?

**Example**  
(dunno)

**Comment by soyuka** [comment]
Can you explain your use case? I see multiple solutions, injecting the RequestStack is not a problem, you could even have some kind of `RequestProcessor`. We're going to introduce a bunch of them soon (see https://github.com/api-platform/core/pull/4655#issuecomment-1488710998)

**Comment by kissifrot** [comment]
> Can you explain your use case? I see multiple solutions, injecting the RequestStack is not a problem, you could even have some kind of `RequestProcessor` that you're decorating. We're going to introduce a bunch of them soon (see [#4655 (comment)](https://github.com/api-platform/core/pull/4655#issuecomment-1488710998))

That's we're doing in the meanwhile (injecting RequestStack), but headers filtering were done in the SerializerContextBuilderInterface, so we have to redo it again when getting raw information from the request in the Processor.

We use currency conversion, so user's currency is given in a header to the API, so the output results do the correct currency conversion.
So we do not use it in the Processor itself, but more when outputing modified result (through DTOs)

I hope that's clear enough 😅

**Comment by soyuka** [comment]
Use request attributes? I understand the issue I see many people with something related I'll consider but probably that https://github.com/api-platform/core/pull/4655 will make that change

**Comment by kissifrot** [comment]
@soyuka Maybe I'm mistaken, but upgraded to 3.2 and it's not available on Processor side.
Is there a config to add?

**Comment by soyuka** [comment]
Did you `composer recipes:update` ? Can you show me your API Platform config (use `debug:config api_platform`)

**Comment by kissifrot** [comment]
> Did you `composer recipes:update` ? Can you show me your API Platform config (use `debug:config api_platform`)

I forgot to do it, by bad 😅 
However it does not seem to have any effect, I still have the 3 "usual" keys (`operation`, `resource_class `and `previous_data`) in `$context`.

Here is my APIP config :
```
api_platform:
    title: 'API'
    description: 'API'
    version: 1.0
    show_webby: false
    enable_swagger_ui: true
    mapping:
        paths:
            - [REDACTED]
    formats:
        json:
            mime_types:
                - application/json
        jsonld:
            mime_types:
                - application/ld+json
        xml:
            mime_types:
                - application/xml
                - text/xml
        html:
            mime_types:
                - text/html
    swagger:
        versions:
            - 3
        api_keys:
            apiKey:
                name: Authorization
                type: header
        swagger_ui_extra_configuration: {  }
    http_cache:
        public: true
        invalidation:
            enabled: false
            varnish_urls: {  }
            urls: {  }
            scoped_clients: {  }
            max_header_length: 7500
            request_options: {  }
            purger: api_platform.http_cache.purger.varnish
            xkey:
                glue: ' '
    defaults:
        stateless: true
        collect_denormalization_errors: true
        pagination_enabled: true
        pagination_items_per_page: 100
        normalization_context:
            skip_null_values: false
        formats:
            - json
            - jsonld
            - xml
        cache_headers:
            etag: true
            max_age: 0
            shared_max_age: 0
            vary:
                - Content-Type
                - Origin
                - Accept-Language
                - Accept-Currency
                - [REDACTED]
                - [REDACTED]
                - [REDACTED]
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        event_listeners_backward_compatibility_layer: false
        keep_legacy_inflector: false
    event_listeners_backward_compatibility_layer: true
    name_converter: null
    asset_package: null
    path_segment_name_generator: api_platform.metadata.path_segment_name_generator.underscore
    validator:
        serialize_payload_fields: {  }
        query_parameter_validation: true
    eager_loading:
        enabled: true
        fetch_partial: false
        max_joins: 30
        force_eager: true
    enable_swagger: true
    enable_re_doc: true
    enable_entrypoint: true
    enable_docs: true
    enable_profiler: true
    keep_legacy_inflector: true
    collection:
        exists_parameter_name: exists
        order: ASC
        order_parameter_name: order
        order_nulls_comparison: null
        pagination:
            enabled: true
            page_parameter_name: page
            enabled_parameter_name: pagination
            items_per_page_parameter_name: itemsPerPage
            partial_parameter_name: partial
    resource_class_directories: {  }
    doctrine:
        enabled: true
    doctrine_mongodb_odm:
        enabled: false
    oauth:
        enabled: false
        clientId: ''
        clientSecret: ''
        pkce: false
        type: oauth2
        flow: application
        tokenUrl: ''
        authorizationUrl: ''
        refreshUrl: ''
        scopes: {  }
    graphql:
        enabled: false
        default_ide: graphiql
        graphiql:
            enabled: false
        graphql_playground:
            enabled: false
        introspection:
            enabled: true
        nesting_separator: _
        collection:
            pagination:
                enabled: true
    mercure:
        enabled: false
        hub_url: null
        include_type: false
    messenger:
        enabled: true
    elasticsearch:
        enabled: false
        hosts: {  }
        mapping: {  }
    openapi:
        contact:
            name: null
            url: null
            email: null
        termsOfService: null
        license:
            name: null
            url: null
        swagger_ui_extra_configuration: {  }
    maker:
        enabled: true
    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        ApiPlatform\Exception\InvalidArgumentException: 400
        ApiPlatform\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409
    patch_formats:
        json:
            mime_types:
                - application/merge-patch+json
    docs_formats:
        jsonopenapi:
            mime_types:
                - application/vnd.openapi+json
        yamlopenapi:
            mime_types:
                - application/vnd.openapi+yaml
        json:
            mime_types:
                - application/json
        jsonld:
            mime_types:
                - application/ld+json
        html:
            mime_types:
                - text/html
    error_formats:
        jsonproblem:
            mime_types:
                - application/problem+json
        jsonld:
            mime_types:
                - application/ld+json
```
