### ISSUE TITLE
[OpenAPI] The OpenAPI specification produced by 2.7/3.0 differs from 2.6

### ISSUE THREAD

**Issue by welcoMattic** [api-platform/core#5537]
**API Platform version(s) affected**: 2.7.x and 3.x

**Description**  
The output of `bin/console api:openapi:export` in 2.7/3.0 differs from the output in 2.6.

**How to reproduce**  
Run `bin/console api:openapi:export` in an app with API Platform 2.6, the result looks like:

```yaml
paths:
  '/my-api/v1/deliveries/{id}':
    get:
      operationId: getDeliveryItem
```

Run `bin/console api:openapi:export` in an app with API Platform 2.7 or 3.0, the result looks like:

```yaml
paths:
  '/my-api/v1/deliveries/{id}':
    get:
      operationId: api_deliveries_id_get
```

This change will totally break tools that use the openapi.yaml file from my API to build a client for instance. In fact, we use https://github.com/acacode/swagger-typescript-api, to generate a TypeScript client using openapi.yaml. The new version of the spec will generate a client where all methods names change, which totally break our TS code. However, the API doesn't changed a bit, except the API Platform version.

It seems that it is only the generation of operation names that breaks the compatibility between versions 2.6 and 2.7/3.0.

Could we consider this as a critical BC Break in 2.7/3.0?

**Additional Context**  
This issue https://github.com/api-platform/core/issues/5232 should never been closed. Even the produced JSON/JSON-LD is the same, the generated OpenAPI spec differs.
