### ISSUE TITLE
array of IRIs

### ISSUE THREAD

**Issue by Fercho191** [api-platform/core#557]
Hello everyone.
I have a problem with my API and you do not get solution

this is one of the entities
![documentacion](https://cloud.githubusercontent.com/assets/13698504/15683713/b607ab74-2731-11e6-9c0e-be95856c099c.png)

in my schema.yml is written as follows

```
properties:
      languages: { range: "language", cardinality: (0..*)}
      writingExpertise: { range: "Rating", cardinality: (0..1)}
      expertiseSpokenLanguage: { range: "Rating", cardinality: (0..1)}
      levelOfAdaptation: { range: "Rating", cardinality: (0..1)}
      employee: { range: "Person", cardinality: (1..1)}
```

I am using for testing Postman, I'm trying to persist in the languages attribute data
![error](https://cloud.githubusercontent.com/assets/13698504/15683992/165a52f0-2733-11e6-9e6c-31c1c3a976b9.png)

It does not say that there is error, but no values are stored. I have tried several ways but does not work and do not understand why

Someone help me?

Thanks in advance
