### ISSUE TITLE
Messenger not working if using processor on same resource

### ISSUE THREAD

**Issue by DurandA** [api-platform/core#5772]
**API Platform version(s) affected**: 3.1

**Description**  
When a resource use both the messenger and a custom processor, either the messages are not created if using `messenger=true`, or the processor is not called if using `messenger='input'`.

**How to reproduce**  
```php
#[ORM\Entity]
#[ApiResource(
    operations: [
        new Post(
            processor: MyEntityProcessor::class,
            messenger: 'input',
            deserialize: false, 
        )
    ]
)]
class MyEntity
{
}
```

```php
final class MyEntityProcessor implements ProcessorInterface
{
    public function __construct(private ProcessorInterface $persistProcessor)
    {
    }

    public function process($data, Operation $operation, array $uriVariables = [], array $context = [])
    {
        $result = $this->persistProcessor->process($data, $operation, $uriVariables, $context);
        return $result;
    }
}
```

**services.yaml**
```yml
services:
    App\State\MyEntityProcessor:
        bind:
            $persistProcessor: '@api_platform.doctrine.orm.state.item_provider'
```

**messenger.yaml**
```yml
framework:
    messenger:
        transports:
            async: 'doctrine://default'

        routing:
            'App\Entity\MyEntity': async
```

**Additional Context**
I need to generate thumbnails on MediaObjects after creation. I want to use Symfony Messenger to trigger this and do it asynchronously since it could take time some to process.

The processor is used to persists the entity. As described in [Symfony Messenger Integration](https://api-platform.com/docs/core/messenger/#dispatching-a-resource-through-the-message-bus):
> Note: when using `messenger=true` ApiResource attribute in a Doctrine entity, the Doctrine Processor is not called. If you want the Doctrine Processor to be called, you should [decorate a built-in state processor](https://api-platform.com/docs/core/state-processors#decorating-the-built-in-state-processors) and implement your own logic.
