### ISSUE TITLE
JSON-LD failing after update 2.6 -> 2.7 with "No resource class found..."

### ISSUE THREAD

**Issue by mmoll** [api-platform/core#5812]
**API Platform version(s) affected**: 2.7.15

Because of the complexity and layering of the application, updating to 3.0 is not simple and a working version using API Platform 2.7 with `metadata_backward_compatibility_layer: true` will be needed as first step.

**Description**  

After updating API platform from 2.6.x to 2.7, one endpoint exposes a problem when requesting JSON-LD (JSON works fine). The configuration in that project is done via YAML:

```yaml
parameters:
  - &Lang
    name: lang
    in: query
    description: 'Provide content in the specified language only'
    required: false
    deprecated: false
    allowEmptyValue: true
    schema:
      type: string
      enum:
        - de
        - dk
        - nl
        - en
        - fi
        - fr
        - it
        - no
        - pl
        - es
        - sv
    style: form
    explode: false
    allowReserved: false
    example: 'de'
  - &Scope
    name: 'scope[]'
    in: query
    description: ''
    required: false
    deprecated: false
    allowEmptyValue: true
    schema:
      type: array
      items:
        type: string
        enum:
          - 'ids'
          - 'stockData'
          - 'logisticData'
          - 'catalogData'
    style: form
    explode: true
    allowReserved: false
    example: [ 'ids', 'stockData', 'logisticData', 'catalogData' ]
resources:
  v1\Model\DefaultDocumentManager\ProductVariation:
    properties:
      id:
        identifier: false
      products_variations_id:
        identifier: true
    attributes:
      route_prefix: /v1
      input: v1\Model\DefaultDocumentManager\ProductVariation
      output: v1\Context\Discovery\Application\ProductVariation\Dto\ProductVariation
      order:
        products_variations_id: ASC
      pagination_via_cursor:
        -
          field: productVariationId
          direction: ASC
      groups:
        scopes:
          scope:ids:
            - id
            - products_variations_id
            - products_id
          scope:stockData:
            - id
            - in_stock
            - weighted_average_price
            - transit_price
            - stockLocations
          scope:logisticData:
            - id
            - products_id
            - package_length
            - package_weight
            - package_height
            - package_weight
            - package_weight_verified
            - main_data.expiration_flag
            - main_data.foil_packing
            - main_data.paperbag_packing
            - main_data.flexible
            - main_data.postprocessing
            - main_data.unNumbers
          scope:catalogData:
            - id
            - images
            - products_id
            - main_data.products_models_id
            - main_data.models_title
    shortName: 'ProductVariation'
    collectionOperations:
      get:
        filters:
          - 'api.product_variation.range_filter'
          - 'api.product_variation.cursor_based_pagination_filter'
          - 'api.product_variation.product_variations_id_filter'
          - 'api.product_variation.product_variations_ean_filter'
          - 'api.product_variation.products_id_filter'
          - 'api.product_variation.search_filter'
          - 'api.product_variation.date_filter'
        method: 'GET'
        path: '/productVariations'
        openapi_context:
          parameters:
            - *Lang
            - *Scope
    itemOperations:
      get:
        method: 'GET'
        path: '/productVariations/{products_variations_id}'
        requirements:
          products_variations_id: '\d+'
        defaults:
          identifier: 'products_variations_id'
        openapi_context:
          parameters:
            - *Lang
            - *Scope

  v1\Model\DefaultDocumentManager\ProductMainData:
    properties:
      id:
        identifier: false
      products_id:
        identifier: true
    attributes:
      pagination_enabled: false
      pagination_client_items_per_page: false
      route_prefix: /v1
      input: v1\Model\DefaultDocumentManager\ProductMainData
      output: v1\Context\Discovery\Application\ProductImage\Dto\ProductImage
    shortName: 'ProductImage'
    collectionOperations:
      get:
        method: 'GET'
        path: '/productImages'
        filters:
          - 'api.product_image.product_id_filter'
    itemOperations: []
```

When requesting JSON-LD from `/productVariations/{products_variations_id}`, the following eror can be seen:

```json
{
  "code": 0,
  "message": "No resource class found for object of type \"v1\\Context\\Discovery\\Application\\ProductVariation\\Dto\\ProductVariation\".",
  "file": "/app/vendor/api-platform/core/src/Api/ResourceClassResolver.php:56",
  "trace": [
    {
      "file": "/app/vendor/api-platform/core/src/Util/ResourceClassInfoTrait.php",
      "line": 60,
      "function": "getResourceClass",
      "class": "ApiPlatform\\Api\\ResourceClassResolver",
      "type": "->",
      "args": [
        {}
      ]
    },
    {
      "file": "/app/vendor/api-platform/core/src/Core/Bridge/Symfony/Routing/IriConverter.php",
      "line": 122,
      "function": "getResourceClass",
      "class": "ApiPlatform\\Core\\Bridge\\Symfony\\Routing\\IriConverter",
      "type": "->",
      "args": [
        {},
        true
      ]
    },
    {
      "file": "/app/vendor/api-platform/core/src/JsonLd/Serializer/ItemNormalizer.php",
      "line": 107,
      "function": "getIriFromItem",
      "class": "ApiPlatform\\Core\\Bridge\\Symfony\\Routing\\IriConverter",
      "type": "->",
      "args": [
        {}
      ]
    },
    {
      "file": "/app/vendor/symfony/serializer/Serializer.php",
      "line": 159,
      "function": "normalize",
      "class": "ApiPlatform\\JsonLd\\Serializer\\ItemNormalizer",
      "type": "->",
      "args": [
        {},
        "jsonld",
        {
          "operation_type": "item",
          "item_operation_name": "get",
          "iri_only": false,
          "input": {
            "class": "v1\\Model\\DefaultDocumentManager\\ProductVariation",
            "name": "ProductVariation"
          },
          "resource_class": "v1\\Context\\Discovery\\Application\\ProductVariation\\Dto\\ProductVariation",
          "request_uri": "/api/v1/productVariations/897035",
          "uri": "http://localhost/api/v1/productVariations/897035",
          "resources": {},
          "exclude_from_cache_key": [
            "resources",
            "resources_to_push"
          ],
          "resources_to_push": {},
          "api_sub_level": true,
          "allow_extra_attributes": false,
          "jsonld_has_context": true
        }
      ]
    },
    {
      "file": "/app/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php",
      "line": 203,
      "function": "normalize",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->",
      "args": [
        {},
        "jsonld",
        {
          "operation_type": "item",
          "item_operation_name": "get",
          "iri_only": false,
          "input": {
            "class": "v1\\Model\\DefaultDocumentManager\\ProductVariation",
            "name": "ProductVariation"
          },
          "resource_class": "v1\\Context\\Discovery\\Application\\ProductVariation\\Dto\\ProductVariation",
          "request_uri": "/api/v1/productVariations/897035",
          "uri": "http://localhost/api/v1/productVariations/897035",
          "resources": {},
          "exclude_from_cache_key": [
            "resources",
            "resources_to_push"
          ],
          "resources_to_push": {},
          "api_sub_level": true,
          "allow_extra_attributes": false
        }
      ]
    },
    {
      "file": "/app/vendor/api-platform/core/src/JsonLd/Serializer/ItemNormalizer.php",
      "line": 81,
      "function": "normalize",
      "class": "ApiPlatform\\Serializer\\AbstractItemNormalizer",
      "type": "->",
      "args": [
        {},
        "jsonld",
        {
          "operation_type": "item",
          "item_operation_name": "get",
          "iri_only": false,
          "input": {
            "class": "v1\\Model\\DefaultDocumentManager\\ProductVariation",
            "name": "ProductVariation"
          },
          "resource_class": "v1\\Context\\Discovery\\Application\\ProductVariation\\Dto\\ProductVariation",
          "request_uri": "/api/v1/productVariations/897035",
          "uri": "http://localhost/api/v1/productVariations/897035",
          "resources": {},
          "exclude_from_cache_key": [
            "resources",
            "resources_to_push"
          ],
          "resources_to_push": {},
          "api_sub_level": true,
          "allow_extra_attributes": false
        }
      ]
    },
    {
      "file": "/app/vendor/symfony/serializer/Serializer.php",
      "line": 159,
      "function": "normalize",
      "class": "ApiPlatform\\JsonLd\\Serializer\\ItemNormalizer",
      "type": "->",
      "args": [
        {},
        "jsonld",
        {
          "operation_type": "item",
          "item_operation_name": "get",
          "iri_only": false,
          "input": {
            "class": "v1\\Model\\DefaultDocumentManager\\ProductVariation",
            "name": "ProductVariation"
          },
          "output": {
            "class": "v1\\Context\\Discovery\\Application\\ProductVariation\\Dto\\ProductVariation",
            "name": "ProductVariation"
          },
          "resource_class": "v1\\Model\\DefaultDocumentManager\\ProductVariation",
          "request_uri": "/api/v1/productVariations/897035",
          "uri": "http://localhost/api/v1/productVariations/897035",
          "resources": {},
          "exclude_from_cache_key": [
            "resources",
            "resources_to_push"
          ],
          "resources_to_push": {}
        }
      ]
    },
    {
      "file": "/app/vendor/symfony/serializer/Serializer.php",
      "line": 138,
      "function": "normalize",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->",
      "args": [
        {},
        "jsonld",
        {
          "operation_type": "item",
          "item_operation_name": "get",
          "iri_only": false,
          "input": {
            "class": "v1\\Model\\DefaultDocumentManager\\ProductVariation",
            "name": "ProductVariation"
          },
          "output": {
            "class": "v1\\Context\\Discovery\\Application\\ProductVariation\\Dto\\ProductVariation",
            "name": "ProductVariation"
          },
          "resource_class": "v1\\Model\\DefaultDocumentManager\\ProductVariation",
          "request_uri": "/api/v1/productVariations/897035",
          "uri": "http://localhost/api/v1/productVariations/897035",
          "resources": {},
          "exclude_from_cache_key": [
            "resources",
            "resources_to_push"
          ],
          "resources_to_push": {}
        }
      ]
    },
    {
      "file": "/app/vendor/api-platform/core/src/Symfony/EventListener/SerializeListener.php",
      "line": 121,
      "function": "serialize",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->",
      "args": [
        {},
        "jsonld",
        {
          "operation_type": "item",
          "item_operation_name": "get",
          "iri_only": false,
          "input": {
            "class": "v1\\Model\\DefaultDocumentManager\\ProductVariation",
            "name": "ProductVariation"
          },
          "output": {
            "class": "v1\\Context\\Discovery\\Application\\ProductVariation\\Dto\\ProductVariation",
            "name": "ProductVariation"
          },
          "resource_class": "v1\\Model\\DefaultDocumentManager\\ProductVariation",
          "request_uri": "/api/v1/productVariations/897035",
          "uri": "http://localhost/api/v1/productVariations/897035",
          "resources": {},
          "exclude_from_cache_key": [
            "resources",
            "resources_to_push"
          ],
          "resources_to_push": {}
        }
      ]
    },
    {
      "file": "/app/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 260,
      "function": "onKernelView",
      "class": "ApiPlatform\\Symfony\\EventListener\\SerializeListener",
      "type": "->",
      "args": [
        {
          "controllerArgumentsEvent": {}
        },
        "kernel.view",
        {}
      ]
    },
    {
      "file": "/app/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 220,
      "function": "Symfony\\Component\\EventDispatcher\\{closure}",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "::",
      "args": [
        {
          "controllerArgumentsEvent": {}
        },
        "kernel.view",
        {}
      ]
    },
    {
      "file": "/app/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 56,
      "function": "callListeners",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "args": [
        [
          {},
          {},
          {},
          {},
          {},
          {},
          {}
        ],
        "kernel.view",
        {
          "controllerArgumentsEvent": {}
        }
      ]
    },
    {
      "file": "/app/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 171,
      "function": "dispatch",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "args": [
        {
          "controllerArgumentsEvent": {}
        },
        "kernel.view"
      ]
    },
    {
      "file": "/app/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 74,
      "function": "handleRaw",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "args": [
        {
          "attributes": {},
          "request": {},
          "query": {},
          "server": {},
          "files": {},
          "cookies": {},
          "headers": {}
        },
        1
      ]
    },
    {
      "file": "/app/vendor/symfony/http-kernel/Kernel.php",
      "line": 197,
      "function": "handle",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "args": [
        {
          "attributes": {},
          "request": {},
          "query": {},
          "server": {},
          "files": {},
          "cookies": {},
          "headers": {}
        },
        1,
        true
      ]
    },
    {
      "file": "/app/public/index.php",
      "line": 28,
      "function": "handle",
      "class": "Symfony\\Component\\HttpKernel\\Kernel",
      "type": "->",
      "args": [
        {
          "attributes": {},
          "request": {},
          "query": {},
          "server": {},
          "files": {},
          "cookies": {},
          "headers": {}
        }
      ]
    }
  ],
  "prev_exception": null
}
```

**How to reproduce**  

Unfortunately I can't share the repo and as it's a quite big and complex application, producing a minimal reproducer will also be very hard, but I'm gladly taking any pointers to investigate further.
