### ISSUE TITLE
"ApiPlatform\Hydra\Serializer\ErrorNormalizer" is deprecated

### ISSUE THREAD

**Issue by KDederichs** [api-platform/core#5949]
**API Platform version(s) affected**: 3.2.4

**Description**  
In my tests I'm getting an indirect deprecation:
```
  17x: Since api-platform 3.2: The class "ApiPlatform\Hydra\Serializer\ErrorNormalizer" is deprecated in favor of using an Error resource. We fallback on "api_platform.serializer.normalizer.item".
```

which should not happen I think? I'm not using that particular serializer anywhere at least so it seems to be Api-Platform using it somewhere still.

**How to reproduce**  
Unclear, it's something Api-Platform does I think?

**Comment by j-schumann** [comment]
What is the configuration in your `packages/api_platform.yaml`, do you maybe have
```
skip_deprecated_exception_normalizers: false
```
in there? (Which is the backwards-compatible config).
Be aware that setting that to `true` may change your output of error responses, depending on your situation, e.g. when you decorated the 'api_platform.hydra.normalizer.error' before.

**Comment by KDederichs** [comment]
Nope, pretty default config as well for now:
```yaml
api_platform:
    title: API
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    error_formats:
        jsonld: ['application/ld+json']      # Hydra error formats
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    exception_to_status:
        App\Exception\OrganisationNotSetException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_FORBIDDEN
        App\Exception\ProjectNotSetException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_FORBIDDEN
        Mollie\Api\Exceptions\ApiException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
```
