### ISSUE TITLE
Ability to create multiple resources based on the same entity

### ISSUE THREAD

**Issue by karser** [api-platform/core#595]
Hello, I wonder if it's possible to have 2 resources with the different serialization groups based on the same entity.
The config below doesn't work:
```yml
#api_resources.yml
user:
    shortName: User
    class: UserBundle\Entity\User
    attributes:
        normalization_context: { groups: ['user_read'] }
        denormalization_context: { groups: ['user_write'] }

participant:
    shortName: Participant
    class: UserBundle\Entity\User
    attributes:
        normalization_context: { groups: ['participant'] }
        denormalization_context: { groups: ['participant'] }

```
The reason is I'd like to restrict or add some virtual fields for the participant.
Is that the right approach achieving this aim?
Should I use Custom Collection Data Provider instead?
