### ISSUE TITLE
Response header "content-type" changes "randomly" in 3.2.x unit tests

### ISSUE THREAD

**Issue by j-schumann** [api-platform/core#5960]
**API Platform version(s) affected**: 3.2.4

**Description**  
For requests to an existing endpoint (e.g. `/documents`) but with an unsupported method (e.g. `DELETE`) our unit tests show inconsistent behaviour:
When run separately (only the test that checks that the collection cannot be deleted) the test is always successful and returns the `content-type` "application/ld+json". But when running the complete test suite or just multiple tests together (whole test class, only failed tests etc...) those tests **sometimes** fail with:

`Failed asserting that the Response has header "content-type" with value "application/ld+json".`
Instead the content-type is "application/problem+json; charset=utf-8"

As far as I can see this happens mostly when another (unrelated) test fails. I can then fix the unrelated test and run all failed tests again (in PhpStorm) and suddenly also this unchanged test(s) pass. Or after one of those tests mysteriously failed I then debug this test in PhpStorm + XDebug and it passes without any changes to the codebase.

**How to reproduce**  
I have no reproduce code/repo and cannot consistently reproduce it myself. But it happens often/reliably when running the test class for one endpoint/entity.

**Additional Context**  
Tests are run via phpStorm with xDebug.
The problem only seems to occur for errors that are produced when the routing fails and are handled by the Symfony system (through its ProblemNormalizer) and not by ApiPlatform's ApiResource\Error 

```yaml
    defaults:
        extra_properties:
          rfc_7807_compliant_errors: true
          skip_deprecated_exception_normalizers: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
```

There are some more inconsistencies with the error handling in 3.2 that I will descibe in other issues.
