### ISSUE TITLE
Migration to 3.2.5: the response structure has changed

### ISSUE THREAD

**Issue by ecourtial** [api-platform/core#5987]
**API Platform version(s) affected**: 3.2.5

**Description**  
Migrated from 3.2.4 to 3.2.5. Now some responses structure have changed (see screenshots below).
The given example is a simple attribute validation.
Request in basic JSON.

With 3.2.4

![before](https://github.com/api-platform/core/assets/57905107/eb1634c2-2393-4361-b976-8519aa091c71)

With 3.2.5

![after](https://github.com/api-platform/core/assets/57905107/b6d37134-4ba8-4488-83c7-2865dbaa9de8)

**Comment by soyuka** [comment]
damn, what's your configuration? Also environment is `dev`? 

Use this for backward compatibility: 

```
api_platform:
    defaults:
        extra_properties:
            rfc_7807_compliant_errors: false
```
