### ISSUE TITLE
Oauth/Entra ID (Azure AD)-scopes problem

### ISSUE THREAD

**Issue by StefanKaifer74** [api-platform/core#6140]
**API Platform version(s) affected**: 3.2.12

**Description**  
Unfortunately I can't use scopes with Enra Id/Azure Id, because these scopes have "hyphens" in it (it's not possible to change the scopes), but Api platform replaces it with "underscores".

**How to reproduce**  
Register application and create scopes in Entra Id as described here:
https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/blob/main/3-Authorization-II/1-call-api/README.md

Change api_platform.yml to:

```
oauth:
        # To enable or disable OAuth.
        enabled: true

        # The OAuth client ID.
        # https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/3-Authorization-II/1-call-api
        clientId: '59gb1f65-1111-0000-pppp-xxxxxxxxxxxx'

        # The OAuth client secret.
        #clientSecret: ''

        # The OAuth type.
        type: 'oauth2'

        # The OAuth flow grant type: implicit / password / application / clientCredentials / accessCode / authorizationCode
        # https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow
        # https://learn.microsoft.com/en-us/entra/identity-platform/sample-v2-code?tabs=apptype#web-api
        flow: 'authorizationCode'

        # The OAuth token URL. Make sure to check the specification tokenUrl is not needed for an implicit flow.
        tokenUrl: 'https://login.microsoftonline.com/<your tenant-id>/oauth2/v2.0/token'

        # The OAuth authentication URL.
        authorizationUrl: 'https://login.microsoftonline.com/<your tenant-id>/oauth2/v2.0/authorize'

        # The OAuth scopes.
        scopes:
            api://59gb1f65-1111-0000-pppp-xxxxxxxxxxxx/ABC.Read: "Allows ABC-users to read."
            api://59gb1f65-1111-0000-pppp-xxxxxxxxxxxx/ABC.ReadWrite: "Allows  ABC-users to read & write."
```

**Possible Solution**  
Don't change the scope names.

**Additional Context** 
![Swagerui-Mask](https://github.com/api-platform/core/assets/80703725/cb74a997-d118-4904-8b62-2e9d338168d1)
![Microsoft-error](https://github.com/api-platform/core/assets/80703725/f0fe1b16-43c9-4e73-924e-bd85a0f702c2)
