### ISSUE TITLE
API platform seems to be not using/throwing away framework.serializer.default_context configuration

### ISSUE THREAD

**Issue by ostrolucky** [api-platform/core#6280]
**API Platform version(s) affected**: 3.2.18

**Description**  
If you have `seld/jsonlint` installed, since https://symfony.com/blog/new-in-symfony-6-4-serializer-improvements#detailed-json-decoding-errors in dev mode symfony serializer is supposed show something more useful than "Syntax error"

This can also be enabled in production by using this config:
```yaml
framework:
 serializer:
  default_context:
   php/const Symfony\Component\Serializer\Encoder\JsonDecode::DETAILED_ERROR_MESSAGES: true
```

Neither works with APIP, however.

**How to reproduce**  
Install seld/jsonlint and send payload to APIP endpoint that's not a valid JSON
