### ISSUE TITLE
V3.2.20 Did Not Fix The BackedEnum Serialization Priority Error

### ISSUE THREAD

**Issue by gnito-org** [api-platform/core#6285]
**API Platform version(s) affected**: 3.2.20

**Description**  
Refer to https://github.com/symfony/symfony/issues/54478.

I do not use GraphQL, and the issue still exists in 3.2.20.

The only work-around I can find is to hack the priority in `services.yaml`.

**How to reproduce**  

Here is a repository with a [problem replicator](https://github.com/gnito-org/api-backed-enum-replicator).

**Possible Solution**  

**Additional Context**

**Comment by gnito-org** [comment]
```yaml
# config/services.yaml

    serializer.normalizer.backed_enum:
        class: Symfony\Component\Serializer\Normalizer\BackedEnumNormalizer
        tags:
            - { name: 'serializer.normalizer', priority: -891 }
```

Any priority from -891 and lower fixes the problem.
