### ISSUE TITLE
[3.3] Object to update failed to load into security context

### ISSUE THREAD

**Issue by latenzio** [api-platform/core#6341]
**API Platform version(s) affected**: 3.3.0

**Description**  
After update from 3.2.22 to 3.3.0 my `PATCH` and `PUT` endpoints do not behave expected. The `object` is not loaded anymore, so my security context definitions fail.

**How to reproduce**  
```php

use ApiPlatform\Metadata as APM;

#[APM\ApiResource(
    operations: [
        new APM\Patch(
            uriTemplate: '/users/{username}',
            uriVariables: [
                'clientId' => new APM\Link(toProperty: 'client', fromClass: Client::class),
                'username' => new APM\Link(fromClass: User::class),
            ],
            requirements: ['username' => '.+'],
            status: Response::HTTP_ACCEPTED,
            security: "is_granted('".Roles::FRONTEND_DEFAULT."')".
            " and is_granted('".Roles::FRONTEND_CLIENT_READ."', object.getClient())".
            " and is_granted('".Roles::FRONTEND_USER_UPDATE."', object)",
            input: Update::class,
            output: false,
            processor: UpdateProcessor::class,
        ),
    ],
    routePrefix: '/{clientId}',
)]
```
**Possible Solution**  
I have no idea.

**Additional Context**  
Occurs in `dev` mode on docker container and also in `prod` on live server

**Comment by soyuka** [comment]
interesting what is the `use_symfony_listener` value on your configuration? can we also get the backward compatibility flags you use (usually inside `defaults.extra_properties`

**Comment by latenzio** [comment]
@soyuka thx for your quick reply.
this is my configuration in `packages/api_platform.yaml`:
```yml
api_platform:
    title: 'Hello API Platform'
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_client_items_per_page: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
```

I was not aware of this new `use_symfony_listeners` option. Just tested setting this to `true` brings no success.
