### ISSUE TITLE
[3.3] BC in 3.3 release. Payload is not serialized to controller

### ISSUE THREAD

**Issue by pimjansen** [api-platform/core#6343]
**API Platform version(s) affected**: 3.2.22 vs 3.3.0

**Description**  
Since upgrading from 3.2.22 to 3.3.0 my request payload is not ending up in my controller anymore. This feels for me like a breaking change in this release.

**How to reproduce**  
My Api Resource:
```
#[ApiResource]
#[Post(
    uriTemplate: '/generate',
    routePrefix: '/v1',
    status: 200,
    controller: Generate::class,
    output: false,
)]
```

My controller:
```
#[AsController]
class Generate extends AbstractController
{
    public function __invoke(
        Pdf $data,
        PdfGenerator $generatorService,
        ValidatorInterface $validator,
    ): JsonResponse {
        dd($data); // Empty object
        $errors = $validator->validate($data);
        if (count($errors) > 0) {
            throw new ValidationException($errors);
        }

        return new JsonResponse(
            $generatorService($data),
            Response::HTTP_OK,
        );
    }
}
```

**Possible Solution**  
n/a

**Additional Context**  
n/a

**Comment by pimjansen** [comment]
As far as i can see this is the issue:

```
If you use controllers you should use:

api_platform:
    use_symfony_listeners: true
```

Setting a configuration parameter with another default behaviour in a minor release? This is weird

**Comment by soyuka** [comment]
I see I think that the parameter's value should've been true by default, I'll fix this asap.

**Comment by justpilot** [comment]
I have similar issue but I can't resolve it with `use_symfony_listeners: true`.

```
new Post(
            uriTemplate: '/verify/{discountCode}',
            uriVariables: [Voucher::class, 'discountCode'],
            controller: VoucherVerifyController::class,
            normalizationContext: ['groups' => ['voucher:item:verify']],
            denormalizationContext: ['groups' => []],
            security: 'is_granted("PUBLIC_ACCESS")',
            read: false,
            write: false,
        ),
```

```
public function __invoke(string $discountCode): Voucher
    {
        $voucher = $this->voucherRepository->findOneBy([
            'discountCode' => $discountCode
        ]);

        if(!$voucher) {
            throw $this->createNotFoundException("Unable to find the Voucher Resource.");
        }

        if(!$voucher->isActive()) {
            $voucher->setValid(false);
        }

        return $voucher;
    }
```

The code doesn't read the Controller at all. Results in an error:

```
"detail": "Invalid identifier value or configuration.",
    "status": 404,
    "type": "/errors/404",
```

Version 3.2.22 worked fine!

**Comment by pimjansen** [comment]
> I see I think that the parameter's value should've been true by default, I'll fix this asap.

Would be good or to revert the change that did this or patch it with the setting enabled. Ofc i have no idea what the original idea behind it was though. Are we missing some tests here as well since this happened?

**Comment by soyuka** [comment]
I should've made it clearer in the changelog, anyways with the `event_listeners_backward_compatibility_layer` to `true` you should end up with `use_symfony_listeners` to `true` which is mandatory for controllers to work. 

The requirement for this 3.3 version should be to set up `use_symfony_listeners` if you need it as the default value will be `false` in 4.0.

**Comment by soyuka** [comment]
@pimjansen you did use `event_listeners_backward_compatibility_layer: true` in 3.2?

**Comment by pimjansen** [comment]
> @pimjansen you did use `event_listeners_backward_compatibility_layer: true` in 3.2?

No and this was my full config:

```yaml
api_platform:
  title: PDF API
  description: API to generate PDF files
  version: 1.0.0
    license:
      name: GPL
  swagger:
    versions: [ 3 ]
    api_keys:
      JWT:
        name: Authorization
        type: header
  formats:
    jsonld: [ 'application/ld+json' ]
    json: [ 'application/json' ]
    yaml: [ 'application/x-yaml' ]
    xml: [ 'application/xml' ]
    csv: [ 'text/csv' ]
    html: [ 'text/html' ]
  enable_entrypoint: true
  enable_profiler: false
  doctrine:
    enabled: false
  validator:
    serialize_payload_fields: ~
  defaults:
    stateless: true
  mapping:
    paths:
      - '%kernel.project_dir%/src/V1/Model'
```
