### ISSUE TITLE
JSON Web Tokens

### ISSUE THREAD

**Issue by foolskill** [api-platform/core#659]
Hi,

I would like to improve my application so I like to know if it is possible to bind it with jwt security ?

I found LexikJWTAuthenticationBundle but there is not work for now, so I'm looking for solution.

Thank's

PS: sorry for my english

**Comment by dunglas** [comment]
Hello, I usually install LexikJwtAunthentifocationBundle with API Platform and it works like a charm.

You can also use it with Guard and API Platform, take a look at this presentation: http://fr.slideshare.net/mobile/weaverryan/symfony-guard-authentication-fun-with-api-token-social-login-jwt-and-more

What doesn't work for you with this bundle?

Alternativately you can use directly the Symfony Security component and a library supporting JWT like namashi/jose or firebase/jwt-php but this is more work.

**Comment by soyuka** [comment]
lexikjwt works fine, I use it with fosuserbundle without issues. Could you tell us what doesn't work? Maybe an abstract of your bundle configuration would help. Thanks!

**Comment by foolskill** [comment]
Hi,
Thank a lot for your responses

@dunglas thanks , i am looking your  link know.
@soyuka thank you also

I have install the LexikJWT  yesterday and i have some problem width my api.

when I run a query on "login_check" I get a 404 error.
I configured my security file as they ask me in the documentation (https://github.com/slashfan/LexikJWTAuthenticationBundleSandbox/blob/master/app/config/security.ym)  but when I run a "debug: router --show-controllers" I get the road well "login_check" but it does not match with any controller.

Someone could help me please? 

PS: sorry for my english
![jwt](https://cloud.githubusercontent.com/assets/6184877/17322049/e5d72b7c-589b-11e6-8a82-5170c20ab5d9.PNG)

**Comment by soyuka** [comment]
Some configuration extracts:

file `config.yml`:

```yaml
imports:
  - { resource: ./security.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    http_method_override: true
    serializer: { enable_annotations: true }

lexik_jwt_authentication:
    private_key_path: '%kernel.root_dir%/../var/jwt/private.pem'   # ssh private key path
    public_key_path:  '%kernel.root_dir%/../var/jwt/public.pem'    # ssh public key path
    pass_phrase:      '1234'                                      # ssh key pass phrase
    token_ttl:        null                                   # token ttl - defaults to 86400 1 day

api_platform:
    enable_fos_user:                   true

fos_user:
    db_driver: orm
    firewall_name: login
    user_class: Party\UserBundle\Entity\User
    group:
        group_class: Party\PartyBundle\Entity\Department
    registration:
        confirmation:
            enabled: false
```

In `app/config/routing.yml`:

```yaml
user_routing:
    resource: "@PartyUserBundle/Resources/config/routing.yml"
api:
    resource: '.'
    type: 'api_platform'
    prefix: /api
```

This loads the following user routing:

```yaml
fos_user_security_check:
    path: /login_check
    requirements:
        methods: POST
fos_user_security_login:
    path: /login
    defaults: { _controller: FOSUserBundle:Security:login }
```

And the `login` firewall is in `security.yml`:

```yaml
security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            context: api
            form_login:
                provider: fos_userbundle
                check_path:               fos_user_security_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        doc: 
            pattern: ^/api/doc
            anonymous: true
        api:
            pattern: ^/api
            anonymous: false
            stateless: true
            context: api
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer

        default:
            anonymous: ~

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       role: IS_AUTHENTICATED_FULLY }
```
