### ISSUE TITLE
All filters are enabled by default

### ISSUE THREAD

**Issue by gui-don** [api-platform/core#665]
On the doc I read:

> By default, all filters are disabled. They must be enabled explicitly.

Since I updated to api-platform v2, it seems all my entities attributes are automatically filterable. When I get a collection, it returns a `hydra:search` node filled with every single attribute.

------

Furthermore, I wanted to add a custom filter with the partial strategy:
```
// service.yml
my_project.attribute_filter:
  parent: "api_platform.doctrine.orm.search_filter"
  arguments: [ { attribute: "partial" } ]
  tags: [ { name: "api_platform.filter", id: "attribute.filter" } ]
```

Now, the filter is added within the Doctrine request along with the default filter, resulting in this nonsense (call: `/api/entity?attribute=test`):

`SELECT i FROM Entity i WHERE i.attribute LIKE '%test%' AND i.attribute = 'test'`

What did I do wrong?

**Comment by teohhanhui** [comment]
> Since I updated to api-platform v2, it seems all my entities attributes are automatically filterable. When I get a collection, it returns a hydra:search node filled with every single attribute.

Please check your filter configuration (and share them with us if you can't figure out what you did wrong). I believe it's not broken since it should be covered in our test suite (we shall see...).

> Now, the filter is added within the Doctrine request along with the default filter

There are no default filters so I don't get what you mean?

**Comment by gui-don** [comment]
Thanks for your help!

You’re right, the unwanted behavior occurs only when I add another custom filter with the one I showed. I have custom filters on each entity, so that’s why it misleaded me.

Here is a simplified version of what I have.

service.yml:
  ```
  [...]

  my_project.exclude_self_filter:
        class: "MyProject\\Doctrine\\Orm\\Filter\\CustomFilter"
        arguments:
            - "@some"
            - "@args"
        tags: [ { name: "api_platform.filter", id: "custom.filter" } ]
    my_project.attribute_filter:
        parent: "api_platform.doctrine.orm.search_filter"
        arguments: [ { attribute: "partial" } ]
        tags: [ { name: "api_platform.filter", id: "attribute.filter" } ]

  [...] (No more filter after)
```

entity.yml:
```
/**
 * @ApiResource(attributes={
 *     "normalization_context"={"groups"={"entity_read"}},
 *     "denormalization_context"={"groups"={"entity_write"}},
 *     "filters"={"attribute.filter", "custom.filter"}
 * })
 * @ORM stuffs here
 */
class Entity implements EntityInterface
{
  // entity content here
}
```

CustomFilter.php:
```
class CustomFilter extends SearchFilter
{
    // Properties…

    public function __construct(
        TokenStorageInterface $tokenStorage,
        ManagerRegistry $managerRegistry,
        RequestStack $requestStack,
        IriConverterInterface $iriConverter,
        PropertyAccessorInterface $propertyAccessor,
        array $properties = null
    ) {
         // Sets private properties…

        parent::__construct($managerRegistry, $requestStack, $iriConverter, $propertyAccessor, $properties);
    }

    public function apply(QueryBuilder $queryBuilder, string $resourceClass, string $operationName = null)
    {
        $queryBuilder
            ->andWhere('i.custom <> :custom')
            ->setParameter(':custom', $this->getCustomValue())
        ;
        parent::apply($queryBuilder, $resourceClass, $operationName);
    }
}
```

Resulting Doctrine request (dumped from `ReadListener->getCollectionData()`): 

> SELECT i FROM  Entity i WHERE i.custom <> :custom AND i.attribute = :attribute_1 AND i.attribute LIKE :attribute_2
(`:attribute_1` and `:attribute_2` are the same, excepted the second is wrapped in `%`).
