### ISSUE TITLE
Deprecation in QueryParameterValidateListener

### ISSUE THREAD

**Issue by dannyvw** [api-platform/core#6686]
**API Platform version(s) affected**: 3.4

**Description**  
User Deprecated: Since api-platform/core 3.3: Use a "ApiPlatform\State\ProviderInterface" as first argument in "ApiPlatform\Symfony\EventListener\QueryParameterValidateListener" instead of "ApiPlatform\ParameterValidator\ParameterValidator".

**How to reproduce**  

**Possible Solution**  

**Additional Context**  

How can we solve this deprecation?

**Comment by james2001** [comment]
I wish to know too 😁

**Comment by mv-developer** [comment]
+1

**Comment by derskythe** [comment]
@dannyvw @james2001 @dannyvw 

This helped me: [Upgrade Guide](https://api-platform.com/docs/v3.1/core/upgrade-guide/)

Special guest:
```shell
php bin/console api:upgrade-resource
```

_From the topic [The Upgrade Command](https://api-platform.com/docs/v3.1/core/upgrade-guide/#the-upgrade-command)_

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/6655

**Comment by sengaigibon** [comment]
I managed to "solve it" by decorating the event listener QueryParameterValidateListener ...
This is the snippet in my services.yaml file:

````
services:
    ApiPlatform\Symfony\EventListener\QueryParameterValidateListener:
        decorates: 'api_platform.listener.view.validate_query_parameters'
        arguments:
            $queryParameterValidator: '@App\State\SimpleStateProvider'
````

`App\State\SimpleStateProvider` is a dummy class with this content:
````
class SimpleStateProvider implements ProviderInterface
{

    public function provide(Operation $operation, array $uriVariables = [], array $context = []): object|array|null
    {
        return [];
    }
}
````

I mean, it's more like a workaround than a solution.
