### ISSUE TITLE
[Question] include null values for date filter

### ISSUE THREAD

**Issue by aledeg** [api-platform/core#669]
I would like to always include null values while searching for dates.
It seems impossible for now. Correct me if I am wrong.

I tried to set the same field with different values but as expected, only one is used.

``` yaml
filter.subscription_date_filter:
    parent: "api_platform.doctrine.orm.date_filter"
    arguments:
        - validFrom: 'include_null_before'
          validFrom: 'include_null_after'
    tags: [ { name: 'api_platform.filter', id: 'filter.subscription_date' } ]
```

Did I miss something?

**Comment by dunglas** [comment]
According to https://github.com/api-platform/docs/blob/master/core/filters.md#managing-null-values, it should work. You only need one line (before or after dpeending of the order you want).

Can you provide your entity mapping?

**Comment by aledeg** [comment]
If I choose 'include_null_after', I have the NULL values when I filter the date with the ```after``` parameter. But I won't have a match with the ```before``` parameter.

If I choose 'include_null_before, I have the NULL values when I filter the date with the ```before``` parameter. But I won't have a match with the ```after``` parameter.

I check the code and it works as expected. But it's not what I am trying to achieve.
I would like to have NULL values displayed all the time whether I am filtering with ```before``` or ```after```

Regarding the entity mapping, I think it's irrelevant since it's not related. I include it anyway.
```php
namespace ApiBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiProperty;

/**
 * @ORM\Entity
 * @ORM\Table(name="contact")
 * @ApiResource(attributes={
 *     "filters"={
 *         "filter.contact_date"
 *     }
 * })
 */
class Contact
{

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthDate;

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getId()
    {
        return $this->id;
    }
    public function setBirthDate(\DateTime $birthDate = null)
    {
        $this->birthDate = $birthDate;
    }

    public function getBirthDate()
    {
        return $this->birthDate;
    }

}
```
The filter configuration:
```yaml
filter.contact_date_filter:
    parent: 'api_platform.doctrine.orm.date_filter'
    arguments:
        - birthDate: include_null_after
    tags:
        - { name: 'api_platform.filter', id: 'filter.contact_date' }
```

What I would like to do instead is something like:
```yaml
filter.contact_date_filter:
    parent: 'api_platform.doctrine.orm.date_filter'
    arguments:
        - birthDate: include_null_always
    tags:
        - { name: 'api_platform.filter', id: 'filter.contact_date' }
```
or like:
```yaml
filter.contact_date_filter:
    parent: 'api_platform.doctrine.orm.date_filter'
    arguments:
        - birthDate: [include_null_after, include_null_before]
    tags:
        - { name: 'api_platform.filter', id: 'filter.contact_date' }
```
