### ISSUE TITLE
Deserialization for the format form is not supported

### ISSUE THREAD

**Issue by karser** [api-platform/core#674]
Does ApiPlatform support posted Form data?
I'm submitting the form data, [DeserializeListener](https://github.com/api-platform/core/blob/master/src/EventListener/DeserializeListener.php#L64-L69) tries to deserialize the request content and throws with the error "Deserialization for the format form is not supported"

```
api_platform:
    formats:
        json: { mime_types: [ "application/json" ] }
        jsonld: { mime_types: [ "application/ld+json" ] }
        form: { mime_types: [ "application/x-www-form-urlencoded" ] }
#        form: { mime_types: [ "text/plain" ] }

```

![image](https://cloud.githubusercontent.com/assets/1675033/17492558/fd5d4ec0-5db4-11e6-8e2c-e8e70b93c352.png)
