### ISSUE TITLE
[HTTP Cache] Doesn't work with stateOptions 

### ISSUE THREAD

**Issue by simondaigre** [api-platform/core#6754]
**API Platform version(s) affected**: 3.x, 4.x

**Description**  
HTTP Cache doesn't work with DTO using stateOptions, the current implementation in `PurgeHttpCacheListener` only searches for Doctrine entities.

**Comment by mrossard** [comment]
I tried looking at this a few weeks ago, but that's actually trickier than it looks : it's implemented with a Doctrine EventListener, which is a pretty "safe" way to get the correct impacted objects; if those are the ApiResources it's rather straightforward.

With StateOptions you can't easily do the same thing : from the doctrine you'd have to cycle through all ApiResources types to check which ones are actually targeting the entity class you're updating. I ended up triggering the cache invalidation from my State Processors, which doesn't seem ideal...but I'm not sure there's a easier way to do this.

**Comment by mrossard** [comment]
I see 2 missing pieces to this puzzle:
* a way to implement some kind of getApiResourceClassesForEntityClass() method
* a way to transform an entity into the corresponding resources

The first one could be done at the same time the metadata for ApiResources is gathered (AttributesResourceMetadataCollectionFactory or something?).
The second one is more of a problem since there's no "standard" way to do this right now. @soyuka is your symfony PR for a Mapper close to getting merged? It could be a solution to rely on this, couldn't it?

**Comment by g-ra** [comment]
You have the option to override PurgeHttpCacheListener, and I believe it would be beneficial to create a custom gatherResourceAndItemTags method to manage cache invalidation for DTOs that rely on state processors.

Additionally, I would recommend adding an attribute to each DTO that links it to its corresponding entity class. In the gatherResourceAndItemTags method, you could then check for this attribute, and if it's present, include it in the cache invalidation process.

It would, of course, be ideal to have such functionality available out-of-the-box for handling custom resources and DTOs more seamlessly.


here is your service.yaml:

```yaml
    App\HttpCache\PurgeHttpCacheListener:
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }    
    api_platform.doctrine.listener.http_cache.purge:
        class: App\HttpCache\PurgeHttpCacheListener
```

here is you custom Listener:

```php
final class PurgeHttpCacheListener
{
    use ClassInfoTrait;
    private readonly PropertyAccessorInterface $propertyAccessor;

    private array $tags = [];

    public function __construct(
        private readonly UrlGeneratorInterface $urlGenerator,
        #[Autowire(service: 'api_platform.http_cache.purger.souin')]
        private readonly PurgerInterface $purger, private readonly IriConverterInterface | LegacyIriConverterInterface $iriConverter, private readonly ResourceClassResolverInterface | LegacyResourceClassResolverInterface $resourceClassResolver, ?PropertyAccessorInterface $propertyAccessor = null)
    {
        $this->propertyAccessor = $propertyAccessor ?? PropertyAccess::createPropertyAccessor();
    }
```
