### ISSUE TITLE
Serialization for the format "html" is not supported

### ISSUE THREAD

**Issue by darkomenx** [api-platform/core#6774]
**API Platform version(s) affected**: 4.0

Symfony : 7.1
PHP 8.2
Symfony Serializer : 7.1

**Description**  
HTTP 400 Error with message : "Serialization for the format "html" is not supported"

**How to reproduce**  

1. symfony new test-project
2. composer require api-platform/core
3. composer require nsbot/carbon
4. composer require symfony/orm-pack
5. composer require symfony/serializer-pack
6. add this format config 

```
formats:

        jsonld: [ 'application/ld+json' ]

        json: [ 'application/json' ]

        html: [ 'text/html' ]

        jsonhal: [ 'application/hal+json' ]
```
7. symfony serve
8. access URL : https://127.0.0.1:8000/api

**Additional Context**
