### ISSUE TITLE
Hydra documentation returning with double @context (docs.jsonld)

### ISSUE THREAD

**Issue by durimjusaj** [api-platform/core#7222]
**API Platform version(s) affected**: 4.1.16

**Description**  
Just updated to v4.1.16, and docs.jsonld is now returning a result with two @context entries.

![Image](https://github.com/user-attachments/assets/e969c4c6-1053-459c-a66b-8480dc47bcea)

**Possible Solution**  
ApiPlatform\JsonLd\HydraContext - has already @context key in array

![Image](https://github.com/user-attachments/assets/10ba7942-dbfe-4c7b-91f1-c1a76b51b82c)

ApiPlatform\Hydra\Serializer\DocumentationNormalizer
- computeDoc: line 556 - Adds a new @context entry to the documentation.
- getContext: line 580 - Returns HYDRA_CONTEXT merged with another array that already contains @context

![Image](https://github.com/user-attachments/assets/54a5e5c6-28ab-4529-8d8a-37ee340410b6)

An array merge would do the trick.
```
return array_merge(HYDRA_CONTEXT['@context'] ?? [],
[
    '@vocab' => $this->urlGenerator->generate('api_doc', ['_format' => self::FORMAT], UrlGeneratorInterface::ABS_URL) . '#',
    'hydra' => ContextBuilderInterface::HYDRA_NS,
    'rdf' => ContextBuilderInterface::RDF_NS,
    'rdfs' => ContextBuilderInterface::RDFS_NS,
    'xmls' => ContextBuilderInterface::XML_NS,
    'owl' => ContextBuilderInterface::OWL_NS,
    'schema' => ContextBuilderInterface::SCHEMA_ORG_NS,
    'domain' => ['@id' => 'rdfs:domain', '@type' => '@id'],
    'range' => ['@id' => 'rdfs:range', '@type' => '@id'],
    'subClassOf' => ['@id' => 'rdfs:subClassOf', '@type' => '@id'],
]);
```

**Comment by soyuka** [comment]
from what version did you update? This looks weird as we have a bunch of tests for this. Could you give me your `api_platform.yaml` configuration.

**Comment by durimjusaj** [comment]
We recently updated from API Platform 3.3.7 to 4.1.16.

Here’s my current api_platform.yaml configuration:
```
api_platform:
  title: 'Title'
  version: 2.5.3
  show_webby: false
  formats:
    jsonld: [ 'application/ld+json' ]
    json: [ 'application/json' ]
    html: [ 'text/html' ]
    graphql: [ 'application/graphql' ]
    multipart: [ 'multipart/form-data' ]
  patch_formats:
    json: [ 'application/merge-patch+json' ]
    multipart: [ 'multipart/form-data' ]
  path_segment_name_generator: api_platform.metadata.path_segment_name_generator.dash
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'

  enable_swagger_ui: true
  enable_re_doc: true
  swagger:
    versions: [ 3 ]
    api_keys:
      apiKey:
        name: Authorization
        type: header
  http_cache:
    invalidation:
      enabled: false
    public: true
  defaults:
    pagination_items_per_page: 30
    pagination_maximum_items_per_page: 500
    pagination_client_items_per_page: true

    cache_headers:
      max_age: 60
      shared_max_age: 3600
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    filters: [ 'trait_base.order_filter', 'trait_base.date_filter', 'trait_base.search_filter', 'trait_base.exclusive_list' ]
  graphql:
    enabled: true
    default_ide: 'graphql-playground'
    graphiql:
      enabled: true
    graphql_playground:
      enabled: true
    collection:
      pagination:
        enabled: true
    max_query_depth: 20
    max_query_complexity: 1500
    introspection: false

  eager_loading:
    fetch_partial: true
    force_eager: false

  collection:
    order_nulls_comparison: 'nulls_smallest'
    pagination:
      enabled_parameter_name: pagination

  serializer:
    hydra_prefix: true

```

I came across an older issue suggesting that setting `hydra_prefix: true` could resolve this, but that didn’t work in my case. After some research, I couldn’t find a viable solution—aside from overriding the Hydra Documentation Normalizer manually.

Also, @type in some keys is changed and not working in react hydraDocumentationParser, 
eg. in v4.1.16 returns type is @vocab
![Image](https://github.com/user-attachments/assets/16caa031-a74e-4087-8db1-430e779b960b)

in v3.3.7 returns type is @id
![Image](https://github.com/user-attachments/assets/e89855ad-bae0-435c-bb6a-5dc195ae5987)

Should I also update the frontend api-platform to use v4.1.16 ?
