### ISSUE TITLE
[Symfony]Api Platform Cannot Handle Composite Identifiers with PHP Backed Enum

### ISSUE THREAD

**Issue by Oviglo** [api-platform/core#7229]
**API Platform version(s) affected**: 4.0.0

**Description**  
Api Platform cannot correctly handle composite identifiers when one of them is a PHP backed enum.
When trying to access a resource with URL parameters that should map to a composite identifier including an enum,
the error "Invalid identifier value or configuration" is thrown without ever reaching the custom provider.

**How to reproduce**  
1. Create an entity with composite identifiers, one being a ManyToOne relation and the other a PHP backed enum:

```php
#[ORM\Entity]
class AccountConfig
{
    #[ORM\Id]
    #[ORM\ManyToOne(targetEntity: User::class)]
    private User $user;

    #[ORM\Id]
    #[ORM\Column(enumType: AccountConfigEnum::class)]
    private AccountConfigEnum $key;
    
    // Getters and setters
    public function getUser(): ?User { return $this->user; }
    public function getKey(): ?AccountConfigEnum { return $this->key; }
    
    // Helper method for string representation of enum value
    public function getKeyValue(): ?string { return $this->key?->value; }
    
    // Setter that can handle string or enum
    public function setKey(string|AccountConfigEnum $key): void
    {
        if (!$key instanceof AccountConfigEnum) {
            $key = AccountConfigEnum::from($key);
        }
        $this->key = $key;
    }
}
```

2. Configure the resource in API Platform:

```yaml
resources:
  'App\Entity\AccountConfig':
    identifiers: [user, key]
    operations:
      ApiPlatform\Metadata\Get:
        provider: 'App\State\AccountConfigProvider'
        uriTemplate: '/account_configs/{user}/{key}{._format}'
        uriVariables:
          user:
            fromClass: 'App\Entity\User'
            fromProperty: 'id'
            toProperty: 'user'
          key:
            fromClass: 'App\Entity\AccountConfig'
            fromProperty: 'keyValue'
            toProperty: 'key'
```

3. Access URL: `/api/account_configs/user_id/enum_value`

**Expected behavior**  
The request should reach the provider and be processed, allowing custom logic to handle the conversion of the string value to enum.

**Actual behavior**
Api Platform returns a 404 with "Invalid identifier value or configuration" without ever reaching the provider.

**Environment**
- API Platform version: 4.0.0
- Symfony version: 7.0.0
- PHP version: 8.3.0
- 
Thanks
