### ISSUE TITLE
[ Bug ] NelmioApiDoc: Serialization groups are ignored for collectionOperations

### ISSUE THREAD

**Issue by karser** [api-platform/core#728]
Probably there is [related closed issue](https://github.com/api-platform/core/issues/582) but I can reproduce this using v2.0.0-beta.3 as well as master.
There is a bug somewhere in [ApiPlatformParser](https://github.com/api-platform/core/blob/master/src/Bridge/NelmioApiDoc/Parser/ApiPlatformParser.php) that provides parsed attributes for NelmioApiDoc.
It should provide denormalization_context from collectionOperations (e.g "registration"), in fact, it returns global (e.g "write")

```
#src/UserBundle/Resources/config/api_resources.yml
user:
    class: UserBundle\Entity\User
    attributes:
        normalization_context: { groups: ['read'] }
        denormalization_context: { groups: ['write'] }
    collectionOperations:
        register:
            path: '/security/register'
            method: 'POST'
            normalization_context: { groups: ['read'] }
            denormalization_context: { groups: ['registration'] }
```

```
#src/UserBundle/Resources/config/serialization.yml
UserBundle\Entity\User:
    attributes:
        id:
            groups: ['login', 'read']
        accessToken:
            groups: ['login']
        username:
            groups: ['login', 'registration', 'read']
        email:
            groups: ['login', 'registration', 'read']
        plainPassword:
            groups: ['registration']
        roles:
            groups: ['login', 'user_read']
```
