### ISSUE TITLE
[Filter] Default order doesn't applied

### ISSUE THREAD

**Issue by Eraac** [api-platform/core#780]
Hi,

According to the doc for the order filter ([here](https://github.com/api-platform/docs/blob/master/core/filters.md)),

> By default, whenever the query does not specify the direction explicitly (e.g: /offers?order[name]&order[id]), filters will not be applied unless you configure a default order direction to use:

So, I guess with this configuration:

```yaml
history.order_filter:
    parent:    'api_platform.doctrine.orm.order_filter'
    arguments: [ { createdAt: 'desc' } ]
    tags:      [ { name: 'api_platform.filter', id: 'history.order' } ]
```
When I request /histories, i shoud have the latest history in first, right? But actually in my code I haven't this behaviour.

Maybe isn't a bug, and I have a lack of comprehension of the doc, but for me it's make sense to have a default order directly in configuration.

It just change one line in [OrderFilter.php:109](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Filter/OrderFilter.php#L109)

From:
```php
return $request->query->get($this->orderParameterName, []);
```
To:
```php
return $request->query->get($this->orderParameterName, $this->properties);
```

I use :
* Symfony 3.1.*
* Api-Platform ^2.0@rc
* PHP 7.0.11
