### ISSUE TITLE
Serialization groups per operation

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#795]
I only tried this with association ie `$metadata->isReadableLink()`.

Say you have your default collection on `api_foos_get_collection`, and a custom route that also gets a collection but with a different serialization context. Configuration looks like this:

```yaml
resources:
    foos:
        class: 'Bundle\Entity\Foo'
        collectionOperations:
            get:
                method: 'GET'
            post:
                method: 'POST'
            get_custom_foo_collection:
                method: 'GET'
                path: '/foos_custom'
                normalization_context: {'groups': ['bar']}
        attributes:
            normalization_context: {'groups': ['something']}
```

```php
<?php

namespace Bundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity
 * @ORM\Table(name="Foo")
 */
class Foo
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Bundle\Entity\Bar", fetch="EAGER")
     * @ORM\JoinColumn(name="bar_id", referencedColumnName="id", nullable=false)
     * @Groups({"bar"})
     */
    private $bar;
}
```

Now, request the custom collection `foos_custom`.

I `var_dump`'ed some values, first in [`SerializerPropertyMetadata` (L55)](https://github.com/api-platform/core/blob/master/src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php#L55) and then in [`EagerLoadingExtension` (L82)](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php#L82).

I can't explain what happens here, maybe you can help me figure out how the serialization flow works:

```
// first call, groups are:
array(1) {
  [0]=>
  string(14) "something"
}
// bool(false), on the propertyMetadata->isReadableLink() in EagerExtension, obvious it had not the `bar` group
array(1) {
  [0]=>
  string(19) "bar"
}
// where does this call come from? why are serialization groups correct here?
// resourceClass is the same
// $options in SerializerPropertyMetadataFactory does have the `collection_operation_name` and the correct serialization groups, but only here, not before
```

Maybe related to #728? Is this a bug or a misuse of groups?

Thanks!
