### ISSUE TITLE
RC.5: ResourceClassNotFoundException: Resource not found.

### ISSUE THREAD

**Issue by karser** [api-platform/core#849]
The error:
ApiPlatform\Core\Exception\ResourceClassNotFoundException: Resource not found.

I'm using
`"api-platform/core": "v2.0.0-rc.5"` and `"nelmio/api-doc-bundle": "~2.13.0"`.

```
#api_resources.yml
user:
    attributes:
        filters: ['user.admins_only', 'user.search_filter']
        normalization_context: { groups: ['user_read'] }
        denormalization_context: { groups: ['user_write'] }
```
The error has gone after I changed my `api_resources.yml` so it looks like this:
```
UserBundle\Entity\User:
    attributes:
        filters: ['user.admins_only', 'user.search_filter']
```

Is it bug or a new feature?

**Comment by dunglas** [comment]
It's probably a bug, can you:

* Post the full stack trace
* Post the entities's code
* Try with this setting in `config.yml`:

```yaml
api_platform:
    eager_loading:
        force_eager: false
```

Thanks!

**Comment by karser** [comment]
It worked fine with RC.4, I was surprised to see this BC, especially, you mentioned that there are bug fixes only in RC.5.
But you are not able to declare the same resource twice, so using classes as keys in yml makes more sense to me.

The stack trace:
```
FileLoaderLoadException in FileLoader.php line 118:
Resource "user" not found in . (which is being imported from "/path/to/project/app/config/routing.yml").
in FileLoader.php line 118
at FileLoader->import('.', 'api_platform', false, '/path/to/project/app/config/routing.yml') in YamlFileLoader.php line 145
at YamlFileLoader->parseImport(object(RouteCollection), array('resource' => '.', 'type' => 'api_platform', 'prefix' => '/api'), '/path/to/project/app/config/routing.yml', '/path/to/project/app/config/routing.yml') in YamlFileLoader.php line 83
at YamlFileLoader->load('/path/to/project/app/config/routing.yml', null) in FileLoader.php line 103
at FileLoader->import('/path/to/project/app/config/routing.yml', null, false, '/path/to/project/app/config/routing_dev.yml') in YamlFileLoader.php line 145
at YamlFileLoader->parseImport(object(RouteCollection), array('resource' => 'routing.yml'), '/path/to/project/app/config/routing_dev.yml', '/path/to/project/app/config/routing_dev.yml') in YamlFileLoader.php line 83
at YamlFileLoader->load('/path/to/project/app/config/routing_dev.yml', null) in DelegatingLoader.php line 45
at DelegatingLoader->load('/path/to/project/app/config/routing_dev.yml', null) in DelegatingLoader.php line 72
at DelegatingLoader->load('/path/to/project/app/config/routing_dev.yml', null) in Router.php line 54
at Router->getRouteCollection() in Router.php line 363
at Router->getGeneratorDumperInstance() in Router.php line 330
at Router->Symfony\Component\Routing\{closure}(object(ResourceCheckerConfigCache))
at call_user_func(object(Closure), object(ResourceCheckerConfigCache)) in ResourceCheckerConfigCacheFactory.php line 46
at ResourceCheckerConfigCacheFactory->cache('/path/to/project/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php', object(Closure)) in Router.php line 338
at Router->getGenerator() in Router.php line 244
at Router->generate('api_doc', array('_format' => 'jsonld'), '0') in Router.php line 91
at Router->generate('api_doc', array('_format' => 'jsonld'), '0') in AddLinkHeaderListener.php line 41
at AddLinkHeaderListener->onKernelResponse(object(FilterResponseEvent), 'kernel.response', object(TraceableEventDispatcher))
at call_user_func(array(object(AddLinkHeaderListener), 'onKernelResponse'), object(FilterResponseEvent), 'kernel.response', object(TraceableEventDispatcher)) in WrappedListener.php line 61
at WrappedListener->__invoke(object(FilterResponseEvent), 'kernel.response', object(ContainerAwareEventDispatcher))
at call_user_func(object(WrappedListener), object(FilterResponseEvent), 'kernel.response', object(ContainerAwareEventDispatcher)) in EventDispatcher.php line 174
at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.response', object(FilterResponseEvent)) in EventDispatcher.php line 43
at EventDispatcher->dispatch('kernel.response', object(FilterResponseEvent)) in TraceableEventDispatcher.php line 136
at TraceableEventDispatcher->dispatch('kernel.response', object(FilterResponseEvent)) in HttpKernel.php line 193
at HttpKernel->filterResponse(object(JsonResponse), object(Request), '2') in HttpKernel.php line 175
at HttpKernel->handleRaw(object(Request), '2') in HttpKernel.php line 68
at HttpKernel->handle(object(Request), '2', false) in ExceptionListener.php line 50
at ExceptionListener->onKernelException(object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
at call_user_func(array(object(ExceptionListener), 'onKernelException'), object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher)) in WrappedListener.php line 61
at WrappedListener->__invoke(object(GetResponseForExceptionEvent), 'kernel.exception', object(ContainerAwareEventDispatcher))
at call_user_func(object(WrappedListener), object(GetResponseForExceptionEvent), 'kernel.exception', object(ContainerAwareEventDispatcher)) in EventDispatcher.php line 174
at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.exception', object(GetResponseForExceptionEvent)) in EventDispatcher.php line 43
at EventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent)) in TraceableEventDispatcher.php line 136
at TraceableEventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent)) in HttpKernel.php line 230
at HttpKernel->handleException(object(FileLoaderLoadException), object(Request), '1') in HttpKernel.php line 79
at HttpKernel->handle(object(Request), '1', true) in Kernel.php line 169
at Kernel->handle(object(Request)) in app_dev.php line 30
```

api_resources.yml:
```
user:
    class: UserBundle\Entity\User
    attributes:
        filters: ['user.admins_only', 'user.search_filter']
        normalization_context: { groups: ['user_read'] }
        denormalization_context: { groups: ['user_write'] }
```

serialization.yml:
```
UserBundle\Entity\User:
    attributes:
        id:
            groups: ['login', 'user_read']
        accessToken:
            groups: ['login']
        username:
            groups: ['login', 'registration', 'user_read', 'user_write']
        email:
            groups: ['login', 'registration', 'user_read', 'user_write']
```

The entity class
```
/**
 * @ORM\Entity(repositoryClass="UserBundle\Repository\UserRepository")
 * @ORM\Table()
 */
class User extends BaseUser implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    protected $accessToken;

    //other fields and methods are trivial, nothing fancy here.
```

`force_eager: false` changes nothing, the same error.
