### ISSUE TITLE
Not recognizing a relationship ManyToOne between entities

### ISSUE THREAD

**Issue by hugohenrique** [api-platform/core#892]
I have two entities relationship.

```php
/**
 * @ORM\Entity(repositoryClass="Infrastructure\ORM\Repository\DoctrineBidRepository")
 * @ORM\Table(name="bids")
 */
class Bid
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint", length=20)
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Supplier")
     */
    private $supplier;

    /**
     * @var Order
     *
     * @ORM\ManyToOne(targetEntity="Domain\Order\Order", inversedBy="bids")
     */
    private $order;
```

In another entity:

```php
/**
 * @ORM\Entity(repositoryClass="Infrastructure\ORM\Repository\DoctrineOrderRepository")
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Domain\User\User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="Domain\Supplier\Bid", mappedBy="order")
     */
    private $bids;
```

In my resources.yml

```yml
resources:
    Domain\Order\Order:
        shortName: "Order"
        itemOperations:
            get:
                method: "GET"
        collectionOperations:
            get:
                method: "GET"
    Domain\Supplier\Bid:
        shortName: "Bid"
        itemOperations:
            get:
                method: "GET"
        collectionOperations:
            get:
                method: "GET"
```

On ```localhost/api``` swagger:
```json
[
  {
    "id": 0,
    "supplier": "string",
    "order": "string",
    "annotation": [
      "string"
    ],
    "rating": "string",
    "closed": {},
    "answered": true,
    "open": true,
    "expired": true,
    "answers": [
      "string"
    ]
  }
]
```

In other words, it only recognizes as a string.
As result:

```json
[
  {
    "id": "2",
    "supplier": "/api/enterprises/3",
    "order": "/api/orders/2",
    "rating": null,
    "answered": true,
    "open": false,
    "expired": true
  }
]
```

**Does anyone know what can it be?**

**Comment by hugohenrique** [comment]
Other likely bug is:
<img width="964" alt="screen shot 2016-12-21 at 20 28 05" src="https://cloud.githubusercontent.com/assets/4316743/21409959/3b161816-c7bc-11e6-88c4-8b0b2e0a91e5.png">
<img width="965" alt="screen shot 2016-12-21 at 20 27 48" src="https://cloud.githubusercontent.com/assets/4316743/21409960/3b19164c-c7bc-11e6-9f80-a10176f698c8.png">

**Comment by dunglas** [comment]
For your 1st report, it's intended. By default API Platform returns links to relations (its URL), but Swagger doesn't have a the notion of IRI/URL. For Swagger "/api/enterprises/3" is just a plain old string.
If you care about relation typing, use the Hydra doc instead.

**Comment by hugohenrique** [comment]
@dunglas, thanks for reply 👍 

In fact the problem we identify is that it does not return the object. And yes to URI.

**Comment by dunglas** [comment]
Your second report looks like a bug. We use Swagger UI to generate the doc, please report this bug upstream: https://github.com/swagger-api/swagger-ui/issues

**Comment by dunglas** [comment]
You can make API Platform returning an object instead of the IRI: https://api-platform.com/docs/core/serialization-groups-and-relations#embedding-relations

**Comment by hugohenrique** [comment]
A very important detail the entity Provider is abstract.

```php
/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ProviderRepository")
 * @ORM\Table(name="provider")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="string", length=36)
 * @ORM\DiscriminatorMap({
 *   "personal"="AppBundle\Entity\Personal",
 *   "enterprise"="AppBundle\Entity\Enterprise"
 * })
 * @ORM\HasLifecycleCallbacks
 */
abstract class Provider
{
    /**
     * @var integer
     *
     * @ORM\Id
     * @ORM\Column(type="bigint", options={"unsigned"=true})
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    // ...
```

**Comment by hugohenrique** [comment]
@dunglas, I've detected that the problem is happening when the mapping is done with YML.
I did the mapping using annotations and it worked correctly.

**Comment by soyuka** [comment]
Which mapping api-platform ones?

**Comment by hugohenrique** [comment]
Yes! ```resources.yml```

```yml
resources:
    Domain\Order\Order:
        shortName: "Order"
        itemOperations:
            get:
                method: "GET"
        collectionOperations:
            get:
                method: "GET"
    Domain\Supplier\Bid:
        shortName: "Bid"
        itemOperations:
            get:
                method: "GET"
        collectionOperations:
            get:
                method: "GET"
```

**Comment by hugohenrique** [comment]
For some reason it is not recognizing entities that are outside AppBundle...

In my config.yml I customize the entity directories:
```yaml
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
        mappings:
            domain:
                type: annotation
                dir: "%kernel.root_dir%/../src/Domain"
                prefix: Domain
                is_bundle: false
```
