### ISSUE TITLE
How to serialize objects manually?

### ISSUE THREAD

**Issue by ybouhjira** [api-platform/core#903]
I wrote this listener to include the user object in the JWT success. But I don't know how to serialize the `Utilisateur` object, if I use the serializer service I get an empty json object `{}`

services.yml
```YAML
    app.event_listeners.jwt_response_changer_listener:
        class: AppBundle\EventListener\JWTResponseChangerListener
        arguments: [ '@doctrine.orm.entity_manager', '@api_platform.serializer' ]
        tags:
            - name: kernel.event_listener
              event: kernel.response
              priority: 
```
JWTResponseChangerListener.php
```php
<?php

namespace AppBundle\EventListener;

use AppBundle\Entity\Utilisateur;
use Doctrine\ORM\EntityManager;
use Symfony\Component\HttpKernel\Event\FilterResponseEvent;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Serializer\Serializer;

class JWTResponseChangerListener
{

    public function __construct(EntityManager $entityManager, Serializer $serializer)
    {
        $this->em = $entityManager;
        $this->serializer = $serializer;
    }

    public function onKernelResponse(FilterResponseEvent $event)
    {
        if (!$this->routeIsLoginRoute($event) || !$this->hasToken($event))
            return;

        $username = $event->getRequest()->get('_username');
        /** @var Utilisateur $user */
        $user = $this->em
            ->getRepository('AppBundle:Utilisateur')
            ->findBy(['username' => $username])[0];

        $content = json_decode($event->getResponse()->getContent());
        $content->utilisateur = [
            '@id' => '/utilisateurs/' . $user->getId(),
            '@type' => preg_replace('#.*\\\\#', '', get_class($user))
        ];

        $event->getResponse()->setContent(
            $this->serializer->encode($content, 'json')
        );
    }

    private function routeIsLoginRoute($event)
    {
        return $event->getRequest()->get('_route') === 'api_login_check';
    }

    private function hasToken(FilterResponseEvent $event)
    {
        return !empty(json_decode($event->getResponse()->getContent())->token);
    }
}
```

Utilisateur.php
```php
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use FOS\UserBundle\Model\UserInterface;
use JMS\Serializer\Annotation\ExclusionPolicy;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="_type", type="string")
 */
abstract class Utilisateur extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Groups({"read", "write", "invit-read"})
     */
    protected $email;

    /**
     * @Groups({"write"})
     */
    protected $plainPassword;

    /**
     * @Groups({"read", "write"})
     */
    protected $username;

    /**
     * User constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->addRole('ROLE_USER');
    }

    public function isUser(UserInterface $user = null)
    {
        return $user instanceof self && $user->id === $this->id;
    }
}
```
resources.yml
```yaml
AppBundle\Entity\Utilisateur:
    attributes:
        normalization_context: { groups: ['read'] }
        denormalization_context: { groups: ['write'] }
        filters: ['utilisateur.username_filter']
```
