### ISSUE TITLE
Best way to add the link for a custom operation?

### ISSUE THREAD

**Issue by ybouhjira** [api-platform/core#908]
I made a custom operation that lists a sub-resources `/posts/1/images`. What is the recommended way to add the `"images": "/posts/1/images"` link to the Post resource?

I did this, but I thought there should be a better way: 
```php
class Post {
// ...
    /**
     * @Groups({"read"})
     * @return string
     */
    public function getImagesList()
    {
        return 'posts/' . $this->getId() . '/images';
    }

// ...
}
```

**Comment by dunglas** [comment]
I would use a custom normalizer to change replace to set the path in place of the File object.

**Comment by ybouhjira** [comment]
@dunglas Is there any doc about how to do this?

**Comment by dunglas** [comment]
It's just a good old Symfony normalizer: http://symfony.com/doc/current/serializer.html#adding-normalizers-and-encoders

**Comment by ybouhjira** [comment]
I've made my custom serializer class and Added it to services.yml but it's not getting loaded. I inject ObjectNormalizer in my normalizer to reuse it. 

```yaml
object_normalizer:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    app.resource_normalizer:
        class: AppBundle\Service\Normalizer\ResourceNormalizer
        public: false
        arguments: ['@object_normalizer']
        tags:
            - name: serializer.normalizer
              priority: 99
```

```php
<?php

namespace AppBundle\Service\Normalizer;

use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;

/**
 * Custom normalizer
 */
class ResourceNormalizer implements NormalizerInterface
{
    /**
     * @var ObjectNormalizer
     */
    private $objectNormalizer;

    public function __construct(ObjectNormalizer $objectNormalizer)
    {
        $this->objectNormalizer = $objectNormalizer;
    }

    /**
     * Normalizes an object into a set of arrays/scalars.
     *
     * @param object $object object to normalize
     * @param string $format format the normalization result will be encoded as
     * @param array $context Context options for the normalizer
     *
     * @return array
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $this->normalize($object, $format, $context);
    }

    /**
     * Checks whether the given class is supported for normalization by this normalizer.
     *
     * @param mixed $data Data to normalize
     * @param string $format The format being (de-)serialized from or into
     *
     * @return bool
     */
    public function supportsNormalization($data, $format = null)
    {
        $this->objectNormalizer->supportsNormalization($data, $format);
    }
}
```

**Comment by ybouhjira** [comment]
I made this quick solution and it's working. But is there a way to get all the routes that begin with a string without iterating on all routes?
```yaml
    app.resource_normalizer:
        class: AppBundle\Service\Normalizer\ResourceNormalizer
        public: false
        arguments:
            - '@api_platform.jsonld.normalizer.item'
            - '@router'
        tags:
            - name: serializer.normalizer
              priority: 99
```

```php
<?php

namespace AppBundle\Service\Normalizer;

use Symfony\Bundle\FrameworkBundle\Routing\Router;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

/**
 * Custom normalizer
 */
class ResourceNormalizer implements NormalizerInterface
{
    /**
     * @var NormalizerInterface
     */
    private $baseNormalizer;

    /**
     * @var Router
     */
    private $router;

    public function __construct(NormalizerInterface $baseNormalizer,
                                Router $router)
    {
        $this->baseNormalizer = $baseNormalizer;
        $this->router = $router;
    }


    /**
     * Normalizes an object into a set of arrays/scalars.
     *
     * @param object $object object to normalize
     * @param string $format format the normalization result will be encoded as
     * @param array $context Context options for the normalizer
     *
     * @return array
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $normalized = $this->baseNormalizer->normalize($object, $format, $context);

        $resourceName = strtolower(
            (new \ReflectionClass($object))->getShortName()
        );

        $routePrefix = "{$resourceName}_get_";
        $routes = $this->router->getRouteCollection()->getIterator();

        foreach ($routes as $name =>$route) {
            if (preg_match("/^$routePrefix/", $name)) {
                $matches = [];
                preg_match("/_get_(.*)/", $name, $matches);

                $subResRouteName = $routePrefix . $matches[1];
                $routePath = $this->router
                    ->getRouteCollection()
                    ->get($subResRouteName)
                    ->getPath();

                $url = preg_replace('/\\{id\\}/', $object->getId(), $routePath);

                $normalized[$matches[1]] = $url;
            }
        }

        return $normalized;
    }

    /**
     * Checks whether the given class is supported for normalization by this normalizer.
     *
     * @param mixed $data Data to normalize
     * @param string $format The format being (de-)serialized from or into
     *
     * @return bool
     */
    public function supportsNormalization($data, $format = null)
    {
        return $this->baseNormalizer->supportsNormalization($data, $format);
    }
}
```
