### ISSUE TITLE
[Question] Exposing custom endpoint

### ISSUE THREAD

**Issue by aistis-** [api-platform/core#936]
Hi guys,

I am trying to implement a custom case endpoint.

Basically I need an endpoint to GET product price (let's call it `/price/{product}`).

My code:

```
# Random/Bundle/ApiBundle/Resources/config/api_resources/resources.yml
resources:
    Random\Bundle\ApiBundle\Model\Price:
        collectionOperations: []
        itemOperations:
            get:
                route_name: random_api_price_get
```

```
# ... /routing.yml
random_api_price_get:
    path: /{id}
    defaults:
        _controller: 'random_api.action.price.get'
        _api_resource_class: 'Random\Bundle\ApiBundle\Model\Price'
        _api_item_operation_name: get
```

```
<?php
// src/Random/Bundle/ApiBundle/Action/Price/GetPriceAction.php

...
use Random\Bundle\ApiBundle\Model\Price;
...

public function __invoke(Request $request, $product)
    {
        $context = $this->some_injected_service_1->create(product, request);
        $prices = $this->some_injected_service_2->calculate($context);

        return new Price($prices->getInitial(), $prices->getFinal());
    }
```

**My problems**:

1. I get an error `Not Found` cause by `ReadListener`, because no DataProvider supports `Price`. Can I skip using `DataProvider` and use my magic fetching logic in `GetPriceAction` instead?
2. Did I understand correctly, that I always need to return a single (or array for collections) object (`Price`) to have my object serialized with api-platform hooks?
