### ISSUE TITLE
[Question] Entity relation as id serializing and deserializing with referenced entities

### ISSUE THREAD

**Issue by aistis-** [api-platform/core#957]
Hi!

I am creating an endpoint for Category and I want to get a feedback of my implementation to check is it the "API-platform way" of doing that.

I have a Category:

```
class Category
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var Category|null
     */
    private $parent;

    /**
     * @return string
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * @param string $id
     *
     * @return Category
     */
    public function setId(string $id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return Category|null
     */
    public function getParent(): Category
    {
        return $this->parent;
    }

    /**
     * @param Category|null $parent
     *
     * @return Category
     */
    public function setParent(?Category $parent)
    {
        $this->parent = $parent;

        return $this;
    }
```

with doctrine ORM mapping in YAML:

```
MyBundle\Entity\Category:
    type: entity
    table: my_category
    fields:
        id:
            id: true
            type: string
            length: 100
            generator:
                strategy: none
    manyToOne:
        parent:
            targetEntity: MyBundle\Entity\Category
            joinColumn:
                onDelete: CASCADE
```

My serialization mapping:
```
MyBundle\Entity\Category:
    attributes:
        id:
            groups: ['Category']
        parent:
            groups: ['Category']
```

resource descriptor:
```
resources:
    MyBundle\Entity\Category:
        attributes:
            normalization_context:
                groups: ['Category']
```

It is exposing these endpoints:
![screen](https://sc-cdn.scaleengine.net/i/37ef47a45a02878b74e4434d67d3226c.png)

**Question:**
I am thinking, that passing parent an object is a complex way of API data structure. How could I achieve exposing API in:
```
[
  {
    "id": "string",
    "parent_id": "string"
  }
]
```
and also accept the same format in `POST` or `PUT`, so the default entity CRUD handling would hook up on it?
