### ISSUE TITLE
Likely bug: Does not recognize a new normalizer

### ISSUE THREAD

**Issue by hugohenrique** [api-platform/core#977]
When changing to the PropertyNormalizer as default:

**api_resources.yml**
```yaml
Domain\Offer\OfferPoint:
    shortName: 'offerpoint'
    attributes:
        normalization_context:
            groups: ['read']
    collectionOperations:
        get:
            method: 'GET'
```
**services.yml**
```yaml
    property_normalizer:
        class: Symfony\Component\Serializer\Normalizer\PropertyNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }
```
**AppBundle\Resources\serialization/offerpoint.yml**
```yaml
Domain\Offer\OfferPoint:
    attributes:
        id:
            groups: ['read']
        startAt:
            groups: ['read']
```
As result to GET ```/api/offerpoints```
```json
[{
    "id": {
        "codec": {
            "builder": {
                "converter": []
            }
        },
        "fields": {
            "time_low": "a82b17eb",
            "time_mid": "23c8",
            "time_hi_and_version": "481d",
            "clock_seq_hi_and_reserved": "93",
            "clock_seq_low": "78",
            "node": "f779b5512408"
        },
        "converter": []
    },
    "startAt": "2017-03-08T00:00:00-03:00",
    "endAt": null,
    "ticketLimit": 10,
    "status": {
        "string": "actived"
    },
    "offerId": [],
    "requirementId": []
}]
```
But in swagger-ui show:
![screenshot from 2017-03-10 12-56-27](https://cloud.githubusercontent.com/assets/4316743/23802210/58af72ce-0591-11e7-9875-7558e9e04b73.png)

**Exepected result should be:**
```json
[{
    "id": {
        "codec": {
            "builder": {
                "converter": []
            }
        },
        "fields": {
            "time_low": "a82b17eb",
            "time_mid": "23c8",
            "time_hi_and_version": "481d",
            "clock_seq_hi_and_reserved": "93",
            "clock_seq_low": "78",
            "node": "f779b5512408"
        },
        "converter": []
    },
    "startAt": "2017-03-08T00:00:00-03:00"
}]
```
Does anyone think what it can be?
