### ISSUE TITLE
dynamic pagination

### ISSUE THREAD

**Issue by mitalcoi** [api-platform/core#999]
I try to disable pagination in ```ContextBuilder```, but it doesn't effect on "pagination_enabled" attribute:
```php
namespace AppBundle\Serializer;

use ApiPlatform\Core\Serializer\SerializerContextBuilderInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\PropertyAccess\PropertyAccess;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

/**
 * Class CampaignContextBuilder
 * @package AppBundle\Serializer
 */
final class CampaignContextBuilder implements SerializerContextBuilderInterface
{
    private $decorated;

    public function __construct(
        SerializerContextBuilderInterface $decorated
    ) {
        $this->decorated = $decorated;
    }

    /**
     * @param Request $request
     * @param bool $normalization
     * @param array|null $extractedAttributes
     * @return array
     */
    public function createFromRequest(Request $request, bool $normalization, array $extractedAttributes = null): array
    {
        $context = $this->decorated->createFromRequest($request, $normalization, $extractedAttributes);  
        $context['pagination_enabled'] = false;

        return $context;
    }
}
```
```
    app.serializer.builder.campaign:
        decorates: api_platform.serializer.context_builder
        class: AppBundle\Serializer\CampaignContextBuilder
        arguments: ['@app.serializer.builder.campaign.inner']
```
But my collection still paginated :(
